"""Chinese presentation helpers for immutable audit evidence.

These helpers only transform the read-time projection. Stored AuditLog rows,
exact filters and raw technical codes remain unchanged.
"""

from __future__ import annotations

import re
from collections.abc import Mapping

from apps.accounts.roles import ROLE_LABELS
from apps.audit.permissions import AUDIT_OBJECT_TYPE_REGISTRY
from apps.audit.services import REDACTED


ACTION_LABELS = {
    "account.bootstrap_created": "创建首批应用用户",
    "account.local_access_reset": "重置本地验收账号",
    "account.local_bootstrap_created": "创建本地验收账号",
    "auth.login_failed": "登录失败",
    "auth.login_succeeded": "登录成功",
    "user_create": "创建应用用户",
    "roles_update": "更新用户固定角色",
    "scope_assign": "分配部门数据范围",
    "scope_revoke": "撤销部门数据范围",
    "create": "创建基础资料",
    "update": "更新基础资料",
    "manager_cleared": "清除部门负责人",
    "initialization_complete": "完成初始化",
    "setup_progress_update": "更新初始化进度",
    "setup_coding_progress_update": "更新编码规则进度",
    "setup_finance_progress_update": "更新财务规则进度",
    "asset_draft_create": "创建资产草稿",
    "asset_draft_update": "更新资产草稿",
    "asset_draft_scope_update": "更新资产草稿责任范围",
    "asset_draft_delete": "删除资产草稿",
    "asset_submit_finance": "提交财务确认",
    "asset_withdraw_to_draft": "撤回为资产草稿",
    "asset_coding_scheme_select": "指定资产编码方案",
    "asset_forbidden_field_attempt": "拦截无权字段提交",
    "asset_attachment_create": "上传资产附件",
    "asset_attachment_download": "下载资产附件",
    "asset_attachment_void": "作废资产附件",
    "asset_code_issue": "签发正式资产编号",
    "asset_code.corrected": "更正正式资产编号",
    "asset_finance_draft_save": "保存资产财务草稿",
    "asset_finance_confirm": "确认资产财务资料",
    "asset_qr_identity_create": "创建资产二维码身份",
    "asset_label.print_generated": "生成标签打印批次",
    "asset_label.print_confirmed": "记录标签打印",
    "asset_label.print_cancelled": "取消标签打印批次",
    "asset_label.attached": "确认资产已贴标",
    "asset_qr.rotated": "更换资产二维码",
    "asset_qr.scan_denied": "拒绝无权扫码",
    "asset_lifecycle.assignment_changed": "变更资产责任归属",
    "asset_lifecycle.loaned": "登记资产借出",
    "asset_lifecycle.loan_returned": "登记资产归还",
    "asset_disposal.initiated": "发起资产处置",
    "asset_disposal.actual_details_recorded": "登记处置实际信息",
    "asset_disposal.finance_locked": "锁定处置财务快照",
    "asset_disposal.completed": "完成资产处置",
    "asset_disposal.cancelled": "取消资产处置",
    "asset_disposal.reversed": "冲销资产处置",
    "asset_disposal.attachment_uploaded": "上传处置附件",
    "asset_disposal.attachment_voided": "作废处置附件",
    "coding_scheme_create": "创建编码方案",
    "coding_scheme_update": "更新编码方案",
    "coding_scheme_activate": "启用编码方案",
    "coding_scheme_retire": "退役编码方案",
    "coding_scheme_clone": "克隆编码方案",
    "coding_scheme_default_set": "设置默认编码方案",
    "coding_scheme_default_unset": "取消默认编码方案",
    "coding_segments_replace": "更新编码片段",
    "category_default_coding_scheme_set": "设置分类默认编码方案",
    "fixed_asset_category_create": "创建固定资产类别",
    "fixed_asset_category_update": "更新固定资产类别",
    "fixed_asset_category_deactivate": "停用固定资产类别",
    "fixed_asset_category_delete": "删除固定资产类别草稿",
    "depreciation_policy_create": "创建折旧政策",
    "depreciation_policy_update": "更新折旧政策",
    "depreciation_policy_activate": "启用折旧政策",
    "depreciation_policy_retire": "退役折旧政策",
    "depreciation_policy_clone": "克隆折旧政策",
    "depreciation_policy_default_set": "设置默认折旧政策",
    "category_default_depreciation_policy_set": "设置分类默认折旧政策",
    "depreciation_profile_version_create": "创建折旧配置版本",
    "depreciation_profile_continuation_review": "复核实际接续日",
    "depreciation_batch_generate": "生成折旧批次",
    "depreciation_batch_confirm": "确认折旧批次",
    "depreciation_batch_reverse": "冲销折旧批次",
    "asset_work_usage_record": "登记资产工作量",
    "asset_value_adjustment_confirm": "确认资产价值调整",
    "asset_value_adjustment_reverse": "冲销资产价值调整",
    "theoretical_depreciation_run": "执行理论折旧试算",
    "import_upload": "上传导入文件",
    "import_validate": "校验导入批次",
    "import_confirm": "确认导入批次",
    "import_confirm_failed": "导入确认失败",
    "import_failure": "导入处理失败",
    "import_abandon": "放弃导入批次",
    "import_cleanup": "清理导入批次",
    "import_temp_cleanup": "清理导入临时文件",
    "attachment_cleanup": "清理附件暂存",
    "asset_finance_import_draft_create": "创建财务导入草稿",
    "depreciation_profile_import_draft_create": "创建折旧配置导入草稿",
    "inventory.task_created": "创建盘点任务",
    "inventory.task_updated": "更新盘点任务",
    "inventory.task_published": "发布盘点任务",
    "inventory.scanning_stopped": "停止盘点扫码",
    "inventory.task_closed": "关闭盘点任务",
    "inventory.task_cancelled": "取消盘点任务",
    "inventory.scan_supplemented": "补录盘点扫码",
    "inventory.difference_resolved": "处理盘点差异",
    "inventory.resolution_corrected": "更正盘点结论",
    "inventory.surplus_created": "登记盘盈",
    "inventory.surplus_resolved": "处理盘盈",
    "inventory.surplus_converted": "盘盈转资产草稿",
    "inventory.attachment_uploaded": "上传盘点附件",
    "inventory.attachment_voided": "作废盘点附件",
    "maintenance.plan_created": "创建保养计划",
    "maintenance.plan_updated": "更新保养计划",
    "maintenance.plan_status_changed": "变更保养计划状态",
    "maintenance.completed": "完成保养",
    "maintenance.record_voided": "作废保养记录",
    "maintenance.problem_closed": "关闭保养问题",
    "maintenance.attachment_uploaded": "上传保养附件",
    "maintenance.attachment_voided": "作废保养附件",
    "maintenance.plan_ended_by_disposal": "处置联动终止保养计划",
    "maintenance.plan_restored_by_disposal": "处置冲销恢复保养计划",
    "employee_offboarding.initiated": "发起离职资产清退",
    "employee_offboarding.refreshed": "刷新离职清退清单",
    "employee_offboarding.item_synchronized": "同步离职清退项目",
    "employee_offboarding.completed": "完成离职资产清退",
    "employee_offboarding.supplement_created": "创建补充清退",
    "employee_offboarding.attachment_uploaded": "上传清退附件",
    "employee_offboarding.attachment_downloaded": "下载清退附件",
    "employee_offboarding.attachment_voided": "作废清退附件",
    "asset_external_reference_created": "创建 T+ 资产卡片编码",
    "asset_external_reference_corrected": "更正 T+ 资产卡片编码",
    "report_export_requested": "申请生成报表",
    "report_export_completed": "完成报表生成",
    "report_export_failed": "报表生成失败",
    "report_export_downloaded": "下载报表",
    "backup.requested": "申请生成备份",
    "backup.completed": "完成数据备份",
    "backup.failed": "数据备份失败",
    "backup.expired": "数据备份到期",
    "backup.stale_failed": "标记超时备份失败",
    "backup.download_authorized": "授权备份下载",
    "backup.download_started": "开始备份下载",
    "backup.reauthentication_failed": "备份身份确认失败",
    "finance.changed": "财务资料变更",
    "employee.changed": "人员资料变更",
    "profile.changed": "折旧配置变更",
    "asset.changed": "资产资料变更",
}


FIELD_LABELS = {
    "accounting_treatment": "会计认定",
    "accounting_treatment_reason": "会计认定原因",
    "acquisition_date": "购置日期",
    "annual_posting_month": "年度计提月份",
    "asset": "资产",
    "asset_code": "资产编号",
    "asset_count": "资产数量",
    "asset_id": "资产 ID",
    "asset_name": "资产名称",
    "asset_status": "资产状态",
    "auto_cancelled_preview_batches": "自动取消预览批次数",
    "automatic": "自动处理",
    "brand": "品牌",
    "capitalization_date": "资本化日期",
    "categories_configured": "实物分类已配置",
    "category": "实物分类",
    "category_level": "分类层级",
    "category_scope_level": "分类作用层级",
    "category_type": "分类类型",
    "code": "编码",
    "coding_scheme_configured": "编码规则已配置",
    "commissioning_date": "达到可使用状态日期",
    "company_configured": "公司已配置",
    "confirmation_method": "确认方式",
    "completed_at": "完成时间",
    "completed_by": "完成人",
    "currency": "币种",
    "custom_values": "扩展字段值",
    "data_snapshot_at": "数据快照时间",
    "default_salvage_amount": "默认残值金额",
    "default_salvage_mode": "默认残值方式",
    "default_salvage_rate": "默认残值率",
    "default_useful_life_months": "默认使用寿命（月）",
    "department": "部门",
    "departments_configured": "部门已配置",
    "description": "说明",
    "display_name": "显示名称",
    "effective_from": "生效开始日期",
    "effective_to": "生效结束日期",
    "email": "电子邮箱",
    "employee_no": "员工编号",
    "employees_configured": "人员已配置",
    "employment_status": "任职状态",
    "explicit_reprint": "明确重新打印",
    "factory_number": "出厂编号",
    "file_size": "文件大小",
    "finance_remark": "财务备注",
    "finance_rules_configured": "财务规则已配置",
    "fixed_asset_category": "固定资产类别",
    "fixed_asset_category_id": "固定资产类别 ID",
    "fixed_value": "固定值",
    "format_string": "格式字符串",
    "hire_date": "入职日期",
    "historical_code": "历史参考编号",
    "include_descendants": "包含下级部门",
    "initial_department": "初始部门范围",
    "initialization_completed": "初始化已完成",
    "initialization_source": "初始化来源",
    "is_active": "启用状态",
    "is_default": "是否默认",
    "is_maintenance_required": "是否需要保养",
    "is_maintenance_required_default": "默认需要保养",
    "issued_code_id": "已发编号 ID",
    "items": "明细",
    "key": "设置键",
    "kind": "类型",
    "label_status": "标签状态",
    "level": "层级",
    "location": "位置",
    "location_type": "位置类型",
    "locations_configured": "位置已配置",
    "manager_employee": "部门负责人",
    "manufacturer": "生产厂家",
    "method": "折旧方法",
    "mime_type": "文件类型",
    "mobile": "手机号码",
    "model": "型号",
    "name": "名称",
    "nested": "嵌套内容",
    "normalized_code": "规范化编码",
    "note": "说明",
    "notes": "备注",
    "original_cost": "原值",
    "package_sha256": "备份包 SHA-256",
    "package_size": "备份包大小",
    "parent": "上级记录",
    "permissions_configured": "权限已配置",
    "policy_key": "政策稳定键",
    "posting_period": "计提周期",
    "printed_at": "打印操作时间",
    "printed_by": "打印操作人",
    "previous_version_id": "上一版本 ID",
    "profile_id": "折旧配置 ID",
    "qr_identity_id": "二维码身份 ID",
    "quantity": "数量",
    "reason": "原因",
    "remark": "备注",
    "request_fingerprint": "请求指纹",
    "reset_mode": "重置方式",
    "responsible_employee": "责任人",
    "role": "角色",
    "roles": "固定角色",
    "safe_note": "安全备注",
    "secret_key": "敏感密钥",
    "file_contents": "文件内容",
    "api_token": "访问令牌",
    "cookie": "Cookie（已脱敏）",
    "schedule_input_mode": "计划输入方式",
    "scheme_key": "方案稳定键",
    "security_class": "安全等级",
    "segment_type": "片段类型",
    "segments": "编码片段",
    "sequence_length": "流水号长度",
    "sequence_order": "片段顺序",
    "sequence_start": "流水号起始值",
    "serial_number": "序列号",
    "sha256": "SHA-256",
    "short_name": "简称",
    "start_rule": "折旧起算规则",
    "status": "状态",
    "stop_rule": "折旧停止规则",
    "submitted_at": "提交时间",
    "submitted_by": "提交人",
    "template_version": "模板版本",
    "termination_date": "离职日期",
    "timezone": "时区",
    "unit": "单位",
    "useful_life_months_default": "默认寿命（月）",
    "user": "用户",
    "username": "用户名",
    "users_configured": "用户已配置",
    "value": "值",
    "value_type": "值类型",
    "version": "版本",
    "work_unit": "工作量单位",
    "zero_pad": "前导零补齐",
}


VALUE_LABELS = {
    **ROLE_LABELS,
    "active": "启用",
    "inactive": "停用",
    "draft": "草稿",
    "pending_finance": "待财务确认",
    "pending_label": "待贴标",
    "pending": "待处理",
    "running": "进行中",
    "in_use": "在用",
    "idle": "闲置",
    "generated": "已生成",
    "ready_to_print": "待打印",
    "printed": "已打印",
    "attached": "已贴标",
    "scan": "扫码确认",
    "scan_opaque_origin": "Edge 扫码兼容确认",
    "web": "Web 确认",
    "completed": "已完成",
    "failed": "失败",
    "expired": "已过期",
    "started": "已开始",
    "consumed": "已使用",
    "cancelled": "已取消",
    "confirmed": "已确认",
    "revoked": "已撤销",
    "fixed_asset": "固定资产",
    "controlled_non_fixed": "受控非固定资产",
    "straight_line": "年限平均法",
    "units_of_production": "工作量法",
    "double_declining_balance": "双倍余额递减法",
    "sum_of_years_digits": "年数总和法",
    "manual": "手工折旧",
    "no_depreciation": "不计提折旧",
    "monthly": "按月",
    "yearly": "按年",
    "rate": "残值率",
    "amount": "固定残值金额",
    "automatic": "自动",
    "manual_backup": "手动备份",
    "A1": "财务敏感附件",
    "P1": "受限实物附件",
    REDACTED: "已脱敏",
}


_ACTION_TOKEN_LABELS = {
    "create": "创建",
    "created": "创建",
    "update": "更新",
    "updated": "更新",
    "changed": "变更",
    "confirm": "确认",
    "confirmed": "确认",
    "failed": "失败",
    "asset": "资产",
    "finance": "财务",
    "employee": "人员",
    "profile": "折旧配置",
    "login": "登录",
    "auth": "认证",
    "succeeded": "成功",
}


def audit_action_label(action: str) -> str:
    if action in ACTION_LABELS:
        return ACTION_LABELS[action]
    tokens = [token for token in re.split(r"[._-]+", str(action)) if token]
    if tokens and all(token in _ACTION_TOKEN_LABELS for token in tokens):
        return "".join(_ACTION_TOKEN_LABELS[token] for token in tokens)
    return "其他操作"


def audit_object_label(object_type: str) -> str:
    return AUDIT_OBJECT_TYPE_REGISTRY.get(object_type, "其他对象")


def _localize_value(value, *, parent_key=""):
    if isinstance(value, Mapping):
        return {
            FIELD_LABELS.get(str(key), str(key)): _localize_value(
                item,
                parent_key=str(key),
            )
            for key, item in value.items()
        }
    if isinstance(value, (list, tuple, set, frozenset)):
        return [_localize_value(item, parent_key=parent_key) for item in value]
    if isinstance(value, bool):
        return "是" if value else "否"
    if value is None:
        return "未填写"
    if isinstance(value, str):
        if parent_key in {"roles", "role"}:
            return ROLE_LABELS.get(value, value)
        if parent_key == "kind" and value == "manual":
            return "手动"
        return VALUE_LABELS.get(value, value)
    return value


def localize_audit_payload(payload):
    return _localize_value(payload)


__all__ = [
    "ACTION_LABELS",
    "FIELD_LABELS",
    "audit_action_label",
    "audit_object_label",
    "localize_audit_payload",
]
