# Generated by Django 5.2.17 on 2026-08-13 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0011_remove_attachmentlink_ck_attachment_link_one_target_and_more'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssetClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplement_reason', models.TextField(blank=True, verbose_name='补充清退原因')),
                ('initiated_at', models.DateTimeField(verbose_name='发起时间')),
                ('total_assets_snapshot', models.PositiveIntegerField(default=0, verbose_name='资产总数')),
                ('unresolved_assets', models.PositiveIntegerField(default=0, verbose_name='未解决资产数')),
                ('status', models.CharField(choices=[('open', '处理中'), ('blocked', '存在未清资产'), ('completed', '已完成'), ('cancelled', '已取消')], default='open', max_length=16, verbose_name='状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_asset_clearances', to='masterdata.company', verbose_name='公司')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_employee_asset_clearances', to=settings.AUTH_USER_MODEL, verbose_name='完成人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_clearances', to='masterdata.employee', verbose_name='离职员工')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_employee_asset_clearances', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('supplements_clearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplementary_clearances', to='offboarding.employeeassetclearance', verbose_name='被补充的原清退单')),
            ],
            options={
                'verbose_name': '员工离职资产清退',
                'verbose_name_plural': '员工离职资产清退',
                'ordering': ('-initiated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssetClearanceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('responsibility', '当前责任'), ('internal_loan', '内部借用'), ('both', '当前责任及内部借用')], max_length=24, verbose_name='来源类型')),
                ('association_effective_at', models.DateTimeField(verbose_name='关联生效时间')),
                ('discovered_at', models.DateTimeField(verbose_name='发现时间')),
                ('addition_reason', models.TextField(blank=True, verbose_name='后补原因')),
                ('asset_code_snapshot', models.CharField(max_length=64, verbose_name='资产编号快照')),
                ('asset_name_snapshot', models.CharField(max_length=200, verbose_name='资产名称快照')),
                ('original_department_snapshot', models.CharField(max_length=200, verbose_name='原部门快照')),
                ('original_employee_snapshot', models.CharField(max_length=200, verbose_name='原责任人快照')),
                ('original_location_path_snapshot', models.CharField(max_length=500, verbose_name='原位置路径快照')),
                ('original_status', models.CharField(max_length=32, verbose_name='原资产状态')),
                ('added_during_clearance', models.BooleanField(default=False, verbose_name='清退期间后补发现')),
                ('resolution', models.CharField(choices=[('pending', '待处理'), ('disposal_in_progress', '处置中'), ('returned', '已归还'), ('transferred', '已转交'), ('disposed', '已处置')], default='pending', max_length=24, verbose_name='解决方式')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_items', to='assets.asset', verbose_name='资产')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='offboarding.employeeassetclearance', verbose_name='清退单')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_asset_clearance_items', to='masterdata.company', verbose_name='公司')),
                ('disposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_items', to='assets.assetdisposal', verbose_name='解决处置证据')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_items', to='assets.assetmovement', verbose_name='解决变动证据')),
                ('original_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_item_snapshots', to='masterdata.department', verbose_name='原部门')),
                ('original_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_item_snapshots', to='masterdata.employee', verbose_name='原责任人')),
                ('original_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_item_snapshots', to='masterdata.location', verbose_name='原位置')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_employee_asset_clearance_items', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('source_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_items', to='assets.assetloan', verbose_name='来源内部借用')),
            ],
            options={
                'verbose_name': '员工离职资产清退项目',
                'verbose_name_plural': '员工离职资产清退项目',
                'ordering': ('clearance_id', 'asset_code_snapshot', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearance',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_clearance_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearance',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'blocked'))), fields=('company', 'employee'), name='uq_clearance_employee_active'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('open', 'blocked', 'completed', 'cancelled'))), name='ck_clearance_status'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearance',
            constraint=models.CheckConstraint(condition=models.Q(('unresolved_assets__lte', models.F('total_assets_snapshot'))), name='ck_clearance_counts'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('supplement_reason', ''), ('supplements_clearance__isnull', True)), models.Q(('supplements_clearance__isnull', False), models.Q(('supplement_reason', ''), _negated=True)), _connector='OR'), name='ck_clearance_supplement_fields'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('status__in', ('open', 'blocked', 'cancelled'))), models.Q(('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='ck_clearance_completion_fields'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearance',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='ck_clearance_idem_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.UniqueConstraint(fields=('clearance', 'asset'), name='uq_clearance_item_asset'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ('responsibility', 'internal_loan', 'both'))), name='ck_clearance_item_source'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_loan__isnull', True), ('source_type', 'responsibility')), models.Q(('source_loan__isnull', False), ('source_type__in', ('internal_loan', 'both'))), _connector='OR'), name='ck_clearance_item_source_loan'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('added_during_clearance', False), ('addition_reason', '')), models.Q(('added_during_clearance', True), models.Q(('addition_reason', ''), _negated=True)), _connector='OR'), name='ck_clearance_item_addition'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__in', ('pending', 'disposal_in_progress', 'returned', 'transferred', 'disposed'))), name='ck_clearance_item_resolution'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disposal__isnull', True), ('movement__isnull', True), ('resolution', 'pending'), ('resolved_at__isnull', True), ('resolved_by__isnull', True)), models.Q(('disposal__isnull', False), ('movement__isnull', True), ('resolution', 'disposal_in_progress'), ('resolved_at__isnull', True), ('resolved_by__isnull', True)), models.Q(('disposal__isnull', True), ('movement__isnull', False), ('resolution__in', ('returned', 'transferred')), ('resolved_at__isnull', False)), models.Q(('disposal__isnull', False), ('movement__isnull', True), ('resolution', 'disposed'), ('resolved_at__isnull', False)), _connector='OR'), name='ck_clearance_item_evidence'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_code_snapshot', ''), _negated=True), models.Q(('asset_name_snapshot', ''), _negated=True), models.Q(('original_department_snapshot', ''), _negated=True), models.Q(('original_employee_snapshot', ''), _negated=True), models.Q(('original_location_path_snapshot', ''), _negated=True)), name='ck_clearance_item_snapshots'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetclearanceitem',
            constraint=models.CheckConstraint(condition=models.Q(('original_status__in', ('pending_label', 'in_use', 'idle', 'loaned', 'under_repair', 'pending_disposal'))), name='ck_clearance_item_original_status'),
        ),
    ]
