# Generated by Django 5.2.17 on 2026-08-12 18:15

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_postgresql_asset_guards'),
        ('masterdata', '0006_fixedassetcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDepreciationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('straight_line', '年限平均法'), ('units_of_production', '工作量法'), ('double_declining_balance', '双倍余额递减法'), ('sum_of_years_digits', '年数总和法'), ('manual', '手工折旧'), ('no_depreciation', '不计提折旧')], max_length=32)),
                ('posting_period', models.CharField(choices=[('monthly', '月度'), ('yearly', '年度')], max_length=16)),
                ('start_rule', models.CharField(choices=[('current_month', '当月'), ('next_month', '次月'), ('specified_month', '指定月份'), ('specified_date', '指定日期')], max_length=32)),
                ('stop_rule', models.CharField(choices=[('event_date', '事件日'), ('next_month', '次月')], max_length=16)),
                ('start_date', models.DateField()),
                ('useful_life_months', models.PositiveIntegerField()),
                ('salvage_mode', models.CharField(choices=[('rate', '残值率'), ('amount', '固定残值金额')], max_length=16)),
                ('salvage_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('salvage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('opening_book_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('opening_actual_accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expected_total_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('work_unit', models.CharField(blank=True, max_length=64)),
                ('annual_posting_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效'), ('suspended', '暂停'), ('completed', '已完成'), ('stopped', '已停止')], default='draft', max_length=16)),
                ('change_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_profiles', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_profiles', to='masterdata.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depreciation_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('asset_id', 'version'),
            },
        ),
        migrations.CreateModel(
            name='AssetFinance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accounting_treatment', models.CharField(blank=True, choices=[('fixed_asset', '固定资产'), ('controlled_non_fixed', '受控非固定资产')], max_length=32, null=True)),
                ('accounting_treatment_reason', models.TextField(blank=True)),
                ('recognition_threshold_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('original_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('capitalization_date', models.DateField(blank=True, null=True)),
                ('impairment_balance_cache', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('finance_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('finance_remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_finances', to='masterdata.company')),
                ('finance_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_asset_finances', to=settings.AUTH_USER_MODEL)),
                ('fixed_asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_finances', to='masterdata.fixedassetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssetValueAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('opening_impairment', '期初减值'), ('impairment', '减值'), ('impairment_reversal', '减值转回'), ('cost_correction', '原值更正'), ('depreciation_adjustment', '折旧调整')], max_length=32)),
                ('effective_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('old_values_json', models.JSONField(default=dict)),
                ('new_values_json', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('reversed', '已冲销')], default='draft', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_adjustments', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_value_adjustments', to='masterdata.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_asset_value_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_value_adjustments', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.assetvalueadjustment')),
            ],
            options={
                'ordering': ('asset_id', 'effective_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='AssetWorkUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('work_unit', models.CharField(max_length=64)),
                ('opening_accumulated_units', models.DecimalField(decimal_places=6, max_digits=24)),
                ('current_units', models.DecimalField(decimal_places=6, max_digits=24)),
                ('closing_accumulated_units', models.DecimalField(decimal_places=6, max_digits=24)),
                ('entered_at', models.DateTimeField()),
                ('remark', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_usages', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_work_usages', to='masterdata.company')),
                ('depreciation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_usages', to='finance.assetdepreciationprofile')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_asset_work_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('depreciation_profile_id', 'period_start'),
            },
        ),
        migrations.CreateModel(
            name='DepreciationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generation_no', models.PositiveIntegerField(default=1)),
                ('batch_type', models.CharField(choices=[('regular', '正常计提'), ('reversal', '冲销')], max_length=16)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('reversed', '已冲销'), ('cancelled', '已取消')], default='draft', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_batches', to='masterdata.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_depreciation_batches', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_depreciation_batches', to=settings.AUTH_USER_MODEL)),
                ('reverses_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_batches', to='finance.depreciationbatch')),
                ('supersedes_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_batches', to='finance.depreciationbatch')),
            ],
            options={
                'ordering': ('company_id', 'period_start', 'generation_no', 'batch_type'),
            },
        ),
        migrations.CreateModel(
            name='DepreciationBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_method', models.CharField(choices=[('straight_line', '年限平均法'), ('units_of_production', '工作量法'), ('double_declining_balance', '双倍余额递减法'), ('sum_of_years_digits', '年数总和法'), ('manual', '手工折旧'), ('no_depreciation', '不计提折旧')], max_length=32)),
                ('opening_book_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('depreciable_floor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('eligible_fraction', models.DecimalField(decimal_places=10, max_digits=12)),
                ('usage_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('manual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('manual_reason', models.TextField(blank=True)),
                ('manual_entered_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_unrounded', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('planned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closing_book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('calculation_snapshot_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ready', '可确认'), ('skipped', '跳过'), ('error', '错误')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_batch_items', to='assets.asset')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.depreciationbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_batch_items', to='masterdata.company')),
                ('depreciation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='finance.assetdepreciationprofile')),
                ('manual_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_manual_depreciation_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('batch_id', 'asset_id'),
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_type', models.CharField(choices=[('batch', '批次'), ('opening', '期初'), ('adjustment', '调整')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('accumulated_depreciation_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='assets.asset')),
                ('batch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.depreciationbatchitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='masterdata.company')),
                ('depreciation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.assetdepreciationprofile')),
                ('opening_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_entries', to='finance.assetdepreciationprofile')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_depreciation_entries', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.depreciationentry')),
                ('value_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='finance.assetvalueadjustment')),
            ],
            options={
                'ordering': ('asset_id', 'period_start', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='DepreciationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_key', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('straight_line', '年限平均法'), ('units_of_production', '工作量法'), ('double_declining_balance', '双倍余额递减法'), ('sum_of_years_digits', '年数总和法'), ('manual', '手工折旧'), ('no_depreciation', '不计提折旧')], max_length=32)),
                ('posting_period', models.CharField(choices=[('monthly', '月度'), ('yearly', '年度')], max_length=16)),
                ('start_rule', models.CharField(choices=[('current_month', '当月'), ('next_month', '次月'), ('specified_month', '指定月份'), ('specified_date', '指定日期')], max_length=32)),
                ('stop_rule', models.CharField(choices=[('event_date', '事件日'), ('next_month', '次月')], max_length=16)),
                ('default_useful_life_months', models.PositiveIntegerField()),
                ('default_salvage_mode', models.CharField(choices=[('rate', '残值率'), ('amount', '固定残值金额')], max_length=16)),
                ('default_salvage_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('default_salvage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('annual_posting_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('work_unit', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效'), ('retired', '历史版本')], default='draft', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_policies', to='masterdata.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depreciation_policies', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='finance.depreciationpolicy')),
            ],
            options={
                'ordering': ('company_id', 'policy_key', '-version'),
            },
        ),
        migrations.AddField(
            model_name='assetdepreciationprofile',
            name='depreciation_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_profiles', to='finance.depreciationpolicy'),
        ),
        migrations.CreateModel(
            name='DepreciationProfileEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('suspend', '暂停'), ('resume', '恢复'), ('stop', '停止')], max_length=16)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_events', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_profile_events', to='masterdata.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depreciation_events', to=settings.AUTH_USER_MODEL)),
                ('depreciation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='finance.assetdepreciationprofile')),
            ],
            options={
                'ordering': ('depreciation_profile_id', 'effective_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_book_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('calculated_unrounded', models.DecimalField(decimal_places=12, max_digits=30)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('planned_accumulated', models.DecimalField(decimal_places=2, max_digits=18)),
                ('closing_book_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('planned_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('eligible_fraction', models.DecimalField(decimal_places=10, max_digits=12)),
                ('formula_snapshot_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('planned', '计划'), ('superseded', '已替代')], default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='masterdata.company')),
                ('depreciation_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='finance.assetdepreciationprofile')),
            ],
            options={
                'ordering': ('depreciation_profile_id', 'sequence_no'),
            },
        ),
        migrations.AddField(
            model_name='depreciationbatchitem',
            name='depreciation_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='finance.depreciationschedule'),
        ),
        migrations.CreateModel(
            name='FinanceFormalizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(default='finance_formalization', max_length=32)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('completed', '已完成')], default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formalization_request', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formalization_requests', to='masterdata.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_formalization_requests', to=settings.AUTH_USER_MODEL)),
                ('result_finance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formalization_request', to='finance.assetfinance')),
                ('result_issued_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='formalization_request', to='masterdata.issuedcode')),
            ],
        ),
        migrations.CreateModel(
            name='TheoreticalDepreciationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('parameter_snapshot_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '完成'), ('failed', '失败')], default='draft', max_length=16)),
                ('requested_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theoretical_depreciation_runs', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theoretical_depreciation_runs', to='masterdata.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_theoretical_depreciation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='TheoreticalDepreciationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('theoretical_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('theoretical_accumulated', models.DecimalField(decimal_places=2, max_digits=18)),
                ('theoretical_book_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('formula_snapshot_json', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.theoreticaldepreciationrun')),
            ],
            options={
                'ordering': ('run_id', 'period_start'),
            },
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(('accounting_treatment__isnull', True), ('accounting_treatment__in', ('fixed_asset', 'controlled_non_fixed')), _connector='OR'), name='ck_asset_finance_treatment'),
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(('original_cost__isnull', True), ('original_cost__gte', 0), _connector='OR'), name='ck_asset_finance_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(('recognition_threshold_snapshot__isnull', True), ('recognition_threshold_snapshot__gte', 0), _connector='OR'), name='ck_asset_finance_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(('impairment_balance_cache__gte', 0)), name='ck_asset_finance_impairment_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finance_confirmed_at__isnull', True), ('finance_confirmed_by__isnull', True), ('recognition_threshold_snapshot__isnull', True)), models.Q(('accounting_treatment__isnull', False), ('finance_confirmed_at__isnull', False), ('finance_confirmed_by__isnull', False), ('original_cost__isnull', False), ('recognition_threshold_snapshot__isnull', False)), _connector='OR'), name='ck_asset_finance_confirmation_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accounting_treatment', 'fixed_asset'), ('finance_confirmed_at__isnull', False), _negated=True), models.Q(('capitalization_date__isnull', False), ('fixed_asset_category__isnull', False)), _connector='OR'), name='ck_asset_finance_fixed_confirmed'),
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accounting_treatment', 'controlled_non_fixed'), _negated=True), models.Q(('fixed_asset_category__isnull', True), ('impairment_balance_cache', 0)), _connector='OR'), name='ck_asset_finance_nonfixed_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('adjustment_type', 'opening_impairment')), fields=('asset',), name='uq_asset_opening_impairment'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='ck_asset_adjustment_reason'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adjustment_type__in', ('opening_impairment', 'impairment', 'impairment_reversal')), ('amount__gt', 0)), models.Q(('adjustment_type__in', ('cost_correction', 'depreciation_adjustment')), models.Q(('amount', 0), _negated=True)), _connector='OR'), name='ck_asset_adjustment_amount'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('status', 'draft')), models.Q(('confirmed_at__isnull', False), ('status__in', ('confirmed', 'reversed'))), _connector='OR'), name='ck_asset_adjustment_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('reversal_of_id')), _negated=True), name='ck_asset_adjustment_not_self_reversal'),
        ),
        migrations.AddConstraint(
            model_name='assetworkusage',
            constraint=models.UniqueConstraint(fields=('depreciation_profile', 'period_start', 'period_end'), name='uq_asset_work_usage_profile_period'),
        ),
        migrations.AddConstraint(
            model_name='assetworkusage',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='ck_asset_work_usage_period'),
        ),
        migrations.AddConstraint(
            model_name='assetworkusage',
            constraint=models.CheckConstraint(condition=models.Q(('opening_accumulated_units__gte', 0), ('current_units__gte', 0), ('closing_accumulated_units__gte', 0)), name='ck_asset_work_usage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetworkusage',
            constraint=models.CheckConstraint(condition=models.Q(('closing_accumulated_units', django.db.models.expressions.CombinedExpression(models.F('opening_accumulated_units'), '+', models.F('current_units')))), name='ck_asset_work_usage_balance'),
        ),
        migrations.AddConstraint(
            model_name='assetworkusage',
            constraint=models.CheckConstraint(condition=models.Q(('work_unit', ''), _negated=True), name='ck_asset_work_usage_unit'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.UniqueConstraint(fields=('company', 'period_start', 'generation_no', 'batch_type'), name='uq_depr_batch_period_generation_type'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_depr_batch_company_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_type', 'reversal'), ('status', 'confirmed')), fields=('reverses_batch',), name='uq_depr_batch_confirmed_reversal'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('batch_type', 'regular'), ('status', 'confirmed')), fields=('company', 'period_start', 'period_end'), name='uq_depr_batch_current_regular'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='ck_depr_batch_period'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('generation_no__gte', 1)), name='ck_depr_batch_generation'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idempotency_key', ''), _negated=True), models.Q(('request_hash', ''), _negated=True)), name='ck_depr_batch_request_values'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', False), ('status', 'confirmed')), models.Q(models.Q(('status', 'confirmed'), _negated=True), ('confirmed_at__isnull', True)), _connector='OR'), name='ck_depr_batch_confirmation_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch_type', 'reversal'), ('reverses_batch__isnull', False), models.Q(('reversal_reason', ''), _negated=True), ('supersedes_batch__isnull', True)), models.Q(('batch_type', 'regular'), ('reversal_reason', ''), ('reverses_batch__isnull', True)), _connector='OR'), name='ck_depr_batch_type_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('id', models.F('reverses_batch_id')), _negated=True), models.Q(('id', models.F('supersedes_batch_id')), _negated=True)), name='ck_depr_batch_not_self_reference'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type', 'batch')), fields=('batch_item',), name='uq_depr_entry_batch_item'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type', 'opening')), fields=('opening_profile',), name='uq_depr_entry_opening_profile'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type', 'adjustment')), fields=('value_adjustment',), name='uq_depr_entry_value_adjustment'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='ck_depr_entry_period'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('accumulated_depreciation_after__gte', 0), ('book_value_after__gte', 0)), name='ck_depr_entry_balances'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('reversal_of__isnull', False), ('source_type', 'adjustment'), _connector='OR'), name='ck_depr_entry_amount_sign'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('batch_item__isnull', False), ('opening_profile__isnull', True), ('source_type', 'batch'), ('value_adjustment__isnull', True)), models.Q(('batch_item__isnull', True), ('opening_profile__isnull', False), ('source_type', 'opening'), ('value_adjustment__isnull', True)), models.Q(('batch_item__isnull', True), ('opening_profile__isnull', True), ('source_type', 'adjustment'), ('value_adjustment__isnull', False)), _connector='OR'), name='ck_depr_entry_source_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('reversal_of_id')), _negated=True), name='ck_depr_entry_not_self_reversal'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.UniqueConstraint(fields=('company', 'policy_key', 'version'), name='uq_depr_policy_company_key_version'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('status', 'active')), fields=('company',), name='uq_depr_policy_active_default'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_depr_policy_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('default_useful_life_months__gt', 0)), name='ck_depr_policy_life_positive'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('default_salvage_amount__isnull', True), ('default_salvage_mode', 'rate'), ('default_salvage_rate__gte', 0), ('default_salvage_rate__isnull', False), ('default_salvage_rate__lte', 1)), models.Q(('default_salvage_amount__gte', 0), ('default_salvage_amount__isnull', False), ('default_salvage_mode', 'amount'), ('default_salvage_rate__isnull', True)), _connector='OR'), name='ck_depr_policy_salvage_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annual_posting_month__gte', 1), ('annual_posting_month__lte', 12), ('posting_period', 'yearly')), models.Q(('annual_posting_month__isnull', True), ('posting_period', 'monthly')), _connector='OR'), name='ck_depr_policy_period_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'units_of_production'), _negated=True), models.Q(('work_unit', ''), _negated=True), _connector='OR'), name='ck_depr_policy_work_unit'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='ck_depr_policy_effective_dates'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('effective_from__isnull', False), _connector='OR'), name='ck_depr_policy_active_from'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('status', 'active'), _connector='OR'), name='ck_depr_policy_default_active'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('previous_version_id')), _negated=True), name='ck_depr_policy_not_self_previous'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.UniqueConstraint(fields=('asset', 'version'), name='uq_depr_profile_asset_version'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_depr_profile_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('useful_life_months__gt', 0)), name='ck_depr_profile_life_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('opening_book_value__gte', 0), ('opening_actual_accumulated_depreciation__gte', 0)), name='ck_depr_profile_opening_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('salvage_amount__isnull', True), ('salvage_mode', 'rate'), ('salvage_rate__gte', 0), ('salvage_rate__isnull', False), ('salvage_rate__lte', 1)), models.Q(('salvage_amount__gte', 0), ('salvage_amount__isnull', False), ('salvage_mode', 'amount'), ('salvage_rate__isnull', True)), _connector='OR'), name='ck_depr_profile_salvage_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annual_posting_month__gte', 1), ('annual_posting_month__lte', 12), ('posting_period', 'yearly')), models.Q(('annual_posting_month__isnull', True), ('posting_period', 'monthly')), _connector='OR'), name='ck_depr_profile_period_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expected_total_units__gt', 0), ('expected_total_units__isnull', False), ('method', 'units_of_production'), models.Q(('work_unit', ''), _negated=True)), models.Q(models.Q(('method', 'units_of_production'), _negated=True), ('expected_total_units__isnull', True), ('work_unit', '')), _connector='OR'), name='ck_depr_profile_work_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='ck_depr_profile_effective_dates'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version', 1), models.Q(('change_reason', ''), _negated=True), _connector='OR'), name='ck_depr_profile_change_reason'),
        ),
        migrations.AddConstraint(
            model_name='depreciationprofileevent',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='ck_depr_event_reason'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.UniqueConstraint(fields=('depreciation_profile', 'sequence_no'), name='uq_depr_schedule_profile_sequence'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.UniqueConstraint(fields=('depreciation_profile', 'period_start', 'period_end'), name='uq_depr_schedule_profile_period'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_no__gte', 1)), name='ck_depr_schedule_sequence'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='ck_depr_schedule_period'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('opening_book_value__gte', 0), ('calculated_unrounded__gte', 0), ('planned_amount__gte', 0), ('planned_accumulated__gte', 0), ('closing_book_value__gte', 0)), name='ck_depr_schedule_amounts'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('planned_units__isnull', True), ('planned_units__gte', 0), _connector='OR'), name='ck_depr_schedule_units'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_fraction__gte', 0), ('eligible_fraction__lte', 1)), name='ck_depr_schedule_fraction'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'asset'), name='uq_depr_batch_item_asset'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('opening_book_value__gte', 0), ('depreciable_floor__gte', 0), models.Q(('planned_amount__isnull', True), ('planned_amount__gte', 0), _connector='OR'), models.Q(('closing_book_value__isnull', True), ('closing_book_value__gte', 0), _connector='OR')), name='ck_depr_batch_item_amounts'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_fraction__gte', 0), ('eligible_fraction__lte', 1)), name='ck_depr_batch_item_fraction'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('usage_units__isnull', True), ('usage_units__gte', 0), _connector='OR'), name='ck_depr_batch_item_usage'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_method', 'manual'), ('manual_amount__gte', 0), ('manual_amount__isnull', False), ('manual_entered_at__isnull', False), models.Q(('manual_reason', ''), _negated=True)), models.Q(models.Q(('calculation_method', 'manual'), _negated=True), ('manual_amount__isnull', True), ('manual_entered_at__isnull', True), ('manual_entered_by__isnull', True), ('manual_reason', '')), _connector='OR'), name='ck_depr_batch_item_manual_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'error'), models.Q(('error_message', ''), _negated=True)), models.Q(models.Q(('status', 'error'), _negated=True), ('error_message', '')), _connector='OR'), name='ck_depr_batch_item_error_fields'),
        ),
        migrations.AddConstraint(
            model_name='financeformalizationrequest',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_fin_formalization_company_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='financeformalizationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('operation', 'finance_formalization')), name='ck_fin_formalization_operation'),
        ),
        migrations.AddConstraint(
            model_name='financeformalizationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'completed')), name='ck_fin_formalization_status'),
        ),
        migrations.AddConstraint(
            model_name='financeformalizationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idempotency_key', ''), _negated=True), models.Q(('request_hash', ''), _negated=True)), name='ck_fin_formalization_request_values'),
        ),
        migrations.AddConstraint(
            model_name='theoreticaldepreciationrun',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_theoretical_run_company_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='theoreticaldepreciationrun',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='ck_theoretical_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='theoreticaldepreciationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'draft')), models.Q(('completed_at__isnull', False), ('status__in', ('completed', 'failed'))), _connector='OR'), name='ck_theoretical_run_completion'),
        ),
        migrations.AddConstraint(
            model_name='theoreticaldepreciationline',
            constraint=models.UniqueConstraint(fields=('run', 'period_start', 'period_end'), name='uq_theoretical_line_run_period'),
        ),
        migrations.AddConstraint(
            model_name='theoreticaldepreciationline',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='ck_theoretical_line_period'),
        ),
        migrations.AddConstraint(
            model_name='theoreticaldepreciationline',
            constraint=models.CheckConstraint(condition=models.Q(('theoretical_amount__gte', 0), ('theoretical_accumulated__gte', 0), ('theoretical_book_value__gte', 0)), name='ck_theoretical_line_amounts'),
        ),
    ]
