# Generated by Django 5.2.17 on 2026-08-12 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetqridentity'),
        ('finance', '0001_initial'),
        ('masterdata', '0006_fixedassetcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['straight_line', 'units_of_production', 'double_declining_balance', 'sum_of_years_digits', 'manual', 'no_depreciation'])), name='ck_depr_profile_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('posting_period__in', ['monthly', 'yearly'])), name='ck_depr_profile_posting_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('start_rule__in', ['current_month', 'next_month', 'specified_month', 'specified_date'])), name='ck_depr_profile_start_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('stop_rule__in', ['event_date', 'next_month'])), name='ck_depr_profile_stop_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'active', 'suspended', 'completed', 'stopped'))), name='ck_depr_profile_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('adjustment_type__in', ('opening_impairment', 'impairment', 'impairment_reversal', 'cost_correction', 'depreciation_adjustment'))), name='ck_asset_adjustment_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'confirmed', 'reversed'))), name='ck_asset_adjustment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('batch_type__in', ('regular', 'reversal'))), name='ck_depr_batch_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'confirmed', 'reversed', 'cancelled'))), name='ck_depr_batch_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('calculation_method__in', ['straight_line', 'units_of_production', 'double_declining_balance', 'sum_of_years_digits', 'manual', 'no_depreciation'])), name='ck_depr_batch_item_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ready', 'skipped', 'error'))), name='ck_depr_batch_item_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ('batch', 'opening', 'adjustment'))), name='ck_depr_entry_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['straight_line', 'units_of_production', 'double_declining_balance', 'sum_of_years_digits', 'manual', 'no_depreciation'])), name='ck_depr_policy_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('posting_period__in', ['monthly', 'yearly'])), name='ck_depr_policy_posting_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('start_rule__in', ['current_month', 'next_month', 'specified_month', 'specified_date'])), name='ck_depr_policy_start_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('stop_rule__in', ['event_date', 'next_month'])), name='ck_depr_policy_stop_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'active', 'retired'))), name='ck_depr_policy_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationprofileevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('suspend', 'resume', 'stop'))), name='ck_depr_event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('planned', 'superseded'))), name='ck_depr_schedule_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='theoreticaldepreciationrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'completed', 'failed'))), name='ck_theoretical_run_status_valid'),
        ),
    ]
