# Generated by Django 5.2.17 on 2026-08-12 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetqridentity'),
        ('finance', '0002_assetdepreciationprofile_ck_depr_profile_method_valid_and_more'),
        ('masterdata', '0007_assetcategory_default_depreciation_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetfinance',
            name='ck_asset_finance_confirmation_fields',
        ),
        migrations.RemoveConstraint(
            model_name='depreciationbatch',
            name='ck_depr_batch_confirmation_fields',
        ),
        migrations.AddConstraint(
            model_name='assetfinance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finance_confirmed_at__isnull', True), ('finance_confirmed_by__isnull', True), ('recognition_threshold_snapshot__isnull', True)), models.Q(('accounting_treatment__isnull', False), ('finance_confirmed_at__isnull', False), ('original_cost__isnull', False), ('recognition_threshold_snapshot__isnull', False)), _connector='OR'), name='ck_asset_finance_confirmation_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', False), ('status__in', ('confirmed', 'reversed'))), models.Q(('status__in', ('draft', 'cancelled')), ('confirmed_at__isnull', True)), _connector='OR'), name='ck_depr_batch_confirmation_fields'),
        ),
    ]
