# Generated by Django 5.2.17 on 2026-08-12 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_sprint4_formal_asset_guards'),
        ('finance', '0004_postgresql_finance_guards'),
        ('masterdata', '0008_sprint4_counter_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetvalueadjustment',
            name='ck_asset_adjustment_confirmation',
        ),
        migrations.RemoveConstraint(
            model_name='depreciationbatchitem',
            name='ck_depr_batch_item_manual_fields',
        ),
        migrations.AddConstraint(
            model_name='assetdepreciationprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'suspended'))), fields=('asset',), name='uq_depr_profile_asset_current'),
        ),
        migrations.AddConstraint(
            model_name='assetvalueadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'draft')), models.Q(('confirmed_at__isnull', False), ('status__in', ('confirmed', 'reversed'))), _connector='OR'), name='ck_asset_adjustment_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='depreciationbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_method', 'manual'), ('manual_amount__gte', 0), ('manual_amount__isnull', False), ('manual_entered_at__isnull', False), ('status', 'ready'), models.Q(('manual_reason', ''), _negated=True)), models.Q(('calculation_method', 'manual'), ('status__in', ('error', 'skipped')), ('manual_amount__isnull', True), ('manual_entered_at__isnull', True), ('manual_entered_by__isnull', True), ('manual_reason', '')), models.Q(models.Q(('calculation_method', 'manual'), _negated=True), ('manual_amount__isnull', True), ('manual_entered_at__isnull', True), ('manual_entered_by__isnull', True), ('manual_reason', '')), _connector='OR'), name='ck_depr_batch_item_manual_fields'),
        ),
    ]
