# Generated by Django 5.2.17 on 2026-08-12 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_assetvalueadjustment_ck_asset_adjustment_confirmation_and_more'),
        ('masterdata', '0008_sprint4_counter_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depreciationbatch',
            name='ck_depr_batch_confirmation_fields',
        ),
        migrations.AddConstraint(
            model_name='depreciationbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', False), ('status__in', ('confirmed', 'reversed'))), models.Q(('status__in', ('draft', 'cancelled')), ('confirmed_at__isnull', True), ('confirmed_by__isnull', True)), _connector='OR'), name='ck_depr_batch_confirmation_fields'),
        ),
    ]
