# Generated by Django 5.2.17 on 2026-08-13 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


FINANCE_EVENT_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION finance_validate_profile()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    asset_company bigint; policy_company bigint; policy_status varchar;
    policy_from date; policy_to date; controlled_status boolean; actor_cleared boolean;
    disposal_restore_evidence boolean := false;
BEGIN
    SELECT company_id INTO asset_company FROM assets_asset WHERE id=NEW.asset_id FOR SHARE;
    SELECT company_id,status,effective_from,effective_to
      INTO policy_company,policy_status,policy_from,policy_to
      FROM finance_depreciationpolicy WHERE id=NEW.depreciation_policy_id FOR SHARE;
    IF asset_company IS NULL OR asset_company<>NEW.company_id
       OR policy_company IS NULL OR policy_company<>NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='depreciation profile references must be in one company';
    END IF;
    IF TG_OP='INSERT' AND NEW.status<>'draft'
       AND (policy_status<>'active' OR policy_from>NEW.effective_from
            OR (policy_to IS NOT NULL AND policy_to<NEW.effective_from)) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='confirmed profile requires an effective policy version';
    END IF;
    IF TG_OP='UPDATE' THEN
        actor_cleared := OLD.created_by_id IS NOT NULL AND NEW.created_by_id IS NULL;
        IF NEW.created_by_id IS DISTINCT FROM OLD.created_by_id AND NOT actor_cleared THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='depreciation profile creator is immutable';
        END IF;
        IF OLD.status<>'draft'
           AND (to_jsonb(NEW)-ARRAY['status','effective_to','created_by_id'])
               IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['status','effective_to','created_by_id']) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='confirmed depreciation profile parameters are immutable';
        END IF;
        IF NEW.status IS DISTINCT FROM OLD.status
           AND NOT (OLD.status='draft' AND NEW.status='active') THEN
            controlled_status := COALESCE(current_setting('eam_lite.controlled_finance_profile_status',true),'')='on';
            IF OLD.status='stopped' AND NEW.status IN ('active','suspended') THEN
                SELECT EXISTS (
                    SELECT 1
                      FROM finance_depreciationprofileevent restore_event
                      JOIN finance_depreciationprofileevent stop_event
                        ON stop_event.id=restore_event.reverses_event_id
                     WHERE restore_event.id=(
                               SELECT latest.id
                                 FROM finance_depreciationprofileevent latest
                                WHERE latest.depreciation_profile_id=NEW.id
                                ORDER BY latest.created_at DESC,latest.id DESC
                                LIMIT 1
                           )
                       AND restore_event.depreciation_profile_id=NEW.id
                       AND restore_event.company_id=NEW.company_id
                       AND restore_event.asset_id=NEW.asset_id
                       AND restore_event.event_type='disposal_restore'
                       AND stop_event.event_type='disposal_stop'
                       AND stop_event.depreciation_profile_id=NEW.id
                       AND stop_event.company_id=NEW.company_id
                       AND stop_event.asset_id=NEW.asset_id
                       AND stop_event.source_disposal_id=restore_event.source_disposal_id
                       AND stop_event.effective_date=restore_event.effective_date
                       AND stop_event.previous_profile_status=NEW.status
                ) INTO disposal_restore_evidence;
            END IF;
            IF NOT controlled_status OR NOT (
                (OLD.status='active' AND NEW.status IN ('suspended','stopped','completed'))
                OR (OLD.status='suspended' AND NEW.status IN ('active','stopped','completed'))
                OR (OLD.status='stopped' AND NEW.status IN ('active','suspended')
                    AND disposal_restore_evidence)
            ) THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid or uncontrolled depreciation profile status transition';
            END IF;
            PERFORM set_config('eam_lite.controlled_finance_profile_status','off',true);
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION finance_validate_profile_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    target_asset uuid; current_status varchar; latest_event varchar;
    disposal_restore_evidence boolean := false;
BEGIN
    target_asset := CASE WHEN TG_OP='DELETE' THEN OLD.asset_id ELSE NEW.asset_id END;
    IF EXISTS (
        SELECT 1 FROM finance_assetdepreciationprofile left_profile
        JOIN finance_assetdepreciationprofile right_profile
          ON right_profile.asset_id=left_profile.asset_id AND right_profile.id>left_profile.id
         AND daterange(right_profile.effective_from,COALESCE(right_profile.effective_to,'infinity'::date),'[]')
             && daterange(left_profile.effective_from,COALESCE(left_profile.effective_to,'infinity'::date),'[]')
        WHERE left_profile.asset_id=target_asset AND left_profile.status<>'draft' AND right_profile.status<>'draft'
    ) THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='depreciation profile effective periods cannot overlap'; END IF;
    IF (SELECT count(*) FROM finance_assetdepreciationprofile WHERE asset_id=target_asset AND status IN ('active','suspended'))>1 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset can have only one current depreciation profile';
    END IF;
    IF TG_OP='UPDATE' THEN
        SELECT status INTO current_status FROM finance_assetdepreciationprofile WHERE id=NEW.id;
        SELECT event_type INTO latest_event FROM finance_depreciationprofileevent
         WHERE depreciation_profile_id=NEW.id ORDER BY created_at DESC,id DESC LIMIT 1;
        IF OLD.status='stopped' AND current_status IN ('active','suspended') THEN
            SELECT EXISTS (
                SELECT 1
                  FROM finance_depreciationprofileevent restore_event
                  JOIN finance_depreciationprofileevent stop_event
                    ON stop_event.id=restore_event.reverses_event_id
                 WHERE restore_event.id=(
                           SELECT latest.id
                             FROM finance_depreciationprofileevent latest
                            WHERE latest.depreciation_profile_id=NEW.id
                            ORDER BY latest.created_at DESC,latest.id DESC
                            LIMIT 1
                       )
                   AND restore_event.depreciation_profile_id=NEW.id
                   AND restore_event.company_id=NEW.company_id
                   AND restore_event.asset_id=NEW.asset_id
                   AND restore_event.event_type='disposal_restore'
                   AND stop_event.event_type='disposal_stop'
                   AND stop_event.depreciation_profile_id=NEW.id
                   AND stop_event.company_id=NEW.company_id
                   AND stop_event.asset_id=NEW.asset_id
                   AND stop_event.source_disposal_id=restore_event.source_disposal_id
                   AND stop_event.effective_date=restore_event.effective_date
                   AND stop_event.previous_profile_status=current_status
            ) INTO disposal_restore_evidence;
            IF NOT disposal_restore_evidence THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='stopped profile restoration requires its matching disposal restore event';
            END IF;
        END IF;
        IF current_status='suspended' AND latest_event NOT IN ('suspend','disposal_restore')
           OR current_status='stopped' AND latest_event NOT IN ('stop','disposal_stop')
           OR current_status='active' AND OLD.status IN ('suspended','stopped')
              AND latest_event NOT IN ('resume','disposal_restore') THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='profile status transition requires its append-only event';
        END IF;
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION finance_sprint7_validate_profile_event()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    profile_company bigint; profile_asset uuid; profile_status varchar;
    disposal_company bigint; disposal_asset uuid; disposal_status varchar;
    reversed_type varchar; reversed_company bigint; reversed_asset uuid;
    reversed_profile uuid; reversed_disposal uuid; reversed_date date;
    last_date date;
BEGIN
    SELECT company_id,asset_id,status INTO profile_company,profile_asset,profile_status
      FROM finance_assetdepreciationprofile WHERE id=NEW.depreciation_profile_id FOR SHARE;
    IF profile_company IS NULL OR profile_company<>NEW.company_id OR profile_asset<>NEW.asset_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='depreciation event references are inconsistent';
    END IF;
    IF NEW.event_type IN ('suspend','resume','stop') THEN
        SELECT max(effective_date) INTO last_date FROM finance_depreciationprofileevent
         WHERE depreciation_profile_id=NEW.depreciation_profile_id;
        IF last_date IS NOT NULL AND NEW.effective_date<=last_date THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='depreciation event dates must move forward';
        END IF;
        IF (NEW.event_type='suspend' AND profile_status<>'active')
           OR (NEW.event_type='resume' AND profile_status<>'suspended')
           OR (NEW.event_type='stop' AND profile_status NOT IN ('active','suspended')) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='depreciation event does not match current profile status';
        END IF;
    ELSIF NEW.event_type='disposal_stop' THEN
        SELECT company_id,asset_id,status INTO disposal_company,disposal_asset,disposal_status
          FROM assets_assetdisposal WHERE id=NEW.source_disposal_id FOR SHARE;
        IF disposal_company<>NEW.company_id OR disposal_asset<>NEW.asset_id
           OR disposal_status NOT IN ('finance_locked','confirmed')
           OR profile_status<>NEW.previous_profile_status
           OR NEW.previous_profile_status NOT IN ('active','suspended') THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid disposal stop event';
        END IF;
    ELSIF NEW.event_type='disposal_restore' THEN
        SELECT event_type,company_id,asset_id,depreciation_profile_id,source_disposal_id,effective_date
          INTO reversed_type,reversed_company,reversed_asset,reversed_profile,reversed_disposal,reversed_date
          FROM finance_depreciationprofileevent WHERE id=NEW.reverses_event_id FOR SHARE;
        SELECT company_id,asset_id,status INTO disposal_company,disposal_asset,disposal_status
          FROM assets_assetdisposal WHERE id=NEW.source_disposal_id FOR SHARE;
        IF reversed_type<>'disposal_stop' OR reversed_company<>NEW.company_id
           OR reversed_asset<>NEW.asset_id OR reversed_profile<>NEW.depreciation_profile_id
           OR reversed_disposal<>NEW.source_disposal_id OR reversed_date<>NEW.effective_date
           OR disposal_company<>NEW.company_id OR disposal_asset<>NEW.asset_id
           OR disposal_status NOT IN ('confirmed','reversed') OR profile_status<>'stopped' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid disposal restore event';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION finance_sprint7_validate_profile_event_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    profile_status varchar; prior_status varchar; disposal_status varchar; current_event_type varchar;
    disposal_stop_restored boolean := false;
BEGIN
    SELECT event_type INTO current_event_type FROM finance_depreciationprofileevent WHERE id=NEW.id;
    IF current_event_type IS DISTINCT FROM NEW.event_type THEN
        RETURN NULL;
    END IF;
    SELECT status INTO profile_status FROM finance_assetdepreciationprofile WHERE id=NEW.depreciation_profile_id;
    IF (NEW.event_type='suspend' AND profile_status<>'suspended')
       OR (NEW.event_type='resume' AND profile_status<>'active')
       OR (NEW.event_type='stop' AND profile_status<>'stopped') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='depreciation event and profile status must commit together';
    END IF;
    IF NEW.event_type='disposal_stop' THEN
        SELECT EXISTS (
            SELECT 1 FROM finance_depreciationprofileevent restore_event
             WHERE restore_event.reverses_event_id=NEW.id
               AND restore_event.event_type='disposal_restore'
               AND restore_event.company_id=NEW.company_id
               AND restore_event.asset_id=NEW.asset_id
               AND restore_event.depreciation_profile_id=NEW.depreciation_profile_id
               AND restore_event.source_disposal_id=NEW.source_disposal_id
               AND restore_event.effective_date=NEW.effective_date
        ) INTO disposal_stop_restored;
        SELECT status INTO disposal_status FROM assets_assetdisposal WHERE id=NEW.source_disposal_id;
        IF disposal_stop_restored AND (
               profile_status<>NEW.previous_profile_status OR disposal_status<>'reversed'
           ) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='restored disposal stop must retain its matching restore result';
        ELSIF NOT disposal_stop_restored AND (
                  profile_status<>'stopped' OR disposal_status<>'confirmed'
              ) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='disposal stop and confirmed disposal must commit together';
        END IF;
    END IF;
    IF NEW.event_type='disposal_restore' THEN
        SELECT previous_profile_status INTO prior_status FROM finance_depreciationprofileevent WHERE id=NEW.reverses_event_id;
        SELECT status INTO disposal_status FROM assets_assetdisposal WHERE id=NEW.source_disposal_id;
        IF profile_status<>prior_status OR disposal_status<>'reversed' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='disposal restore must restore saved profile status';
        END IF;
    END IF;
    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_finance_profile_event_validate ON finance_depreciationprofileevent;
CREATE TRIGGER trg_finance_profile_event_validate BEFORE INSERT ON finance_depreciationprofileevent FOR EACH ROW EXECUTE FUNCTION finance_sprint7_validate_profile_event();
DROP TRIGGER IF EXISTS trg_finance_profile_event_commit ON finance_depreciationprofileevent;
CREATE CONSTRAINT TRIGGER trg_finance_profile_event_commit AFTER INSERT ON finance_depreciationprofileevent DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION finance_sprint7_validate_profile_event_commit();
"""

FINANCE_EVENT_GUARDS_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS trg_finance_profile_event_commit ON finance_depreciationprofileevent;
DROP TRIGGER IF EXISTS trg_finance_profile_event_validate ON finance_depreciationprofileevent;
DROP FUNCTION IF EXISTS finance_sprint7_validate_profile_event_commit();
DROP FUNCTION IF EXISTS finance_sprint7_validate_profile_event();
"""


def install_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FINANCE_EVENT_GUARDS_SQL)


def remove_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FINANCE_EVENT_GUARDS_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetdisposal_assetdisposalreversal_assetloan_and_more'),
        ('finance', '0006_remove_depreciationbatch_ck_depr_batch_confirmation_fields_and_more'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depreciationprofileevent',
            name='ck_depr_event_type_valid',
        ),
        migrations.AddField(
            model_name='depreciationprofileevent',
            name='previous_profile_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='depreciationprofileevent',
            name='reverses_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restored_by_event', to='finance.depreciationprofileevent'),
        ),
        migrations.AddField(
            model_name='depreciationprofileevent',
            name='source_disposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_profile_events', to='assets.assetdisposal'),
        ),
        migrations.AlterField(
            model_name='depreciationprofileevent',
            name='event_type',
            field=models.CharField(choices=[('suspend', '暂停'), ('resume', '恢复'), ('stop', '停止'), ('disposal_stop', '处置停止'), ('disposal_restore', '处置恢复')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='depreciationprofileevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('suspend', 'resume', 'stop', 'disposal_stop', 'disposal_restore'))), name='ck_depr_event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationprofileevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ('suspend', 'resume', 'stop')), ('previous_profile_status', ''), ('reverses_event__isnull', True), ('source_disposal__isnull', True)), models.Q(('event_type', 'disposal_stop'), ('previous_profile_status__in', ('active', 'suspended')), ('reverses_event__isnull', True), ('source_disposal__isnull', False)), models.Q(('event_type', 'disposal_restore'), ('previous_profile_status', ''), ('reverses_event__isnull', False), ('source_disposal__isnull', False)), _connector='OR'), name='ck_depr_event_disposal_fields'),
        ),
        migrations.AddConstraint(
            model_name='depreciationprofileevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'disposal_stop')), fields=('source_disposal', 'depreciation_profile'), name='uq_depr_event_disposal_profile_stop'),
        ),
        migrations.RunPython(
            install_postgresql_guards,
            reverse_code=remove_postgresql_guards,
        ),
    ]
