# Generated by Django 5.2.17 on 2026-08-12 02:46

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=100, verbose_name='公司简称')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='业务时区')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'constraints': [models.UniqueConstraint(fields=('normalized_code',), name='uq_company_normalized_code'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uq_company_single_active'), models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_company_code_nonempty'), models.CheckConstraint(condition=models.Q(('currency', 'CNY')), name='ck_company_currency_cny'), models.CheckConstraint(condition=models.Q(('timezone', 'Asia/Shanghai')), name='ck_company_timezone_shanghai')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=512, verbose_name='存储键')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原文件名')),
                ('safe_filename', models.CharField(max_length=255, verbose_name='安全文件名')),
                ('file_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='文件大小')),
                ('mime_type', models.CharField(max_length=127, verbose_name='MIME 类型')),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='必须是 64 位小写十六进制 SHA-256。', regex='\\A[0-9a-f]{64}\\Z')], verbose_name='SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('orphaned_at', models.DateTimeField(blank=True, null=True, verbose_name='进入孤儿候选时间')),
                ('malware_scan_status', models.CharField(choices=[('pending', '待校验'), ('policy_limited', '策略受限校验通过'), ('clean', '恶意软件扫描通过'), ('rejected', '已拒绝')], default='pending', max_length=24, verbose_name='安全扫描状态')),
                ('is_available', models.BooleanField(default=False, verbose_name='可提供')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='masterdata.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='分类名称')),
                ('category_level', models.PositiveIntegerField(default=1, editable=False, verbose_name='分类层级')),
                ('category_type', models.CharField(choices=[('equipment', '设备'), ('mold', '模具'), ('tool', '工具'), ('inspection_tool', '检具'), ('office_equipment', '办公设备'), ('other', '其他')], max_length=32, verbose_name='实物类型')),
                ('is_maintenance_required_default', models.BooleanField(default=False, verbose_name='默认需要保养')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masterdata.assetcategory', verbose_name='上级分类')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='masterdata.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '实物分类',
                'verbose_name_plural': '实物分类',
                'ordering': ('company_id', 'category_level', 'normalized_code'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='部门名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='masterdata.company', verbose_name='公司')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masterdata.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ('company_id', 'normalized_code'),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee_no', models.CharField(max_length=100, verbose_name='员工编号')),
                ('normalized_employee_no', models.CharField(editable=False, max_length=100, verbose_name='规范化员工编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('employment_status', models.CharField(choices=[('active', '在职'), ('leaving', '离职处理中'), ('resigned', '已离职')], default='active', max_length=16, verbose_name='任职状态')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='实际离职日期')),
                ('mobile', models.CharField(blank=True, max_length=32, verbose_name='手机号码')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='masterdata.company', verbose_name='公司')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='masterdata.department', verbose_name='所属部门')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ('company_id', 'normalized_employee_no'),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='masterdata.employee', verbose_name='部门经理'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('department', '部门'), ('employee', '人员')], max_length=32, verbose_name='导入类型')),
                ('template_version', models.CharField(max_length=32, verbose_name='模板版本')),
                ('file_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='必须是 64 位小写十六进制 SHA-256。', regex='\\A[0-9a-f]{64}\\Z')], verbose_name='文件 SHA-256')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('validated', '校验通过'), ('invalid', '校验不通过'), ('confirmed', '已确认'), ('failed', '处理失败')], default='uploaded', max_length=16, verbose_name='批次状态')),
                ('total_rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='有效行数')),
                ('error_rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='错误行数')),
                ('warning_rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='警告行数')),
                ('request_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='必须是 64 位小写十六进制 SHA-256。', regex='\\A[0-9a-f]{64}\\Z')], verbose_name='请求摘要')),
                ('idempotency_key', models.CharField(max_length=255, verbose_name='幂等键')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='校验时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='masterdata.company', verbose_name='公司')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('file_attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='masterdata.attachment', verbose_name='源文件附件')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='行号')),
                ('raw_data_json', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('normalized_data_json', models.JSONField(blank=True, default=dict, verbose_name='规范化数据')),
                ('validation_status', models.CharField(choices=[('pending', '待校验'), ('valid', '有效'), ('invalid', '无效'), ('created', '已创建')], default='pending', max_length=16, verbose_name='校验状态')),
                ('errors_json', models.JSONField(blank=True, default=list, verbose_name='错误')),
                ('warnings_json', models.JSONField(blank=True, default=list, verbose_name='警告')),
                ('created_object_type', models.CharField(blank=True, max_length=100, verbose_name='创建对象类型')),
                ('created_object_id', models.CharField(blank=True, max_length=255, verbose_name='创建对象标识')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='masterdata.importbatch', verbose_name='导入批次')),
            ],
            options={
                'verbose_name': '导入暂存行',
                'verbose_name_plural': '导入暂存行',
                'ordering': ('batch_id', 'row_number'),
            },
        ),
        migrations.CreateModel(
            name='InitializationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialization_completed', models.BooleanField(default=False, verbose_name='初始化完成')),
                ('company_configured', models.BooleanField(default=False, verbose_name='公司已配置')),
                ('departments_configured', models.BooleanField(default=False, verbose_name='部门已配置')),
                ('employees_configured', models.BooleanField(default=False, verbose_name='人员已配置')),
                ('categories_configured', models.BooleanField(default=False, verbose_name='实物分类已配置')),
                ('locations_configured', models.BooleanField(default=False, verbose_name='位置已配置')),
                ('coding_scheme_configured', models.BooleanField(default=False, verbose_name='编码规则已配置')),
                ('finance_rules_configured', models.BooleanField(default=False, verbose_name='财务规则已配置')),
                ('permissions_configured', models.BooleanField(default=False, verbose_name='权限已配置')),
                ('users_configured', models.BooleanField(default=False, verbose_name='用户已配置')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='initialization_setting', to='masterdata.company', verbose_name='公司')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_initializations', to=settings.AUTH_USER_MODEL, verbose_name='完成人')),
            ],
            options={
                'verbose_name': '初始化设置',
                'verbose_name_plural': '初始化设置',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='位置名称')),
                ('level', models.PositiveIntegerField(default=1, editable=False, verbose_name='层级')),
                ('location_type', models.CharField(choices=[('site', '厂区'), ('workshop', '车间'), ('department_area', '部门区域'), ('warehouse', '仓库'), ('office', '办公室'), ('position', '具体位置'), ('other', '其他')], max_length=32, verbose_name='位置类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='masterdata.company', verbose_name='公司')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masterdata.location', verbose_name='上级位置')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
                'ordering': ('company_id', 'level', 'normalized_code'),
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='设置键')),
                ('value', models.TextField(verbose_name='设置值')),
                ('value_type', models.CharField(choices=[('integer', '整数'), ('decimal', '小数'), ('string_list', '字符串列表')], max_length=16, verbose_name='值类型')),
                ('description', models.CharField(max_length=255, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_settings', to='masterdata.company', verbose_name='公司')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='UserDepartmentScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_descendants', models.BooleanField(default=True, verbose_name='包含下级部门')),
                ('is_active', models.BooleanField(default=True, verbose_name='活动授权')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_department_scopes', to=settings.AUTH_USER_MODEL, verbose_name='分配人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_department_scopes', to='masterdata.company', verbose_name='公司')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='masterdata.department', verbose_name='授权根部门')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_department_scopes', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_scopes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户部门范围',
                'verbose_name_plural': '用户部门范围',
                'ordering': ('company_id', 'user_id', 'department_id', '-assigned_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('company', 'storage_key'), name='uq_attachment_company_storage'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gt', 0)), name='ck_attachment_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('malware_scan_status__in', ['pending', 'policy_limited', 'clean', 'rejected'])), name='ck_attachment_scan_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('orphaned_at__isnull', True), ('is_available', False), _connector='OR'), name='ck_attachment_orphan_unavailable'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_asset_category_company_code'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_category_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='ck_category_not_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('category_level__gte', 1)), name='ck_category_level_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('category_type__in', ['equipment', 'mold', 'tool', 'inspection_tool', 'office_equipment', 'other'])), name='ck_category_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_employee_no'), name='uq_employee_company_no'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='uq_employee_user'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_employee_no', ''), _negated=True), name='ck_employee_no_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employment_status', 'active'), models.Q(('employment_status__in', ('leaving', 'resigned')), ('is_active', False)), _connector='OR'), name='ck_employee_status_active_flag'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employment_status', 'resigned'), ('termination_date__isnull', False)), models.Q(('employment_status__in', ('active', 'leaving')), ('termination_date__isnull', True)), _connector='OR'), name='ck_employee_termination_status'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('hire_date__isnull', True), ('termination_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='ck_employee_termination_after_hire'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employment_status__in', ['active', 'leaving', 'resigned'])), name='ck_employee_employment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_department_company_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_department_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='ck_department_not_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_import_batch_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('error_rows__isnull', True), ('total_rows__isnull', True), ('valid_rows__isnull', True), ('warning_rows__isnull', True)), models.Q(('error_rows__isnull', False), ('total_rows', django.db.models.expressions.CombinedExpression(models.F('valid_rows'), '+', models.F('error_rows'))), ('total_rows__isnull', False), ('valid_rows__isnull', False), ('warning_rows__isnull', False), ('warning_rows__lte', models.F('total_rows'))), _connector='OR'), name='ck_import_batch_counts'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'uploaded'), ('validated_at__isnull', True)), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('error_rows', 0), ('status', 'validated'), ('validated_at__isnull', False)), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('error_rows__gt', 0), ('status', 'invalid'), ('validated_at__isnull', False)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('error_rows', 0), ('status', 'confirmed'), ('validated_at__isnull', False)), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'failed')), _connector='OR'), name='ck_import_batch_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('import_type__in', ['department', 'employee'])), name='ck_import_batch_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['uploaded', 'validated', 'invalid', 'confirmed', 'failed'])), name='ck_import_batch_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uq_import_row_batch_number'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gte', 1)), name='ck_import_row_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_object_id__gt', ''), ('created_object_type__gt', ''), ('validation_status', 'created')), models.Q(('created_object_id', ''), ('created_object_type', ''), ('validation_status__in', ('pending', 'valid', 'invalid'))), _connector='OR'), name='ck_import_row_created_mapping'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.CheckConstraint(condition=models.Q(('validation_status__in', ['pending', 'valid', 'invalid', 'created'])), name='ck_import_row_validation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='initializationsetting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categories_configured', True), ('coding_scheme_configured', True), ('company_configured', True), ('completed_at__isnull', False), ('completed_by__isnull', False), ('departments_configured', True), ('employees_configured', True), ('finance_rules_configured', True), ('initialization_completed', True), ('locations_configured', True), ('permissions_configured', True), ('users_configured', True)), models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('initialization_completed', False)), _connector='OR'), name='ck_initialization_completion_state'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_location_company_code'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_location_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='ck_location_not_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='ck_location_level_positive'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('location_type__in', ['site', 'workshop', 'department_area', 'warehouse', 'office', 'position', 'other'])), name='ck_location_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='uq_system_setting_company_key'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('key', 'attachment_allowed_extensions'), ('value_type', 'string_list')), models.Q(('key', 'attachment_max_size_bytes'), ('value_type', 'integer')), models.Q(('key', 'fixed_asset_warning_amount'), ('value_type', 'decimal')), _connector='OR'), name='ck_system_setting_registry_type'),
        ),
        migrations.AddConstraint(
            model_name='systemsetting',
            constraint=models.CheckConstraint(condition=models.Q(('value_type__in', ['integer', 'decimal', 'string_list'])), name='ck_system_setting_value_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='userdepartmentscope',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'user', 'department'), name='uq_user_scope_active_root'),
        ),
        migrations.AddConstraint(
            model_name='userdepartmentscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='ck_user_scope_revocation_state'),
        ),
    ]
