# Generated by Django 5.2.17 on 2026-08-12 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_postgresql_setting_decimal_finite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCodingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='方案名称')),
                ('scheme_key', models.CharField(max_length=100, verbose_name='方案稳定键')),
                ('version', models.PositiveIntegerField(verbose_name='版本')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '有效版本'), ('retired', '历史版本')], default='draft', max_length=16, verbose_name='状态')),
                ('is_default', models.BooleanField(default=False, verbose_name='公司默认方案')),
                ('reset_mode', models.CharField(choices=[('never', '永不重置'), ('yearly', '按年重置'), ('monthly', '按月重置'), ('category_yearly', '按分类和年重置'), ('category_monthly', '按分类和月重置')], max_length=32, verbose_name='重置模式')),
                ('sequence_start', models.BigIntegerField(default=1, verbose_name='流水起始值')),
                ('category_scope_level', models.CharField(blank=True, choices=[('major', '大类'), ('minor', '小类'), ('leaf', '叶级分类')], max_length=16, null=True, verbose_name='分类作用域层级')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效开始日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='生效结束日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_coding_schemes', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_coding_schemes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='masterdata.assetcodingscheme', verbose_name='上一版本')),
            ],
            options={
                'verbose_name': '资产编码方案',
                'verbose_name_plural': '资产编码方案',
                'ordering': ('company_id', 'scheme_key', '-version'),
            },
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='default_coding_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='masterdata.assetcodingscheme', verbose_name='默认编码方案'),
        ),
        migrations.CreateModel(
            name='AssetCodingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(verbose_name='片段顺序')),
                ('segment_type', models.CharField(choices=[('fixed_text', '固定文本'), ('company_code', '公司编码'), ('major_category_code', '大类编码'), ('minor_category_code', '小类编码'), ('category_code', '分类编码'), ('department_code', '部门编码'), ('year', '年'), ('year_month', '年月'), ('full_date', '完整日期'), ('sequence', '顺序号'), ('custom_text', '自定义固定文本'), ('separator', '分隔符')], max_length=32, verbose_name='片段类型')),
                ('fixed_value', models.CharField(blank=True, max_length=64, null=True, verbose_name='固定值')),
                ('format_string', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='格式字符串')),
                ('sequence_length', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='流水位数')),
                ('zero_pad', models.BooleanField(blank=True, null=True, verbose_name='左侧补零')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('coding_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='masterdata.assetcodingscheme', verbose_name='编码方案')),
            ],
            options={
                'verbose_name': '资产编码片段',
                'verbose_name_plural': '资产编码片段',
                'ordering': ('coding_scheme_id', 'sequence_order'),
            },
        ),
        migrations.CreateModel(
            name='IssuedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=512, verbose_name='作用域键')),
                ('sequence_value', models.BigIntegerField(verbose_name='流水值')),
                ('display_code', models.CharField(max_length=64, verbose_name='显示编号')),
                ('normalized_code', models.CharField(max_length=64, verbose_name='规范化编号')),
                ('effective_date', models.DateField(verbose_name='编号生效日期')),
                ('effective_date_reason', models.TextField(blank=True, verbose_name='历史回填原因')),
                ('status', models.CharField(choices=[('active', '当前有效'), ('replaced', '已替换'), ('voided', '已作废')], default='active', max_length=16, verbose_name='状态')),
                ('idempotency_key', models.CharField(max_length=255, verbose_name='幂等键')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签发时间')),
                ('replaced_or_voided_reason', models.TextField(blank=True, verbose_name='替换或作废原因')),
                ('replaced_or_voided_at', models.DateTimeField(blank=True, null=True, verbose_name='替换或作废时间')),
                ('coding_scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_codes', to='masterdata.assetcodingscheme', verbose_name='编码方案')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_codes', to='masterdata.company', verbose_name='公司')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_asset_codes', to=settings.AUTH_USER_MODEL, verbose_name='签发人')),
            ],
            options={
                'verbose_name': '已发资产编号',
                'verbose_name_plural': '已发资产编号',
            },
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scope_key', models.CharField(max_length=512, verbose_name='作用域键')),
                ('current_value', models.BigIntegerField(verbose_name='当前值')),
                ('coding_scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_counters', to='masterdata.assetcodingscheme', verbose_name='编码方案')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_counters', to='masterdata.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '编码流水计数器',
                'verbose_name_plural': '编码流水计数器',
            },
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.UniqueConstraint(fields=('company', 'scheme_key', 'version'), name='uq_coding_scheme_company_key_version'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('status', 'active')), fields=('company',), name='uq_coding_scheme_active_default'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_coding_scheme_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_start__gte', 0)), name='ck_coding_scheme_sequence_start'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'active', 'retired'))), name='ck_coding_scheme_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(('reset_mode__in', ('never', 'yearly', 'monthly', 'category_yearly', 'category_monthly'))), name='ck_coding_scheme_reset_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category_scope_level__in', ('major', 'minor', 'leaf')), ('reset_mode__in', ('category_yearly', 'category_monthly'))), models.Q(('category_scope_level__isnull', True), ('reset_mode__in', ('never', 'yearly', 'monthly'))), _connector='OR'), name='ck_coding_scheme_category_scope'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='ck_coding_scheme_effective_dates'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('effective_from__isnull', False), _connector='OR'), name='ck_coding_scheme_active_from'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('status', 'active'), _connector='OR'), name='ck_coding_scheme_default_active'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingscheme',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('previous_version_id')), _negated=True), name='ck_coding_scheme_not_self_previous'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.UniqueConstraint(fields=('coding_scheme', 'sequence_order'), name='uq_coding_segment_scheme_order'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.UniqueConstraint(condition=models.Q(('segment_type', 'sequence')), fields=('coding_scheme',), name='uq_coding_segment_one_sequence'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_order__gte', 1)), name='ck_coding_segment_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.CheckConstraint(condition=models.Q(('segment_type__in', ('fixed_text', 'company_code', 'major_category_code', 'minor_category_code', 'category_code', 'department_code', 'year', 'year_month', 'full_date', 'sequence', 'custom_text', 'separator'))), name='ck_coding_segment_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.CheckConstraint(condition=models.Q(('format_string__isnull', True)), name='ck_coding_segment_format_null'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_value__isnull', False), ('fixed_value__regex', '^[^\\s\\x00-\\x1F\\x7F-\\x9F{}](?:[^\\x00-\\x1F\\x7F-\\x9F{}]*[^\\s\\x00-\\x1F\\x7F-\\x9F{}])?$'), ('segment_type__in', ('fixed_text', 'custom_text')), ('sequence_length__isnull', True), ('zero_pad__isnull', True)), models.Q(('fixed_value__in', ('-', '_', '.', '/')), ('segment_type', 'separator'), ('sequence_length__isnull', True), ('zero_pad__isnull', True)), models.Q(('fixed_value__isnull', True), ('segment_type', 'sequence'), ('sequence_length__gte', 1), ('sequence_length__isnull', False), ('sequence_length__lte', 12), ('zero_pad__isnull', False)), models.Q(('fixed_value__isnull', True), ('segment_type__in', ('company_code', 'major_category_code', 'minor_category_code', 'category_code', 'department_code', 'year', 'year_month', 'full_date')), ('sequence_length__isnull', True), ('zero_pad__isnull', True)), _connector='OR'), name='ck_coding_segment_field_matrix'),
        ),
        migrations.AddConstraint(
            model_name='issuedcode',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_issued_code_company_normalized'),
        ),
        migrations.AddConstraint(
            model_name='issuedcode',
            constraint=models.UniqueConstraint(fields=('company', 'coding_scheme', 'scope_key', 'sequence_value'), name='uq_issued_code_scope_sequence'),
        ),
        migrations.AddConstraint(
            model_name='issuedcode',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_issued_code_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='issuedcode',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_value__gte', 0)), name='ck_issued_code_sequence_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='issuedcode',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'replaced', 'voided'))), name='ck_issued_code_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='issuedcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('replaced_or_voided_at__isnull', True), ('replaced_or_voided_reason', ''), ('status', 'active')), models.Q(('replaced_or_voided_at__isnull', False), ('replaced_or_voided_reason__gt', ''), ('status__in', ('replaced', 'voided'))), _connector='OR'), name='ck_issued_code_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='issuedcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('display_code', ''), _negated=True), models.Q(('normalized_code', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_issued_code_values_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='sequencecounter',
            constraint=models.UniqueConstraint(fields=('company', 'coding_scheme', 'scope_key'), name='uq_sequence_counter_scope'),
        ),
        migrations.AddConstraint(
            model_name='sequencecounter',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', -1)), name='ck_sequence_counter_minimum'),
        ),
    ]
