# Generated by Django 5.2.17 on 2026-08-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_sprint2_postgresql_coding_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化编码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='固定资产类别名称')),
                ('useful_life_months_default', models.PositiveIntegerField(verbose_name='默认使用年限（月）')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_categories', to='masterdata.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '固定资产会计类别',
                'verbose_name_plural': '固定资产会计类别',
                'ordering': ('company_id', 'normalized_code'),
                'constraints': [models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_fixed_asset_category_company_code'), models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_fixed_asset_category_code_nonempty'), models.CheckConstraint(condition=models.Q(('useful_life_months_default__gt', 0)), name='ck_fixed_asset_category_life_positive')],
            },
        ),
    ]
