# Generated by Django 5.2.17 on 2026-08-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_assetdepreciationprofile_ck_depr_profile_method_valid_and_more'),
        ('masterdata', '0006_fixedassetcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='default_depreciation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_asset_categories', to='finance.depreciationpolicy', verbose_name='默认折旧政策'),
        ),
    ]
