# Generated by Django 5.2.17 on 2026-09-10 06:07

from django.db import migrations, models
from importlib import import_module


def issued_guard_sql(*, allow_retired):
    previous = import_module('apps.masterdata.migrations.0008_sprint4_counter_guards').CREATE_SQL
    start = previous.index('CREATE OR REPLACE FUNCTION masterdata_validate_issued_code()')
    end = previous.index('\n$$;', start) + len('\n$$;')
    result = previous[start:end]
    if allow_retired:
        old = "IF scheme_status <> 'active'\n       OR NEW.effective_date"
        new = "IF (TG_OP='INSERT' AND scheme_status<>'active') OR scheme_status NOT IN ('active','retired')\n       OR NEW.effective_date"
        if result.count(old) != 1:
            raise RuntimeError('Unexpected predecessor issued-code guard')
        result = result.replace(old, new, 1)
    return result


UNIFIED_SQL = r'''
CREATE OR REPLACE FUNCTION masterdata_validate_unified_structure()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_id bigint; config masterdata_assetcodingscheme%ROWTYPE; kinds text[];
BEGIN
    IF TG_TABLE_NAME='masterdata_assetcodingscheme' THEN target_id:=NEW.id;
    ELSIF TG_OP='DELETE' THEN target_id:=OLD.coding_scheme_id;
    ELSE target_id:=NEW.coding_scheme_id; END IF;
    SELECT * INTO config FROM masterdata_assetcodingscheme WHERE id=target_id;
    IF NOT FOUND OR config.status<>'active' THEN RETURN NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM masterdata_assetcodingsegment WHERE coding_scheme_id=target_id
        AND segment_type IN ('management_attribute','coding_year','subitem_number')) THEN RETURN NULL; END IF;
    SELECT array_agg(segment_type::text ORDER BY sequence_order) INTO kinds
      FROM masterdata_assetcodingsegment WHERE coding_scheme_id=target_id;
    IF kinds IS DISTINCT FROM ARRAY['management_attribute','separator','major_category_code','separator',
        'coding_year','separator','sequence','separator','subitem_number']::text[]
       OR config.sequence_start<>1 OR config.reset_mode<>'category_yearly' OR config.category_scope_level<>'major'
       OR EXISTS (SELECT 1 FROM masterdata_assetcodingsegment WHERE coding_scheme_id=target_id
           AND ((segment_type='separator' AND fixed_value IS DISTINCT FROM '-')
             OR (segment_type='sequence' AND (sequence_length<>6 OR zero_pad IS DISTINCT FROM true)))) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid unified identity scheme structure';
    END IF;
    RETURN NULL;
END; $$;
CREATE CONSTRAINT TRIGGER trg_unified_scheme_structure AFTER INSERT OR UPDATE ON masterdata_assetcodingscheme
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION masterdata_validate_unified_structure();
CREATE CONSTRAINT TRIGGER trg_unified_segment_structure AFTER INSERT OR UPDATE OR DELETE ON masterdata_assetcodingsegment
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION masterdata_validate_unified_structure();

CREATE OR REPLACE FUNCTION masterdata_validate_unified_counter()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE scope jsonb; attribute text; category text; year_value integer; canonical text;
BEGIN
    IF NEW.scope_key NOT LIKE '{"standard":"asset_identity_v1",%%' THEN RETURN NEW; END IF;
    BEGIN
        scope:=NEW.scope_key::jsonb; attribute:=scope->>'attribute'; category:=scope->>'category_code';
        year_value:=(scope->>'year')::integer;
    EXCEPTION WHEN OTHERS THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid unified counter scope';
    END;
    canonical:='{"standard":"asset_identity_v1","company_id":"'||NEW.company_id::text||
        '","attribute":"'||attribute||'","category_code":"'||category||'","year":'||year_value::text||'}';
    IF NEW.scope_key IS DISTINCT FROM canonical OR attribute NOT IN ('FA','LV','IA','LS','OT')
       OR category !~ '^(0[1-9]|[1-9][0-9])$' OR year_value<1000
       OR year_value>EXTRACT(YEAR FROM CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai')
       OR NEW.current_value<0 OR NEW.current_value>999999 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid unified counter identity or range';
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER trg_unified_counter BEFORE INSERT OR UPDATE ON masterdata_sequencecounter
FOR EACH ROW EXECUTE FUNCTION masterdata_validate_unified_counter();
'''


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(issued_guard_sql(allow_retired=True), params=None)
        schema_editor.execute(UNIFIED_SQL, params=None)


def remove_guards(apps, schema_editor):
    if apps.get_model('masterdata', 'AssetCodingSegment').objects.filter(
        segment_type__in=('management_attribute', 'coding_year', 'subitem_number')
    ).exists():
        raise RuntimeError('仍有统一编码方案，不能降回无法表示这些片段的旧版本。')
    if apps.get_model('masterdata', 'SequenceCounter').objects.filter(scope_key__startswith='{"standard":"asset_identity_v1",').exists():
        raise RuntimeError('已有统一流水历史，不允许通过降级移除其保护。')
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('''
DROP TRIGGER IF EXISTS trg_unified_scheme_structure ON masterdata_assetcodingscheme;
DROP TRIGGER IF EXISTS trg_unified_segment_structure ON masterdata_assetcodingsegment;
DROP TRIGGER IF EXISTS trg_unified_counter ON masterdata_sequencecounter;
DROP FUNCTION IF EXISTS masterdata_validate_unified_structure();
DROP FUNCTION IF EXISTS masterdata_validate_unified_counter();
''')
        schema_editor.execute(issued_guard_sql(allow_retired=False), params=None)


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_sprint16_opening_custody_import'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetcodingsegment',
            name='ck_coding_segment_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='assetcodingsegment',
            name='ck_coding_segment_field_matrix',
        ),
        migrations.AlterField(
            model_name='assetcodingsegment',
            name='segment_type',
            field=models.CharField(choices=[('fixed_text', '固定文本'), ('company_code', '公司编码'), ('major_category_code', '大类编码'), ('minor_category_code', '小类编码'), ('category_code', '分类编码'), ('department_code', '部门编码'), ('year', '年'), ('year_month', '年月'), ('full_date', '完整日期'), ('sequence', '顺序号'), ('custom_text', '自定义固定文本'), ('separator', '分隔符'), ('management_attribute', '首次建档管理属性'), ('coding_year', '取得年份（编码用）'), ('subitem_number', '主资产或组件子项号')], max_length=32, verbose_name='片段类型'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.CheckConstraint(condition=models.Q(('segment_type__in', ('fixed_text', 'company_code', 'major_category_code', 'minor_category_code', 'category_code', 'department_code', 'year', 'year_month', 'full_date', 'sequence', 'custom_text', 'separator', 'management_attribute', 'coding_year', 'subitem_number'))), name='ck_coding_segment_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetcodingsegment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_value__isnull', False), ('fixed_value__regex', '^[^\\s\\x00-\\x1F\\x7F-\\x9F{}](?:[^\\x00-\\x1F\\x7F-\\x9F{}]*[^\\s\\x00-\\x1F\\x7F-\\x9F{}])?$'), ('segment_type__in', ('fixed_text', 'custom_text')), ('sequence_length__isnull', True), ('zero_pad__isnull', True)), models.Q(('fixed_value__in', ('-', '_', '.', '/')), ('segment_type', 'separator'), ('sequence_length__isnull', True), ('zero_pad__isnull', True)), models.Q(('fixed_value__isnull', True), ('segment_type', 'sequence'), ('sequence_length__gte', 1), ('sequence_length__isnull', False), ('sequence_length__lte', 12), ('zero_pad__isnull', False)), models.Q(('fixed_value__isnull', True), ('segment_type__in', ('company_code', 'major_category_code', 'minor_category_code', 'category_code', 'department_code', 'year', 'year_month', 'full_date', 'management_attribute', 'coding_year', 'subitem_number')), ('sequence_length__isnull', True), ('zero_pad__isnull', True)), _connector='OR'), name='ck_coding_segment_field_matrix'),
        ),
        migrations.AddConstraint(
            model_name='sequencecounter',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_key__startswith', '{"standard":"asset_identity_v1",')), fields=('company', 'scope_key'), name='uq_standard_counter_company_scope'),
        ),
        migrations.RunPython(install_guards, reverse_code=remove_guards),
    ]
