# Generated by Django 5.2.17 on 2026-09-10 07:51

from django.conf import settings
from django.db import migrations, models


def ensure_reverse_compatible(apps, schema_editor):
    if apps.get_model('masterdata', 'InitializationSetting').objects.filter(
        initialization_completed=True, finance_rules_configured=False,
    ).exists():
        raise RuntimeError('已有实物初始化完成且财务待配置的记录，不能降回强制财务先行的旧约束。')


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_unified_asset_identity'),
        ('assets', '0015_physical_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='initializationsetting',
            name='ck_initialization_completion_state',
        ),
        migrations.AddConstraint(
            model_name='initializationsetting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('categories_configured', True), ('coding_scheme_configured', True), ('company_configured', True), ('completed_at__isnull', False), ('completed_by__isnull', False), ('departments_configured', True), ('employees_configured', True), ('initialization_completed', True), ('locations_configured', True), ('permissions_configured', True), ('users_configured', True)), models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('initialization_completed', False)), _connector='OR'), name='ck_initialization_completion_state'),
        ),
        migrations.RunPython(migrations.RunPython.noop, reverse_code=ensure_reverse_compatible),
    ]
