# Generated by Django 5.2.17 on 2026-09-24 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_remove_asset_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='ck_import_batch_status_fields',
        ),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='ck_import_batch_status_valid',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('validated', '校验通过'), ('invalid', '校验不通过'), ('confirmed', '已确认'), ('failed', '处理失败'), ('cancelled', '已取消'), ('reversed', '已撤销')], default='uploaded', max_length=16, verbose_name='批次状态'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'uploaded'), ('validated_at__isnull', True)), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('error_rows', 0), ('status', 'validated'), ('validated_at__isnull', False)), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('error_rows__gt', 0), ('status', 'invalid'), ('validated_at__isnull', False)), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('error_rows', 0), ('status__in', ('confirmed', 'reversed')), ('validated_at__isnull', False)), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'failed')), models.Q(('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'cancelled')), _connector='OR'), name='ck_import_batch_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('uploaded', 'validated', 'invalid', 'confirmed', 'failed', 'cancelled', 'reversed'))), name='ck_import_batch_status_valid'),
        ),
    ]
