# Generated by Django 5.2.17 on 2026-08-13 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


INVENTORY_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION inventory_guard_task()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE ref_company bigint; controlled boolean; actor_only boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory task history cannot be deleted';
    END IF;
    IF NEW.scope_department_id IS NOT NULL THEN
        SELECT company_id INTO ref_company FROM masterdata_department WHERE id=NEW.scope_department_id;
    ELSIF NEW.scope_location_id IS NOT NULL THEN
        SELECT company_id INTO ref_company FROM masterdata_location WHERE id=NEW.scope_location_id;
    ELSIF NEW.scope_category_id IS NOT NULL THEN
        SELECT company_id INTO ref_company FROM masterdata_assetcategory WHERE id=NEW.scope_category_id;
    ELSE ref_company := NEW.company_id;
    END IF;
    IF ref_company IS DISTINCT FROM NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory task scope must be in the same company';
    END IF;
    IF TG_OP='UPDATE' THEN
        controlled := COALESCE(current_setting('eam_lite.controlled_inventory_task_mutation',true),'')='on';
        actor_only := (to_jsonb(NEW)-'created_by_id'-'scanning_stopped_by_id'-'closed_by_id'-'cancelled_by_id')
                      =(to_jsonb(OLD)-'created_by_id'-'scanning_stopped_by_id'-'closed_by_id'-'cancelled_by_id')
                      AND (NEW.created_by_id IS NOT DISTINCT FROM OLD.created_by_id
                           OR (OLD.created_by_id IS NOT NULL AND NEW.created_by_id IS NULL))
                      AND (NEW.scanning_stopped_by_id IS NOT DISTINCT FROM OLD.scanning_stopped_by_id
                           OR (OLD.scanning_stopped_by_id IS NOT NULL AND NEW.scanning_stopped_by_id IS NULL))
                      AND (NEW.closed_by_id IS NOT DISTINCT FROM OLD.closed_by_id
                           OR (OLD.closed_by_id IS NOT NULL AND NEW.closed_by_id IS NULL))
                      AND (NEW.cancelled_by_id IS NOT DISTINCT FROM OLD.cancelled_by_id
                           OR (OLD.cancelled_by_id IS NOT NULL AND NEW.cancelled_by_id IS NULL));
        IF NOT controlled AND NOT actor_only THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory task must be changed by the controlled service';
        END IF;
        IF OLD.status<>'draft' AND ROW(
            NEW.company_id,NEW.task_code,NEW.name,NEW.inventory_type,NEW.scope_type,
            NEW.scope_department_id,NEW.scope_location_id,NEW.scope_category_id,
            NEW.scope_definition_json,NEW.planned_start,NEW.planned_end,NEW.remark,
            NEW.snapshot_at,NEW.expected_asset_count,NEW.idempotency_key
        ) IS DISTINCT FROM ROW(
            OLD.company_id,OLD.task_code,OLD.name,OLD.inventory_type,OLD.scope_type,
            OLD.scope_department_id,OLD.scope_location_id,OLD.scope_category_id,
            OLD.scope_definition_json,OLD.planned_start,OLD.planned_end,OLD.remark,
            OLD.snapshot_at,OLD.expected_asset_count,OLD.idempotency_key
        ) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='published inventory task scope and snapshot metadata are immutable';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION inventory_guard_assignee()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE task_company bigint; task_status varchar;
BEGIN
    IF TG_OP='UPDATE' THEN
        IF (to_jsonb(NEW)-'assigned_by_id')=(to_jsonb(OLD)-'assigned_by_id')
           AND OLD.assigned_by_id IS NOT NULL AND NEW.assigned_by_id IS NULL THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory assignee is immutable';
    END IF;
    IF TG_OP='DELETE' THEN
        SELECT status INTO task_status FROM inventory_inventorytask WHERE id=OLD.inventory_task_id;
        IF task_status<>'draft' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='published inventory assignee cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;
    SELECT company_id,status INTO task_company,task_status
      FROM inventory_inventorytask WHERE id=NEW.inventory_task_id;
    IF task_company IS DISTINCT FROM NEW.company_id OR task_status<>'draft' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory assignee must belong to a draft task in the same company';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION inventory_guard_task_asset()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE task_company bigint; task_status varchar; asset_company bigint;
    d_company bigint; e_company bigint; l_company bigint; controlled boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory snapshot cannot be deleted';
    END IF;
    IF TG_OP='UPDATE' THEN
        controlled := COALESCE(current_setting('eam_lite.controlled_inventory_task_mutation',true),'')='on';
        IF NOT controlled OR (to_jsonb(NEW)-'inventory_status')<>(to_jsonb(OLD)-'inventory_status') THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory snapshot is immutable';
        END IF;
        RETURN NEW;
    END IF;
    IF COALESCE(current_setting('eam_lite.controlled_inventory_task_mutation',true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory snapshot must be created by the controlled publish service';
    END IF;
    SELECT company_id,status INTO task_company,task_status
      FROM inventory_inventorytask WHERE id=NEW.inventory_task_id;
    SELECT company_id INTO asset_company FROM assets_asset WHERE id=NEW.asset_id;
    SELECT company_id INTO d_company FROM masterdata_department WHERE id=NEW.expected_department_id;
    SELECT company_id INTO e_company FROM masterdata_employee WHERE id=NEW.expected_employee_id;
    SELECT company_id INTO l_company FROM masterdata_location WHERE id=NEW.expected_location_id;
    IF task_company IS DISTINCT FROM NEW.company_id OR asset_company IS DISTINCT FROM NEW.company_id
       OR d_company IS DISTINCT FROM NEW.company_id OR e_company IS DISTINCT FROM NEW.company_id
       OR l_company IS DISTINCT FROM NEW.company_id OR task_status<>'in_progress' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid cross-company or non-publish inventory snapshot';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION inventory_guard_scan()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE task_company bigint; task_status varchar; row_company bigint; row_task uuid; row_asset uuid;
    asset_company bigint; actual_company bigint; old_company bigint; old_row uuid;
    actor_only boolean; controlled boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory scan history cannot be deleted';
    END IF;
    IF TG_OP='UPDATE' THEN
        controlled := COALESCE(current_setting('eam_lite.controlled_inventory_scan_mutation',true),'')='on';
        actor_only := (to_jsonb(NEW)-'scanned_by_id')=(to_jsonb(OLD)-'scanned_by_id')
                      AND OLD.scanned_by_id IS NOT NULL AND NEW.scanned_by_id IS NULL;
        IF NOT actor_only AND NOT (
            controlled AND OLD.is_effective AND NOT NEW.is_effective
            AND (to_jsonb(NEW)-'is_effective')=(to_jsonb(OLD)-'is_effective')
        ) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory scans are append-only';
        END IF;
        RETURN NEW;
    END IF;
    IF COALESCE(current_setting('eam_lite.controlled_inventory_scan_mutation',true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory scan must be created by the controlled service';
    END IF;
    SELECT company_id,status INTO task_company,task_status
      FROM inventory_inventorytask WHERE id=NEW.inventory_task_id;
    SELECT company_id,inventory_task_id,asset_id INTO row_company,row_task,row_asset
      FROM inventory_inventorytaskasset WHERE id=NEW.task_asset_id;
    SELECT company_id INTO asset_company FROM assets_asset WHERE id=NEW.asset_id;
    IF NEW.actual_location_id IS NOT NULL THEN
        SELECT company_id INTO actual_company FROM masterdata_location WHERE id=NEW.actual_location_id;
        IF actual_company IS DISTINCT FROM NEW.company_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory actual location must be in the same company';
        END IF;
    END IF;
    IF NEW.actual_employee_id IS NOT NULL THEN
        SELECT company_id INTO actual_company FROM masterdata_employee WHERE id=NEW.actual_employee_id;
        IF actual_company IS DISTINCT FROM NEW.company_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory actual employee must be in the same company';
        END IF;
    END IF;
    IF task_company IS DISTINCT FROM NEW.company_id OR row_company IS DISTINCT FROM NEW.company_id
       OR asset_company IS DISTINCT FROM NEW.company_id OR row_task<>NEW.inventory_task_id
       OR row_asset<>NEW.asset_id OR NEW.scanned_by_id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid inventory scan references';
    END IF;
    IF NEW.scan_mode='normal' AND task_status<>'in_progress'
       OR NEW.scan_mode='supplemental' AND task_status<>'reconciliation' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory scan mode does not match task state';
    END IF;
    IF NEW.supersedes_scan_id IS NOT NULL THEN
        SELECT company_id,task_asset_id INTO old_company,old_row
          FROM inventory_inventoryscan WHERE id=NEW.supersedes_scan_id;
        IF old_company IS DISTINCT FROM NEW.company_id OR old_row<>NEW.task_asset_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory scan can only supersede the same snapshot';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION inventory_guard_resolution()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE row_company bigint; row_asset uuid; movement_company bigint; movement_asset uuid;
    old_company bigint; old_row uuid; actor_only boolean; controlled boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory resolution history cannot be deleted';
    END IF;
    IF TG_OP='UPDATE' THEN
        controlled := COALESCE(current_setting('eam_lite.controlled_inventory_resolution_mutation',true),'')='on';
        actor_only := (to_jsonb(NEW)-'resolved_by_id')=(to_jsonb(OLD)-'resolved_by_id')
                      AND OLD.resolved_by_id IS NOT NULL AND NEW.resolved_by_id IS NULL;
        IF NOT actor_only AND NOT (
            controlled AND OLD.status='active' AND NEW.status='superseded'
            AND (to_jsonb(NEW)-'status')=(to_jsonb(OLD)-'status')
        ) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory resolutions are append-only';
        END IF;
        RETURN NEW;
    END IF;
    IF COALESCE(current_setting('eam_lite.controlled_inventory_resolution_mutation',true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory resolution must be created by the controlled service';
    END IF;
    SELECT company_id,asset_id INTO row_company,row_asset
      FROM inventory_inventorytaskasset WHERE id=NEW.inventory_task_asset_id;
    IF row_company IS DISTINCT FROM NEW.company_id OR NEW.resolved_by_id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid inventory resolution references';
    END IF;
    IF NEW.movement_id IS NOT NULL THEN
        SELECT company_id,asset_id INTO movement_company,movement_asset
          FROM assets_assetmovement WHERE id=NEW.movement_id;
        IF movement_company IS DISTINCT FROM NEW.company_id OR movement_asset<>row_asset THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory resolution movement must be for the same asset and company';
        END IF;
    END IF;
    IF NEW.supersedes_resolution_id IS NOT NULL THEN
        SELECT company_id,inventory_task_asset_id INTO old_company,old_row
          FROM inventory_inventoryresolution WHERE id=NEW.supersedes_resolution_id;
        IF old_company IS DISTINCT FROM NEW.company_id OR old_row<>NEW.inventory_task_asset_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory resolution can only correct the same snapshot';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION inventory_guard_surplus()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE task_company bigint; asset_company bigint; linked_asset_status varchar;
    controlled boolean; actor_only boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory surplus history cannot be deleted';
    END IF;
    SELECT company_id INTO task_company FROM inventory_inventorytask WHERE id=NEW.inventory_task_id;
    IF task_company IS DISTINCT FROM NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory surplus task must be in the same company';
    END IF;
    IF NEW.linked_asset_id IS NOT NULL THEN
        SELECT asset_row.company_id,asset_row.asset_status
          INTO asset_company,linked_asset_status
          FROM assets_asset AS asset_row WHERE asset_row.id=NEW.linked_asset_id;
        IF asset_company IS DISTINCT FROM NEW.company_id OR linked_asset_status<>'draft' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory surplus can only link a draft asset in the same company';
        END IF;
    END IF;
    IF TG_OP='UPDATE' THEN
        controlled := COALESCE(current_setting('eam_lite.controlled_inventory_surplus_mutation',true),'')='on';
        actor_only := (to_jsonb(NEW)-'found_by_id'-'resolved_by_id')=(to_jsonb(OLD)-'found_by_id'-'resolved_by_id')
                      AND (NEW.found_by_id IS NOT DISTINCT FROM OLD.found_by_id
                           OR (OLD.found_by_id IS NOT NULL AND NEW.found_by_id IS NULL))
                      AND (NEW.resolved_by_id IS NOT DISTINCT FROM OLD.resolved_by_id
                           OR (OLD.resolved_by_id IS NOT NULL AND NEW.resolved_by_id IS NULL));
        IF NOT controlled AND NOT actor_only THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory surplus must be changed by the controlled service';
        END IF;
        IF OLD.resolution_status<>'pending' AND NOT actor_only THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='resolved inventory surplus is immutable';
        END IF;
    ELSIF NEW.resolution_status<>'pending' OR NEW.found_by_id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='inventory surplus must be created pending with its finder';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_inventory_task_guard ON inventory_inventorytask;
CREATE TRIGGER trg_inventory_task_guard BEFORE UPDATE OR DELETE ON inventory_inventorytask
FOR EACH ROW EXECUTE FUNCTION inventory_guard_task();
DROP TRIGGER IF EXISTS trg_inventory_assignee_guard ON inventory_inventorytaskassignee;
CREATE TRIGGER trg_inventory_assignee_guard BEFORE INSERT OR UPDATE OR DELETE ON inventory_inventorytaskassignee
FOR EACH ROW EXECUTE FUNCTION inventory_guard_assignee();
DROP TRIGGER IF EXISTS trg_inventory_task_asset_guard ON inventory_inventorytaskasset;
CREATE TRIGGER trg_inventory_task_asset_guard BEFORE INSERT OR UPDATE OR DELETE ON inventory_inventorytaskasset
FOR EACH ROW EXECUTE FUNCTION inventory_guard_task_asset();
DROP TRIGGER IF EXISTS trg_inventory_scan_guard ON inventory_inventoryscan;
CREATE TRIGGER trg_inventory_scan_guard BEFORE INSERT OR UPDATE OR DELETE ON inventory_inventoryscan
FOR EACH ROW EXECUTE FUNCTION inventory_guard_scan();
DROP TRIGGER IF EXISTS trg_inventory_resolution_guard ON inventory_inventoryresolution;
CREATE TRIGGER trg_inventory_resolution_guard BEFORE INSERT OR UPDATE OR DELETE ON inventory_inventoryresolution
FOR EACH ROW EXECUTE FUNCTION inventory_guard_resolution();
DROP TRIGGER IF EXISTS trg_inventory_surplus_guard ON inventory_inventorysurplus;
CREATE TRIGGER trg_inventory_surplus_guard BEFORE INSERT OR UPDATE OR DELETE ON inventory_inventorysurplus
FOR EACH ROW EXECUTE FUNCTION inventory_guard_surplus();
"""


def install_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(INVENTORY_GUARDS_SQL)


INVENTORY_GUARDS_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS trg_inventory_surplus_guard ON inventory_inventorysurplus;
DROP TRIGGER IF EXISTS trg_inventory_resolution_guard ON inventory_inventoryresolution;
DROP TRIGGER IF EXISTS trg_inventory_scan_guard ON inventory_inventoryscan;
DROP TRIGGER IF EXISTS trg_inventory_task_asset_guard ON inventory_inventorytaskasset;
DROP TRIGGER IF EXISTS trg_inventory_assignee_guard ON inventory_inventorytaskassignee;
DROP TRIGGER IF EXISTS trg_inventory_task_guard ON inventory_inventorytask;
DROP FUNCTION IF EXISTS inventory_guard_surplus();
DROP FUNCTION IF EXISTS inventory_guard_resolution();
DROP FUNCTION IF EXISTS inventory_guard_scan();
DROP FUNCTION IF EXISTS inventory_guard_task_asset();
DROP FUNCTION IF EXISTS inventory_guard_assignee();
DROP FUNCTION IF EXISTS inventory_guard_task();
"""


def remove_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(INVENTORY_GUARDS_REVERSE_SQL)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_assetdisposal_assetdisposalreversal_assetloan_and_more'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_code', models.CharField(max_length=64, verbose_name='任务编号')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('inventory_type', models.CharField(choices=[('department', '部门盘点'), ('full', '财务全盘'), ('special', '专项盘点')], max_length=16, verbose_name='盘点类型')),
                ('scope_type', models.CharField(choices=[('company', '全公司'), ('department', '部门'), ('category', '实物分类'), ('location', '位置'), ('selected_assets', '勾选资产')], max_length=32, verbose_name='范围类型')),
                ('scope_definition_json', models.JSONField(blank=True, default=dict, verbose_name='范围定义快照')),
                ('planned_start', models.DateField(verbose_name='计划开始日期')),
                ('planned_end', models.DateField(verbose_name='计划结束日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('snapshot_at', models.DateTimeField(blank=True, null=True, verbose_name='快照基准时间')),
                ('expected_asset_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='应盘数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('reconciliation', '差异处理中'), ('closed', '已关闭'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='创建幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('scanning_stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='停止扫码时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='取消原因')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='取消人')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='关闭人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('scanning_stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='停止扫码人')),
                ('scope_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to='masterdata.assetcategory', verbose_name='范围实物分类')),
                ('scope_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to='masterdata.department', verbose_name='范围部门')),
                ('scope_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to='masterdata.location', verbose_name='范围位置')),
            ],
            options={
                'verbose_name': '盘点任务',
                'verbose_name_plural': '盘点任务',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventorySurplus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temporary_name', models.CharField(max_length=200, verbose_name='临时名称')),
                ('temporary_category_text', models.CharField(blank=True, max_length=200, verbose_name='实物分类描述')),
                ('temporary_location_text', models.CharField(max_length=500, verbose_name='发现位置')),
                ('found_at', models.DateTimeField(verbose_name='发现时间')),
                ('resolution_status', models.CharField(choices=[('pending', '待确认'), ('converted_to_draft', '已转资产草稿'), ('not_company', '非公司资产'), ('duplicate', '重复记录'), ('other', '其他处理')], default='pending', max_length=32, verbose_name='处理状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('remark', models.TextField(blank=True, verbose_name='说明')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_surpluses', to='masterdata.company', verbose_name='公司')),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_inventory_surpluses', to=settings.AUTH_USER_MODEL, verbose_name='发现人')),
                ('linked_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inventory_surpluses', to='assets.asset', verbose_name='转建资产草稿')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_inventory_surpluses', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('inventory_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surpluses', to='inventory.inventorytask', verbose_name='盘点任务')),
            ],
            options={
                'verbose_name': '盘盈记录',
                'verbose_name_plural': '盘盈记录',
                'ordering': ('inventory_task_id', 'found_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryTaskAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_asset_status', models.CharField(max_length=32, verbose_name='应为资产状态')),
                ('expected_code_snapshot', models.CharField(max_length=64, verbose_name='资产编号快照')),
                ('expected_name_snapshot', models.CharField(max_length=200, verbose_name='资产名称快照')),
                ('expected_category_snapshot', models.CharField(max_length=200, verbose_name='实物分类快照')),
                ('expected_department_snapshot', models.CharField(max_length=200, verbose_name='部门快照')),
                ('expected_employee_snapshot', models.CharField(max_length=200, verbose_name='责任人快照')),
                ('expected_location_path_snapshot', models.CharField(max_length=500, verbose_name='完整位置路径快照')),
                ('inventory_status', models.CharField(choices=[('pending', '未盘'), ('normal', '正常'), ('exception', '异常'), ('missing', '盘亏候选'), ('resolved', '已处理')], default='pending', max_length=16, verbose_name='盘点状态')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_snapshots', to='assets.asset', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_task_assets', to='masterdata.company', verbose_name='公司')),
                ('expected_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_expected_department_rows', to='masterdata.department', verbose_name='应在部门')),
                ('expected_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_expected_employee_rows', to='masterdata.employee', verbose_name='应由责任人')),
                ('expected_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_expected_location_rows', to='masterdata.location', verbose_name='应在位置')),
                ('inventory_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assets', to='inventory.inventorytask', verbose_name='盘点任务')),
            ],
            options={
                'verbose_name': '盘点应盘快照',
                'verbose_name_plural': '盘点应盘快照',
                'ordering': ('expected_code_snapshot', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_mode', models.CharField(choices=[('normal', '普通扫描'), ('supplemental', '受控补盘')], max_length=16, verbose_name='扫描模式')),
                ('supplement_reason', models.TextField(blank=True, verbose_name='补盘原因')),
                ('scanned_at', models.DateTimeField(verbose_name='扫描时间')),
                ('actual_status', models.CharField(max_length=32, verbose_name='实际状态')),
                ('result', models.CharField(choices=[('normal', '正常'), ('location_mismatch', '位置异常'), ('responsible_mismatch', '责任人异常'), ('status_mismatch', '状态异常'), ('multiple_mismatch', '多项异常'), ('other_mismatch', '其他异常')], max_length=32, verbose_name='扫描结果')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('is_effective', models.BooleanField(default=True, verbose_name='当前有效结果')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('actual_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_actual_employee_scans', to='masterdata.employee', verbose_name='实际责任人')),
                ('actual_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_actual_location_scans', to='masterdata.location', verbose_name='实际位置')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_scans', to='assets.asset', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_scans', to='masterdata.company', verbose_name='公司')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_scans', to=settings.AUTH_USER_MODEL, verbose_name='扫描人')),
                ('supersedes_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_scans', to='inventory.inventoryscan', verbose_name='替代的扫描')),
                ('inventory_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='inventory.inventorytask', verbose_name='盘点任务')),
                ('task_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='inventory.inventorytaskasset', verbose_name='应盘快照')),
            ],
            options={
                'verbose_name': '盘点扫描',
                'verbose_name_plural': '盘点扫描',
                'ordering': ('task_asset_id', 'scanned_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_type', models.CharField(choices=[('master_updated', '已执行主档变动'), ('master_confirmed', '确认主档无误'), ('loss_confirmed', '确认盘亏'), ('other', '其他结论')], max_length=32, verbose_name='结论类型')),
                ('conclusion', models.TextField(verbose_name='处理结论')),
                ('status', models.CharField(choices=[('active', '当前结论'), ('superseded', '已被更正')], default='active', max_length=16, verbose_name='状态')),
                ('correction_reason', models.TextField(blank=True, verbose_name='更正原因')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('resolved_at', models.DateTimeField(verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_resolutions', to='masterdata.company', verbose_name='公司')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_resolutions', to='assets.assetmovement', verbose_name='主档变动')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_resolutions', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('supersedes_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_resolutions', to='inventory.inventoryresolution', verbose_name='更正的原结论')),
                ('inventory_task_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='inventory.inventorytaskasset', verbose_name='应盘快照')),
            ],
            options={
                'verbose_name': '盘点处理结论',
                'verbose_name_plural': '盘点处理结论',
                'ordering': ('inventory_task_asset_id', 'resolved_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryTaskAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='分配人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_task_assignees', to='masterdata.company', verbose_name='公司')),
                ('inventory_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignees', to='inventory.inventorytask', verbose_name='盘点任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='执行用户')),
            ],
            options={
                'verbose_name': '盘点任务执行人',
                'verbose_name_plural': '盘点任务执行人',
            },
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.UniqueConstraint(fields=('company', 'task_code'), name='uq_inv_task_company_code'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_inv_task_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_code', ''), _negated=True), models.Q(('name', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_inv_task_required_text'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.CheckConstraint(condition=models.Q(('inventory_type__in', ('department', 'full', 'special'))), name='ck_inv_task_type'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ('company', 'department', 'category', 'location', 'selected_assets'))), name='ck_inv_task_scope_type'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_category__isnull', True), ('scope_department__isnull', True), ('scope_location__isnull', True), ('scope_type', 'company')), models.Q(('scope_category__isnull', True), ('scope_department__isnull', False), ('scope_location__isnull', True), ('scope_type', 'department')), models.Q(('scope_category__isnull', False), ('scope_department__isnull', True), ('scope_location__isnull', True), ('scope_type', 'category')), models.Q(('scope_category__isnull', True), ('scope_department__isnull', True), ('scope_location__isnull', False), ('scope_type', 'location')), models.Q(('scope_category__isnull', True), ('scope_department__isnull', True), ('scope_location__isnull', True), ('scope_type', 'selected_assets')), _connector='OR'), name='ck_inv_task_scope_fields'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.CheckConstraint(condition=models.Q(('planned_end__gte', models.F('planned_start'))), name='ck_inv_task_planned_dates'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'in_progress', 'reconciliation', 'closed', 'cancelled'))), name='ck_inv_task_status'),
        ),
        migrations.AddConstraint(
            model_name='inventorytask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('closed_at__isnull', True), ('closed_by__isnull', True), ('expected_asset_count__isnull', True), ('scanning_stopped_at__isnull', True), ('scanning_stopped_by__isnull', True), ('snapshot_at__isnull', True), ('status', 'draft')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('closed_at__isnull', True), ('closed_by__isnull', True), ('expected_asset_count__isnull', False), ('scanning_stopped_at__isnull', True), ('scanning_stopped_by__isnull', True), ('snapshot_at__isnull', False), ('status', 'in_progress')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('closed_at__isnull', True), ('closed_by__isnull', True), ('expected_asset_count__isnull', False), ('scanning_stopped_at__isnull', False), ('snapshot_at__isnull', False), ('status', 'reconciliation')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('closed_at__isnull', False), ('expected_asset_count__isnull', False), ('scanning_stopped_at__isnull', False), ('snapshot_at__isnull', False), ('status', 'closed')), models.Q(('cancelled_at__isnull', False), ('closed_at__isnull', True), ('closed_by__isnull', True), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='ck_inv_task_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='inventorysurplus',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_inv_surplus_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='inventorysurplus',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_status__in', ('pending', 'converted_to_draft', 'not_company', 'duplicate', 'other'))), name='ck_inv_surplus_status'),
        ),
        migrations.AddConstraint(
            model_name='inventorysurplus',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('linked_asset__isnull', True), ('remark', ''), ('resolution_status', 'pending'), ('resolved_at__isnull', True), ('resolved_by__isnull', True)), models.Q(('linked_asset__isnull', False), ('resolution_status', 'converted_to_draft'), ('resolved_at__isnull', False), models.Q(('remark', ''), _negated=True)), models.Q(('linked_asset__isnull', True), ('resolution_status__in', ('not_company', 'duplicate', 'other')), ('resolved_at__isnull', False), models.Q(('remark', ''), _negated=True)), _connector='OR'), name='ck_inv_surplus_resolution_fields'),
        ),
        migrations.AddConstraint(
            model_name='inventorysurplus',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('temporary_name', ''), _negated=True), models.Q(('temporary_location_text', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_inv_surplus_required_text'),
        ),
        migrations.AddConstraint(
            model_name='inventorytaskasset',
            constraint=models.UniqueConstraint(fields=('inventory_task', 'asset'), name='uq_inv_task_asset'),
        ),
        migrations.AddConstraint(
            model_name='inventorytaskasset',
            constraint=models.CheckConstraint(condition=models.Q(('inventory_status__in', ('pending', 'normal', 'exception', 'missing', 'resolved'))), name='ck_inv_task_asset_status'),
        ),
        migrations.AddConstraint(
            model_name='inventorytaskasset',
            constraint=models.CheckConstraint(condition=models.Q(('expected_asset_status__in', ('draft', 'pending_finance', 'pending_label', 'in_use', 'idle', 'loaned', 'under_repair', 'pending_disposal', 'disposed', 'sold', 'other_disposed'))), name='ck_inv_task_asset_expected_status'),
        ),
        migrations.AddConstraint(
            model_name='inventorytaskasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expected_code_snapshot', ''), _negated=True), models.Q(('expected_name_snapshot', ''), _negated=True), models.Q(('expected_category_snapshot', ''), _negated=True), models.Q(('expected_department_snapshot', ''), _negated=True), models.Q(('expected_employee_snapshot', ''), _negated=True), models.Q(('expected_location_path_snapshot', ''), _negated=True)), name='ck_inv_task_asset_snapshots'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_inv_scan_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_effective', True)), fields=('task_asset',), name='uq_inv_scan_effective_task_asset'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(('scan_mode__in', ('normal', 'supplemental'))), name='ck_inv_scan_mode'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scan_mode', 'normal'), ('supplement_reason', '')), models.Q(('scan_mode', 'supplemental'), models.Q(('supplement_reason', ''), _negated=True)), _connector='OR'), name='ck_inv_scan_mode_reason'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ('normal', 'location_mismatch', 'responsible_mismatch', 'status_mismatch', 'multiple_mismatch', 'other_mismatch'))), name='ck_inv_scan_result'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('result', 'other_mismatch'), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='ck_inv_scan_other_note'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(('actual_status__in', ('draft', 'pending_finance', 'pending_label', 'in_use', 'idle', 'loaned', 'under_repair', 'pending_disposal', 'disposed', 'sold', 'other_disposed'))), name='ck_inv_scan_actual_status'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='ck_inv_scan_idem_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes_scan__isnull', True), models.Q(('id', models.F('supersedes_scan')), _negated=True), _connector='OR'), name='ck_inv_scan_not_self_supersede'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_inv_resolution_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('inventory_task_asset',), name='uq_inv_resolution_active_task_asset'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_type__in', ('master_updated', 'master_confirmed', 'loss_confirmed', 'other'))), name='ck_inv_resolution_type'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'superseded'))), name='ck_inv_resolution_status'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement__isnull', False), ('resolution_type', 'master_updated')), models.Q(models.Q(('resolution_type', 'master_updated'), _negated=True), ('movement__isnull', True)), _connector='OR'), name='ck_inv_resolution_movement'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_reason', ''), ('supersedes_resolution__isnull', True)), models.Q(('supersedes_resolution__isnull', False), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='ck_inv_resolution_correction'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conclusion', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_inv_resolution_required_text'),
        ),
        migrations.AddConstraint(
            model_name='inventoryresolution',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes_resolution__isnull', True), models.Q(('id', models.F('supersedes_resolution')), _negated=True), _connector='OR'), name='ck_inv_resolution_not_self'),
        ),
        migrations.AddConstraint(
            model_name='inventorytaskassignee',
            constraint=models.UniqueConstraint(fields=('inventory_task', 'user'), name='uq_inv_assignee_task_user'),
        ),
        migrations.RunPython(
            install_postgresql_guards,
            reverse_code=remove_postgresql_guards,
        ),
    ]
