# Generated by Django 5.2.17 on 2026-08-26 02:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0010_sprint13_supply_item_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='分类编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化分类编码')),
                ('name', models.CharField(max_length=200, verbose_name='分类名称')),
                ('default_item_type', models.CharField(blank=True, choices=[('consumable', '低值易耗品'), ('durable_quantity', '数量型低值耐用品')], max_length=32, null=True, verbose_name='默认管理模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_categories', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='supplies.supplycategory', verbose_name='上级分类')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '低值物品分类',
                'verbose_name_plural': '低值物品分类',
                'ordering': ('company_id', 'normalized_code'),
            },
        ),
        migrations.CreateModel(
            name='SupplyWarehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='仓库编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化仓库编码')),
                ('name', models.CharField(max_length=200, verbose_name='仓库名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_warehouses', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_warehouses', to='masterdata.location', verbose_name='关联位置')),
                ('manager_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_supply_warehouses', to='masterdata.employee', verbose_name='仓库负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '低值物品仓库',
                'verbose_name_plural': '低值物品仓库',
                'ordering': ('company_id', 'normalized_code'),
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100, verbose_name='物品编码')),
                ('normalized_item_code', models.CharField(editable=False, max_length=100, verbose_name='规范化物品编码')),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('item_type', models.CharField(choices=[('consumable', '低值易耗品'), ('durable_quantity', '数量型低值耐用品')], max_length=32, verbose_name='管理模式')),
                ('unit', models.CharField(max_length=32, verbose_name='计量单位')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('minimum_stock_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='最低库存数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='supplies.supplycategory', verbose_name='分类')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_items', to='supplies.supplywarehouse', verbose_name='默认仓库')),
            ],
            options={
                'verbose_name': '低值物品档案',
                'verbose_name_plural': '低值物品档案',
                'ordering': ('company_id', 'normalized_item_code'),
            },
        ),
        migrations.AddConstraint(
            model_name='supplycategory',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_supply_category_company_code'),
        ),
        migrations.AddConstraint(
            model_name='supplycategory',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_supply_category_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='supplycategory',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_supply_category_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='supplycategory',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='ck_supply_category_not_self'),
        ),
        migrations.AddConstraint(
            model_name='supplycategory',
            constraint=models.CheckConstraint(condition=models.Q(('default_item_type__isnull', True), ('default_item_type__in', ['consumable', 'durable_quantity']), _connector='OR'), name='ck_supply_category_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplywarehouse',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_supply_warehouse_company_code'),
        ),
        migrations.AddConstraint(
            model_name='supplywarehouse',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_supply_warehouse_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='supplywarehouse',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_supply_warehouse_name_nonempty'),
        ),
        migrations.AddIndex(
            model_name='supplyitem',
            index=models.Index(fields=['company', 'item_type', 'is_active'], name='supply_item_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_item_code'), name='uq_supply_item_company_code'),
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_item_code', ''), _negated=True), name='ck_supply_item_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='ck_supply_item_name_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit', ''), _negated=True), name='ck_supply_item_unit_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', ['consumable', 'durable_quantity'])), name='ck_supply_item_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplyitem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stock_quantity__gte', 0)), name='ck_supply_item_minimum_nonnegative'),
        ),
    ]
