# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("supplies", "0008_sprint17_counts_and_offboarding")]

    operations = [
        migrations.AddIndex(
            model_name="supplystockledger",
            index=models.Index(
                fields=["company", "-occurred_at", "-id"],
                name="supply_ledger_company_time_idx",
            ),
        )
    ]
