# Generated by Django 5.2.17 on 2026-08-13 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


MAINTENANCE_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION maintenance_validate_plan()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE asset_company bigint; asset_status varchar; asset_required boolean;
    employee_company bigint; employee_status varchar; employee_active boolean;
    employee_department_active boolean;
    disposal_company bigint; disposal_asset uuid; disposal_status varchar;
    controlled boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23503', MESSAGE='maintenance plan cannot be deleted';
    END IF;
    controlled := COALESCE(current_setting(
        CASE WHEN TG_OP='INSERT' THEN 'eam_lite.controlled_maintenance_plan_insert'
             ELSE 'eam_lite.controlled_maintenance_plan_mutation' END,true),'')='on';
    IF NOT controlled THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance plan must be changed by controlled service';
    END IF;
    SELECT a.company_id,a.asset_status,a.is_maintenance_required
      INTO asset_company,asset_status,asset_required
      FROM assets_asset AS a WHERE a.id=NEW.asset_id FOR SHARE;
    IF asset_company IS NULL OR asset_company<>NEW.company_id OR NOT asset_required
       OR (TG_OP='INSERT' AND (asset_status NOT IN ('in_use','idle','loaned','under_repair')
           OR NEW.status<>'active' OR NEW.last_maintenance_date IS NOT NULL
           OR NEW.next_maintenance_date<>NEW.first_due_date)) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance plan requires an eligible same-company asset';
    END IF;
    IF TG_OP='INSERT' OR NEW.responsible_employee_id IS DISTINCT FROM OLD.responsible_employee_id
       OR (TG_OP='UPDATE' AND OLD.status='ended' AND NEW.status IN ('active','suspended')) THEN
        SELECT e.company_id,e.employment_status,e.is_active,d.is_active
          INTO employee_company,employee_status,employee_active,employee_department_active
          FROM masterdata_employee AS e
          JOIN masterdata_department AS d ON d.id=e.department_id
          WHERE e.id=NEW.responsible_employee_id FOR SHARE OF e,d;
        IF employee_company IS NULL OR employee_company<>NEW.company_id
           OR employee_status<>'active' OR NOT employee_active OR NOT employee_department_active THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance responsible employee must be active in same company';
        END IF;
    END IF;
    IF NEW.ended_by_disposal_id IS NOT NULL THEN
        SELECT company_id,asset_id,status INTO disposal_company,disposal_asset,disposal_status
          FROM assets_assetdisposal WHERE id=NEW.ended_by_disposal_id FOR SHARE;
        IF disposal_company IS NULL OR disposal_company<>NEW.company_id OR disposal_asset<>NEW.asset_id
           OR disposal_status NOT IN ('confirmed','reversed') THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance plan disposal source mismatch';
        END IF;
    END IF;
    IF TG_OP='UPDATE' AND ROW(NEW.company_id,NEW.asset_id,NEW.created_at)
       IS DISTINCT FROM ROW(OLD.company_id,OLD.asset_id,OLD.created_at) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance plan identity is immutable';
    END IF;
    PERFORM set_config(CASE WHEN TG_OP='INSERT' THEN 'eam_lite.controlled_maintenance_plan_insert'
        ELSE 'eam_lite.controlled_maintenance_plan_mutation' END,'off',true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION maintenance_validate_record()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE plan_company bigint; plan_asset uuid; plan_status varchar; asset_company bigint;
    employee_company bigint; controlled boolean; actor_cleared boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23503', MESSAGE='maintenance record cannot be deleted';
    END IF;
    IF TG_OP='UPDATE' THEN
        actor_cleared := (OLD.completed_by_id IS NOT NULL AND NEW.completed_by_id IS NULL
                          OR OLD.voided_by_id IS NOT NULL AND NEW.voided_by_id IS NULL)
            AND (to_jsonb(NEW)-ARRAY['completed_by_id','voided_by_id'])
                =(to_jsonb(OLD)-ARRAY['completed_by_id','voided_by_id'])
            AND (NEW.completed_by_id IS NOT DISTINCT FROM OLD.completed_by_id OR NEW.completed_by_id IS NULL)
            AND (NEW.voided_by_id IS NOT DISTINCT FROM OLD.voided_by_id OR NEW.voided_by_id IS NULL);
        IF actor_cleared THEN RETURN NEW; END IF;
    END IF;
    controlled := COALESCE(current_setting(
        CASE WHEN TG_OP='INSERT' THEN 'eam_lite.controlled_maintenance_record_insert'
             ELSE 'eam_lite.controlled_maintenance_record_mutation' END,true),'')='on';
    IF NOT controlled THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance record must be changed by controlled service';
    END IF;
    SELECT company_id,asset_id,status INTO plan_company,plan_asset,plan_status
      FROM maintenance_maintenanceplan WHERE id=NEW.maintenance_plan_id FOR SHARE;
    SELECT company_id INTO asset_company FROM assets_asset WHERE id=NEW.asset_id FOR SHARE;
    IF plan_company IS NULL OR plan_company<>NEW.company_id OR plan_asset<>NEW.asset_id
       OR asset_company<>NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance record plan and asset must be in same company';
    END IF;
    IF TG_OP='INSERT' AND (plan_status<>'active' OR NEW.status<>'confirmed' OR NEW.completed_by_id IS NULL) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='new maintenance record requires active plan, confirmed status and actor';
    END IF;
    IF NEW.completed_by_id IS NOT NULL THEN
        SELECT company_id INTO employee_company FROM masterdata_employee WHERE id=NEW.completed_by_id;
        IF employee_company<>NEW.company_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance completed employee must be in same company';
        END IF;
    END IF;
    IF TG_OP='UPDATE' AND NOT (
        OLD.status='confirmed' AND NEW.status='voided'
        AND ROW(NEW.company_id,NEW.maintenance_plan_id,NEW.asset_id,NEW.scheduled_date,
                NEW.completed_date,NEW.completed_by_id,NEW.content_snapshot,NEW.result,
                NEW.remark,NEW.idempotency_key,NEW.created_at)
            IS NOT DISTINCT FROM
            ROW(OLD.company_id,OLD.maintenance_plan_id,OLD.asset_id,OLD.scheduled_date,
                OLD.completed_date,OLD.completed_by_id,OLD.content_snapshot,OLD.result,
                OLD.remark,OLD.idempotency_key,OLD.created_at)
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance record is append-only except controlled void';
    END IF;
    PERFORM set_config(CASE WHEN TG_OP='INSERT' THEN 'eam_lite.controlled_maintenance_record_insert'
        ELSE 'eam_lite.controlled_maintenance_record_mutation' END,'off',true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION maintenance_validate_problem()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE record_company bigint; record_asset uuid; record_result varchar; record_status varchar; record_completed date;
    asset_company bigint; owner_company bigint; controlled boolean; actor_cleared boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23503', MESSAGE='maintenance problem cannot be deleted';
    END IF;
    IF TG_OP='UPDATE' THEN
        actor_cleared := (OLD.closed_by_id IS NOT NULL AND NEW.closed_by_id IS NULL
                          OR OLD.owner_employee_id IS NOT NULL AND NEW.owner_employee_id IS NULL)
            AND (to_jsonb(NEW)-ARRAY['closed_by_id','owner_employee_id'])
                =(to_jsonb(OLD)-ARRAY['closed_by_id','owner_employee_id'])
            AND (NEW.closed_by_id IS NOT DISTINCT FROM OLD.closed_by_id OR NEW.closed_by_id IS NULL)
            AND (NEW.owner_employee_id IS NOT DISTINCT FROM OLD.owner_employee_id OR NEW.owner_employee_id IS NULL);
        IF actor_cleared THEN RETURN NEW; END IF;
    END IF;
    controlled := COALESCE(current_setting(
        CASE WHEN TG_OP='INSERT' THEN 'eam_lite.controlled_maintenance_problem_insert'
             ELSE 'eam_lite.controlled_maintenance_problem_mutation' END,true),'')='on';
    IF NOT controlled THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance problem must be changed by controlled service';
    END IF;
    SELECT company_id,asset_id,result,status,completed_date
      INTO record_company,record_asset,record_result,record_status,record_completed
      FROM maintenance_maintenancerecord WHERE id=NEW.maintenance_record_id FOR SHARE;
    SELECT company_id INTO asset_company FROM assets_asset WHERE id=NEW.asset_id FOR SHARE;
    IF record_company IS NULL OR record_company<>NEW.company_id OR record_asset<>NEW.asset_id
       OR asset_company<>NEW.company_id OR record_result<>'problem_found'
       OR record_status<>'confirmed' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance problem source mismatch';
    END IF;
    IF NEW.target_date IS NOT NULL AND NEW.target_date<record_completed THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance problem target date is before completion date';
    END IF;
    IF NEW.owner_employee_id IS NOT NULL THEN
        SELECT company_id INTO owner_company FROM masterdata_employee WHERE id=NEW.owner_employee_id;
        IF owner_company<>NEW.company_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance problem owner company mismatch';
        END IF;
    END IF;
    IF TG_OP='INSERT' AND NEW.status<>'open' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance problem must be created open';
    END IF;
    IF TG_OP='UPDATE' AND NOT (
        OLD.status='open' AND NEW.status='closed'
        AND ROW(NEW.company_id,NEW.maintenance_record_id,NEW.asset_id,NEW.description,
                NEW.owner_employee_id,NEW.target_date,NEW.created_at)
            IS NOT DISTINCT FROM
            ROW(OLD.company_id,OLD.maintenance_record_id,OLD.asset_id,OLD.description,
                OLD.owner_employee_id,OLD.target_date,OLD.created_at)
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='maintenance problem is append-only except controlled close';
    END IF;
    PERFORM set_config(CASE WHEN TG_OP='INSERT' THEN 'eam_lite.controlled_maintenance_problem_insert'
        ELSE 'eam_lite.controlled_maintenance_problem_mutation' END,'off',true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION maintenance_validate_record_problem_pair()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE record_id uuid; record_result varchar; problem_count integer;
BEGIN
    IF TG_TABLE_NAME='maintenance_maintenancerecord' THEN
        record_id := NEW.id;
    ELSE
        record_id := NEW.maintenance_record_id;
    END IF;
    SELECT result INTO record_result FROM maintenance_maintenancerecord WHERE id=record_id;
    SELECT count(*) INTO problem_count FROM maintenance_maintenanceproblem
     WHERE maintenance_record_id=record_id;
    IF record_result='problem_found' AND problem_count<>1 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='problem-found record requires exactly one problem';
    ELSIF record_result='normal' AND problem_count<>0 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='normal record cannot have a problem';
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_maintenance_plan_guard BEFORE INSERT OR UPDATE OR DELETE
ON maintenance_maintenanceplan FOR EACH ROW EXECUTE FUNCTION maintenance_validate_plan();
CREATE TRIGGER trg_maintenance_record_guard BEFORE INSERT OR UPDATE OR DELETE
ON maintenance_maintenancerecord FOR EACH ROW EXECUTE FUNCTION maintenance_validate_record();
CREATE TRIGGER trg_maintenance_problem_guard BEFORE INSERT OR UPDATE OR DELETE
ON maintenance_maintenanceproblem FOR EACH ROW EXECUTE FUNCTION maintenance_validate_problem();
CREATE CONSTRAINT TRIGGER trg_maintenance_record_problem_pair_record
AFTER INSERT OR UPDATE ON maintenance_maintenancerecord DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION maintenance_validate_record_problem_pair();
CREATE CONSTRAINT TRIGGER trg_maintenance_record_problem_pair_problem
AFTER INSERT OR UPDATE ON maintenance_maintenanceproblem DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION maintenance_validate_record_problem_pair();
"""


def install_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(MAINTENANCE_GUARDS_SQL)


def uninstall_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            DROP TRIGGER IF EXISTS trg_maintenance_record_problem_pair_problem ON maintenance_maintenanceproblem;
            DROP TRIGGER IF EXISTS trg_maintenance_record_problem_pair_record ON maintenance_maintenancerecord;
            DROP TRIGGER IF EXISTS trg_maintenance_problem_guard ON maintenance_maintenanceproblem;
            DROP TRIGGER IF EXISTS trg_maintenance_record_guard ON maintenance_maintenancerecord;
            DROP TRIGGER IF EXISTS trg_maintenance_plan_guard ON maintenance_maintenanceplan;
            DROP FUNCTION IF EXISTS maintenance_validate_record_problem_pair();
            DROP FUNCTION IF EXISTS maintenance_validate_problem();
            DROP FUNCTION IF EXISTS maintenance_validate_record();
            DROP FUNCTION IF EXISTS maintenance_validate_plan();
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0009_remove_attachmentlink_ck_attachment_link_one_target_and_more'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('cycle_value', models.PositiveIntegerField(verbose_name='周期数值')),
                ('cycle_unit', models.CharField(choices=[('day', '日'), ('week', '周'), ('month', '月'), ('year', '年')], max_length=8, verbose_name='周期单位')),
                ('advance_notice_days', models.PositiveIntegerField(default=0, verbose_name='提前提醒天数')),
                ('standard_content', models.TextField(verbose_name='标准内容')),
                ('first_due_date', models.DateField(verbose_name='首次到期日')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次完成日')),
                ('next_maintenance_date', models.DateField(verbose_name='下次到期日')),
                ('status', models.CharField(choices=[('active', '启用'), ('suspended', '暂停'), ('ended', '已终止')], default='active', max_length=16, verbose_name='状态')),
                ('ended_reason', models.CharField(blank=True, choices=[('manual', '手工终止'), ('asset_disposal', '资产处置'), ('other', '其他')], max_length=24, null=True, verbose_name='终止原因')),
                ('status_before_disposal', models.CharField(blank=True, choices=[('active', '启用'), ('suspended', '暂停')], max_length=16, null=True, verbose_name='处置前状态')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='终止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='masterdata.company')),
                ('ended_by_disposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_maintenance_plans', to='assets.assetdisposal')),
                ('responsible_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_maintenance_plans', to='masterdata.employee')),
            ],
            options={
                'ordering': ('next_maintenance_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(verbose_name='计划日期')),
                ('completed_date', models.DateField(verbose_name='实际完成日期')),
                ('content_snapshot', models.TextField(verbose_name='实际内容')),
                ('result', models.CharField(choices=[('normal', '正常'), ('problem_found', '发现问题')], max_length=16, verbose_name='结果')),
                ('status', models.CharField(choices=[('confirmed', '已确认'), ('voided', '已作废')], default='confirmed', max_length=16, verbose_name='状态')),
                ('void_reason', models.TextField(blank=True, verbose_name='作废原因')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='masterdata.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_records', to='masterdata.employee')),
                ('maintenance_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='maintenance.maintenanceplan')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='问题说明')),
                ('status', models.CharField(choices=[('open', '待跟进'), ('closed', '已关闭')], default='open', max_length=8, verbose_name='状态')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('closure_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_problems', to='assets.asset')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_maintenance_problems', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_problems', to='masterdata.company')),
                ('owner_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_maintenance_problems', to='masterdata.employee')),
                ('maintenance_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='problem', to='maintenance.maintenancerecord')),
            ],
            options={
                'ordering': ('status', 'target_date', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_value__gt', 0)), name='ck_maint_plan_cycle_positive'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('advance_notice_days__gte', 0)), name='ck_maint_plan_notice_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('standard_content', ''), _negated=True)), name='ck_maint_plan_required_text'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_unit__in', ('day', 'week', 'month', 'year'))), name='ck_maint_plan_cycle_unit'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'suspended', 'ended'))), name='ck_maint_plan_status'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('ended_by_disposal__isnull', True), ('ended_reason__isnull', True), ('status__in', ('active', 'suspended')), ('status_before_disposal__isnull', True)), models.Q(('ended_at__isnull', False), ('ended_by_disposal__isnull', True), ('ended_reason__in', ('manual', 'other')), ('status', 'ended'), ('status_before_disposal__isnull', True)), models.Q(('ended_at__isnull', False), ('ended_by_disposal__isnull', False), ('ended_reason', 'asset_disposal'), ('status', 'ended'), ('status_before_disposal__in', ('active', 'suspended'))), _connector='OR'), name='ck_maint_plan_ended_fields'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_maint_record_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('maintenance_plan', 'scheduled_date'), name='uq_maint_record_confirmed_due'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ('normal', 'problem_found'))), name='ck_maint_record_result'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('confirmed', 'voided'))), name='ck_maint_record_status'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_snapshot', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_maint_record_required_text'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('status', 'voided'), ('voided_at__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='ck_maint_record_void_fields'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceproblem',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='ck_maint_problem_description'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceproblem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('open', 'closed'))), name='ck_maint_problem_status'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceproblem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_by__isnull', True), ('closure_note', ''), ('status', 'open')), models.Q(('closed_at__isnull', False), ('status', 'closed'), models.Q(('closure_note', ''), _negated=True)), _connector='OR'), name='ck_maint_problem_closed_fields'),
        ),
        migrations.RunPython(
            install_postgresql_guards,
            reverse_code=uninstall_postgresql_guards,
        ),
    ]
