# Generated by Django 5.2.17 on 2026-08-12 15:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0005_sprint2_postgresql_coding_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='正式资产编号')),
                ('asset_status', models.CharField(choices=[('draft', '草稿'), ('pending_finance', '待财务确认'), ('pending_label', '待贴标'), ('in_use', '在用'), ('idle', '闲置'), ('loaned', '借出'), ('under_repair', '维修中'), ('pending_disposal', '处置处理中'), ('disposed', '已报废'), ('sold', '已出售'), ('other_disposed', '已其他处置')], default='draft', max_length=32, verbose_name='资产状态')),
                ('record_status', models.CharField(choices=[('active', '有效'), ('archived', '已归档')], default='active', max_length=16, verbose_name='记录状态')),
                ('asset_name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='厂家')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='序列号')),
                ('factory_number', models.CharField(blank=True, max_length=200, verbose_name='出厂编号')),
                ('historical_code', models.CharField(blank=True, max_length=200, verbose_name='历史参考编号')),
                ('tracking_mode', models.CharField(choices=[('single_item', '单件追踪')], default='single_item', editable=False, max_length=16, verbose_name='追踪方式')),
                ('quantity', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单位')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='购置日期')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='达到可使用状态日期')),
                ('is_maintenance_required', models.BooleanField(default=False, verbose_name='需要保养')),
                ('initialization_source', models.CharField(default='manual', max_length=32, verbose_name='初始化来源')),
                ('initialization_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='初始化日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='masterdata.assetcategory', verbose_name='实物分类')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('current_issued_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_asset', to='masterdata.issuedcode', verbose_name='当前正式编号登记')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='masterdata.department', verbose_name='当前部门')),
                ('initialized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initialized_assets', to=settings.AUTH_USER_MODEL, verbose_name='初始化人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='masterdata.location', verbose_name='当前位置')),
                ('requested_coding_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_by_assets', to='masterdata.assetcodingscheme', verbose_name='指定编码方案版本')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_assets', to='masterdata.employee', verbose_name='当前责任人')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_assets', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetCodeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('issued', '首次发号'), ('corrected', '编号更正'), ('voided', '编号作废')], max_length=16, verbose_name='事件类型')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('effective_at', models.DateTimeField(verbose_name='业务生效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_history', to='assets.asset', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_code_histories', to='masterdata.company', verbose_name='公司')),
                ('new_issued_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_code_history', to='masterdata.issuedcode', verbose_name='新编号登记')),
                ('old_issued_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_code_history', to='masterdata.issuedcode', verbose_name='原编号登记')),
                ('operated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_asset_code_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '资产编号历史',
                'verbose_name_plural': '资产编号历史',
                'ordering': ('asset_id', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='AssetCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('code', models.CharField(max_length=100, verbose_name='字段编码')),
                ('normalized_code', models.CharField(editable=False, max_length=100, verbose_name='规范化字段编码')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('decimal', '小数'), ('date', '日期'), ('boolean', '布尔'), ('select', '单选')], max_length=16, verbose_name='字段类型')),
                ('required', models.BooleanField(default=False, verbose_name='提交时必填')),
                ('options_json', models.JSONField(blank=True, null=True, verbose_name='选项')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_fields', to='masterdata.assetcategory', verbose_name='适用实物分类')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_custom_fields', to='masterdata.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '资产动态字段',
                'verbose_name_plural': '资产动态字段',
                'ordering': ('company_id', 'display_order', 'normalized_code'),
            },
        ),
        migrations.CreateModel(
            name='AssetCustomValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='文本值')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True, verbose_name='小数值')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='日期值')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='assets.asset', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_custom_values', to='masterdata.company', verbose_name='公司')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='assets.assetcustomfield', verbose_name='动态字段')),
            ],
            options={
                'verbose_name': '资产动态字段值',
                'verbose_name_plural': '资产动态字段值',
            },
        ),
        migrations.CreateModel(
            name='AttachmentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('cover', '封面照片'), ('photo', '资产照片'), ('invoice', '发票'), ('contract', '合同'), ('acceptance', '验收单'), ('certificate', '合格证'), ('manual', '说明书'), ('other', '其他')], max_length=32, verbose_name='附件用途')),
                ('security_class', models.CharField(choices=[('A0', '普通附件'), ('A1', '财务附件')], max_length=2, verbose_name='安全分类')),
                ('status', models.CharField(choices=[('active', '有效'), ('voided', '已作废')], default='active', max_length=16, verbose_name='状态')),
                ('void_reason', models.TextField(blank=True, verbose_name='作废原因')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_links', to='assets.asset', verbose_name='资产')),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business_link', to='masterdata.attachment', verbose_name='附件')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_links', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attachment_links', to=settings.AUTH_USER_MODEL, verbose_name='关联人')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_attachment_links', to=settings.AUTH_USER_MODEL, verbose_name='作废人')),
            ],
            options={
                'verbose_name': '附件业务关联',
                'verbose_name_plural': '附件业务关联',
                'ordering': ('asset_id', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_code__isnull', False)), fields=('company', 'asset_code'), name='uq_asset_company_code'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 1)), name='ck_asset_quantity_one'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('tracking_mode', 'single_item')), name='ck_asset_tracking_single'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('asset_status__in', ('draft', 'pending_finance', 'pending_label', 'in_use', 'idle', 'loaned', 'under_repair', 'pending_disposal', 'disposed', 'sold', 'other_disposed'))), name='ck_asset_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('record_status__in', ('active', 'archived'))), name='ck_asset_record_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_code__isnull', True), ('asset_status__in', ('draft', 'pending_finance')), ('current_issued_code__isnull', True)), models.Q(('asset_code__isnull', False), ('asset_status__in', ('pending_label', 'in_use', 'idle', 'loaned', 'under_repair', 'pending_disposal', 'disposed', 'sold', 'other_disposed')), ('current_issued_code__isnull', False)), _connector='OR'), name='ck_asset_code_status'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('asset_code__isnull', True), models.Q(('asset_code', ''), _negated=True), _connector='OR'), name='ck_asset_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_status', 'draft'), ('submitted_at__isnull', True), ('submitted_by__isnull', True)), models.Q(('asset_status__in', ('pending_finance', 'pending_label', 'in_use', 'idle', 'loaned', 'under_repair', 'pending_disposal', 'disposed', 'sold', 'other_disposed')), ('submitted_at__isnull', False)), _connector='OR'), name='ck_asset_submission_metadata'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('record_status', 'active'), models.Q(('asset_status__in', ('disposed', 'sold', 'other_disposed')), ('record_status', 'archived')), _connector='OR'), name='ck_asset_archive_terminal_only'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset_status__in', ('in_use', 'idle', 'loaned', 'under_repair', 'pending_disposal')), _negated=True), models.Q(('department__isnull', False), ('location__isnull', False), ('responsible_employee__isnull', False)), _connector='OR'), name='ck_asset_operational_responsibility'),
        ),
        migrations.AddConstraint(
            model_name='assetcodehistory',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('issued', 'corrected', 'voided'))), name='ck_asset_code_history_type'),
        ),
        migrations.AddConstraint(
            model_name='assetcodehistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'issued'), ('new_issued_code__isnull', False), ('old_issued_code__isnull', True)), models.Q(('event_type', 'corrected'), ('new_issued_code__isnull', False), ('old_issued_code__isnull', False), ('reason__gt', '')), models.Q(('event_type', 'voided'), ('new_issued_code__isnull', True), ('old_issued_code__isnull', False), ('reason__gt', '')), _connector='OR'), name='ck_asset_code_history_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetcodehistory',
            constraint=models.CheckConstraint(condition=models.Q(('old_issued_code__isnull', True), ('new_issued_code__isnull', True), models.Q(('old_issued_code', models.F('new_issued_code')), _negated=True), _connector='OR'), name='ck_asset_code_history_distinct_codes'),
        ),
        migrations.AddConstraint(
            model_name='assetcustomfield',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_code'), name='uq_asset_custom_field_company_code'),
        ),
        migrations.AddConstraint(
            model_name='assetcustomfield',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_code', ''), _negated=True), name='ck_asset_custom_field_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='assetcustomfield',
            constraint=models.CheckConstraint(condition=models.Q(('field_type__in', ('text', 'decimal', 'date', 'boolean', 'select'))), name='ck_asset_custom_field_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetcustomfield',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('field_type', 'select'), ('options_json__isnull', False)), models.Q(('field_type__in', ('text', 'decimal', 'date', 'boolean')), ('options_json__isnull', True)), _connector='OR'), name='ck_asset_custom_field_options_type'),
        ),
        migrations.AddConstraint(
            model_name='assetcustomfield',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 1)), name='ck_asset_custom_field_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetcustomvalue',
            constraint=models.UniqueConstraint(fields=('asset', 'custom_field'), name='uq_asset_custom_value_asset_field'),
        ),
        migrations.AddConstraint(
            model_name='assetcustomvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_boolean__isnull', True), ('value_date__isnull', True), ('value_decimal__isnull', True), ('value_text__isnull', False)), models.Q(('value_boolean__isnull', True), ('value_date__isnull', True), ('value_decimal__isnull', False), ('value_text__isnull', True)), models.Q(('value_boolean__isnull', True), ('value_date__isnull', False), ('value_decimal__isnull', True), ('value_text__isnull', True)), models.Q(('value_boolean__isnull', False), ('value_date__isnull', True), ('value_decimal__isnull', True), ('value_text__isnull', True)), _connector='OR'), name='ck_asset_custom_value_one_column'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'cover'), ('status', 'active')), fields=('asset',), name='uq_attachment_link_active_cover'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('cover', 'photo', 'invoice', 'contract', 'acceptance', 'certificate', 'manual', 'other'))), name='ck_attachment_link_role'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(('security_class__in', ('A0', 'A1'))), name='ck_attachment_link_security'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ('cover', 'photo', 'certificate', 'manual')), ('security_class', 'A0')), models.Q(('role__in', ('invoice', 'contract', 'acceptance')), ('security_class', 'A1')), models.Q(('role', 'other'), ('security_class__in', ('A0', 'A1'))), _connector='OR'), name='ck_attachment_link_role_security'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('status', 'voided'), ('void_reason__gt', ''), ('voided_at__isnull', False)), _connector='OR'), name='ck_attachment_link_status_fields'),
        ),
    ]
