# Generated by Django 5.2.17 on 2026-08-12 18:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_postgresql_asset_guards'),
        ('masterdata', '0006_fixedassetcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetQrIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(22)], verbose_name='公开随机标识')),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已撤销')], default='active', max_length=16, verbose_name='状态')),
                ('label_status', models.CharField(choices=[('not_generated', '未生成'), ('ready_to_print', '待打印'), ('printed', '已打印'), ('attached', '已贴标')], default='ready_to_print', max_length=16, verbose_name='标签状态')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='签发时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.TextField(blank=True, verbose_name='撤销原因')),
                ('attached_at', models.DateTimeField(blank=True, null=True, verbose_name='贴标时间')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_identities', to='assets.asset', verbose_name='资产')),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_asset_qr_identities', to=settings.AUTH_USER_MODEL, verbose_name='贴标确认人')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_qr_identities', to='masterdata.company', verbose_name='公司')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_asset_qr_identities', to=settings.AUTH_USER_MODEL, verbose_name='签发人')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_asset_qr_identities', to=settings.AUTH_USER_MODEL, verbose_name='撤销人')),
            ],
            options={
                'verbose_name': '资产二维码身份',
                'verbose_name_plural': '资产二维码身份',
                'ordering': ('asset_id', 'version'),
                'constraints': [models.UniqueConstraint(fields=('asset', 'version'), name='uq_asset_qr_identity_version'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('asset',), name='uq_asset_qr_identity_active'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='ck_asset_qr_version_positive'), models.CheckConstraint(condition=models.Q(('public_token__regex', '^.{22,128}$')), name='ck_asset_qr_token_length'), models.CheckConstraint(condition=models.Q(('status__in', ('active', 'revoked'))), name='ck_asset_qr_status_valid'), models.CheckConstraint(condition=models.Q(('label_status__in', ('not_generated', 'ready_to_print', 'printed', 'attached'))), name='ck_asset_qr_label_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('revoke_reason', ''), ('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('status', 'revoked'), models.Q(('revoke_reason', ''), _negated=True)), _connector='OR'), name='ck_asset_qr_status_fields'), models.CheckConstraint(condition=models.Q(models.Q(('attached_at__isnull', True), ('attached_by__isnull', True), ('label_status__in', ('not_generated', 'ready_to_print', 'printed'))), models.Q(('attached_at__isnull', False), ('label_status', 'attached')), _connector='OR'), name='ck_asset_qr_label_fields')],
            },
        ),
    ]
