# Generated by Django 5.2.17 on 2026-08-12 23:08

import django.db.models.deletion
import uuid
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


CREATE_SQL = r"""
CREATE OR REPLACE FUNCTION assets_validate_asset_references()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    category_company bigint;
    category_active boolean;
    department_company bigint;
    department_active boolean;
    employee_company bigint;
    employee_department bigint;
    employee_status varchar;
    employee_active boolean;
    employee_department_active boolean;
    location_company bigint;
    location_active boolean;
    scheme_company bigint;
    scheme_status varchar;
    scheme_from date;
    scheme_to date;
    shanghai_today date;
    controlled_mutation boolean;
    actor_cleared boolean;
BEGIN
    IF TG_OP = 'INSERT' AND NEW.asset_status <> 'draft' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'assets must be created as drafts';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        controlled_mutation := COALESCE(
            current_setting('eam_lite.controlled_asset_mutation', true), ''
        ) = 'on';
        actor_cleared := OLD.submitted_by_id IS NOT NULL
            AND NEW.submitted_by_id IS NULL
            AND ROW(
                NEW.asset_status, NEW.record_status, NEW.asset_code,
                NEW.current_issued_code_id, NEW.requested_coding_scheme_id,
                NEW.submitted_at
            ) IS NOT DISTINCT FROM ROW(
                OLD.asset_status, OLD.record_status, OLD.asset_code,
                OLD.current_issued_code_id, OLD.requested_coding_scheme_id,
                OLD.submitted_at
            );
        IF ROW(
            NEW.asset_status, NEW.record_status, NEW.asset_code,
            NEW.current_issued_code_id, NEW.requested_coding_scheme_id,
            NEW.submitted_by_id, NEW.submitted_at
        ) IS DISTINCT FROM ROW(
            OLD.asset_status, OLD.record_status, OLD.asset_code,
            OLD.current_issued_code_id, OLD.requested_coding_scheme_id,
            OLD.submitted_by_id, OLD.submitted_at
        ) AND NOT controlled_mutation AND NOT actor_cleared THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'asset protected state must be changed by the controlled service';
        END IF;
        IF controlled_mutation AND ROW(
            NEW.asset_status, NEW.record_status, NEW.asset_code,
            NEW.current_issued_code_id, NEW.requested_coding_scheme_id,
            NEW.submitted_by_id, NEW.submitted_at
        ) IS DISTINCT FROM ROW(
            OLD.asset_status, OLD.record_status, OLD.asset_code,
            OLD.current_issued_code_id, OLD.requested_coding_scheme_id,
            OLD.submitted_by_id, OLD.submitted_at
        ) THEN
            PERFORM set_config('eam_lite.controlled_asset_mutation', 'off', true);
        END IF;
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.asset_status IS DISTINCT FROM OLD.asset_status
       AND NOT (
           (OLD.asset_status = 'draft' AND NEW.asset_status = 'pending_finance')
           OR (OLD.asset_status = 'pending_finance' AND NEW.asset_status = 'draft')
           OR (OLD.asset_status = 'pending_finance' AND NEW.asset_status = 'pending_label')
           OR (OLD.asset_status = 'pending_label' AND NEW.asset_status IN ('in_use', 'idle'))
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'asset status transition is not enabled in Sprint 6';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.asset_status IN ('pending_label', 'in_use', 'idle')
       AND ROW(NEW.asset_code, NEW.current_issued_code_id, NEW.requested_coding_scheme_id)
           IS DISTINCT FROM
           ROW(OLD.asset_code, OLD.current_issued_code_id, OLD.requested_coding_scheme_id) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset code and requested coding scheme are immutable in Sprint 6';
    END IF;

    SELECT company_id, is_active INTO category_company, category_active
      FROM masterdata_assetcategory WHERE id = NEW.category_id
      FOR SHARE;
    IF category_company IS NULL OR category_company <> NEW.company_id OR NOT category_active THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'asset category must be active and in the same company';
    END IF;

    IF NEW.department_id IS NOT NULL THEN
        SELECT company_id, is_active INTO department_company, department_active
          FROM masterdata_department WHERE id = NEW.department_id
          FOR SHARE;
        IF department_company IS NULL OR department_company <> NEW.company_id OR NOT department_active THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'asset department must be active and in the same company';
        END IF;
    END IF;

    IF NEW.responsible_employee_id IS NOT NULL THEN
        SELECT employee.company_id, employee.department_id,
               employee.employment_status, employee.is_active,
               department.is_active
          INTO employee_company, employee_department, employee_status,
               employee_active, employee_department_active
          FROM masterdata_employee employee
          JOIN masterdata_department department ON department.id = employee.department_id
         WHERE employee.id = NEW.responsible_employee_id
         FOR SHARE OF employee, department;
        IF employee_company IS NULL OR employee_company <> NEW.company_id
           OR NEW.department_id IS NULL OR employee_department <> NEW.department_id
           OR employee_status <> 'active' OR NOT employee_active
           OR NOT employee_department_active THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'asset responsible employee must be active in the asset department and company';
        END IF;
    END IF;

    IF NEW.location_id IS NOT NULL THEN
        SELECT company_id, is_active INTO location_company, location_active
          FROM masterdata_location WHERE id = NEW.location_id
          FOR SHARE;
        IF location_company IS NULL OR location_company <> NEW.company_id OR NOT location_active THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'asset location must be active and in the same company';
        END IF;
    END IF;

    IF NEW.requested_coding_scheme_id IS NOT NULL THEN
        SELECT company_id, status, effective_from, effective_to
          INTO scheme_company, scheme_status, scheme_from, scheme_to
          FROM masterdata_assetcodingscheme
         WHERE id = NEW.requested_coding_scheme_id;
        shanghai_today := (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai')::date;
        IF scheme_company IS NULL OR scheme_company <> NEW.company_id
           OR scheme_status <> 'active' OR scheme_from > shanghai_today
           OR (scheme_to IS NOT NULL AND scheme_to < shanghai_today) THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'requested coding scheme must be current and in the same company';
        END IF;
    END IF;

    IF TG_OP = 'UPDATE' AND NEW.category_id IS DISTINCT FROM OLD.category_id
       AND EXISTS (
           SELECT 1
             FROM assets_assetcustomvalue value
             JOIN assets_assetcustomfield field ON field.id = value.custom_field_id
            WHERE value.asset_id = NEW.id AND field.category_id <> NEW.category_id
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'remove or migrate incompatible custom values before changing category';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_formal_asset_commit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_asset_id uuid;
    target_asset assets_asset%%ROWTYPE;
    issued_company bigint;
    issued_display varchar;
    issued_status varchar;
    finance_id uuid;
    finance_company bigint;
    finance_treatment varchar;
    finance_cost numeric;
    finance_confirmed timestamptz;
    qr_count integer;
    movement_count integer;
    formalization_count integer;
BEGIN
    IF TG_TABLE_NAME = 'assets_asset' THEN
        target_asset_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    ELSIF TG_TABLE_NAME IN (
        'finance_assetfinance', 'assets_assetqridentity',
        'finance_assetdepreciationprofile', 'finance_financeformalizationrequest',
        'assets_assetmovement'
    ) THEN
        target_asset_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.asset_id ELSE NEW.asset_id END;
    ELSIF TG_TABLE_NAME IN (
        'finance_depreciationentry', 'finance_assetvalueadjustment'
    ) THEN
        target_asset_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.asset_id ELSE NEW.asset_id END;
    ELSIF TG_TABLE_NAME = 'masterdata_issuedcode' THEN
        SELECT asset.id INTO target_asset_id
          FROM assets_asset asset
         WHERE asset.current_issued_code_id = CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    ELSE
        RETURN NULL;
    END IF;
    SELECT * INTO target_asset FROM assets_asset WHERE id = target_asset_id;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    IF target_asset.asset_status IN ('draft', 'pending_finance') THEN
        IF EXISTS (
            SELECT 1 FROM assets_assetqridentity
             WHERE asset_id = target_asset.id
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'draft or pending finance asset cannot retain a QR identity outside formalization';
        END IF;
        RETURN NULL;
    END IF;
    IF target_asset.asset_status NOT IN ('pending_label', 'in_use', 'idle') THEN
        RETURN NULL;
    END IF;

    SELECT company_id, display_code, status
      INTO issued_company, issued_display, issued_status
      FROM masterdata_issuedcode WHERE id = target_asset.current_issued_code_id;
    IF issued_company IS NULL OR issued_company <> target_asset.company_id
       OR issued_display <> target_asset.asset_code OR issued_status <> 'active' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset requires its active issued code mirror';
    END IF;

    SELECT id, company_id, accounting_treatment, original_cost, finance_confirmed_at
      INTO finance_id, finance_company, finance_treatment, finance_cost, finance_confirmed
      FROM finance_assetfinance WHERE asset_id = target_asset.id;
    IF finance_id IS NULL OR finance_company <> target_asset.company_id
       OR finance_confirmed IS NULL OR finance_treatment IS NULL OR finance_cost IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset requires confirmed complete finance';
    END IF;

    IF target_asset.asset_status = 'pending_label' THEN
        SELECT count(*) INTO qr_count FROM assets_assetqridentity
         WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
           AND status = 'active' AND label_status IN ('ready_to_print', 'printed');
        SELECT count(*) INTO movement_count FROM assets_assetmovement
         WHERE asset_id = target_asset.id AND movement_type = 'label_activation';
        IF qr_count <> 1 OR movement_count <> 0 THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'pending label asset requires one printable active QR and no activation movement';
        END IF;
    ELSE
        SELECT count(*) INTO qr_count FROM assets_assetqridentity
         WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
           AND status = 'active'
           AND label_status IN ('ready_to_print', 'printed', 'attached');
        SELECT count(*) INTO movement_count FROM assets_assetmovement
         WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
           AND movement_type = 'label_activation';
        IF qr_count <> 1 OR movement_count <> 1 THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'active or idle asset requires one active QR and one activation movement';
        END IF;
    END IF;

    IF finance_treatment = 'fixed_asset' THEN
        IF NOT EXISTS (
            SELECT 1 FROM finance_assetdepreciationprofile
             WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
               AND (
                   (target_asset.asset_status = 'pending_label' AND status = 'active')
                   OR (
                       target_asset.asset_status IN ('in_use', 'idle')
                       AND status IN ('active', 'suspended', 'completed', 'stopped')
                   )
               )
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'fixed asset formalization requires one active depreciation profile';
        END IF;
    ELSE
        IF EXISTS (
            SELECT 1 FROM finance_assetdepreciationprofile
             WHERE asset_id = target_asset.id AND status IN ('active', 'suspended')
        ) OR EXISTS (
            SELECT 1 FROM finance_depreciationentry WHERE asset_id = target_asset.id
        ) OR EXISTS (
            SELECT 1 FROM finance_assetvalueadjustment WHERE asset_id = target_asset.id
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'controlled non-fixed asset cannot have depreciation or value adjustment history';
        END IF;
    END IF;

    SELECT count(*) INTO formalization_count
      FROM finance_financeformalizationrequest request
     WHERE request.asset_id = target_asset.id
       AND request.company_id = target_asset.company_id
       AND request.result_finance_id = finance_id
       AND request.result_issued_code_id = target_asset.current_issued_code_id
       AND request.status = 'completed';
    IF formalization_count <> 1 THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset requires its durable formalization idempotency result';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_qr_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    asset_company bigint;
    current_asset_status varchar;
    controlled_qr boolean;
    actor_only_clear boolean;
BEGIN
    SELECT asset.company_id, asset.asset_status
      INTO asset_company, current_asset_status
      FROM assets_asset AS asset WHERE asset.id = NEW.asset_id FOR SHARE;
    IF asset_company IS NULL OR asset_company <> NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'QR identity must be in the asset company';
    END IF;
    controlled_qr := COALESCE(
        current_setting('eam_lite.controlled_qr_identity_mutation', true), ''
    ) = 'on';
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'active' OR NEW.label_status <> 'ready_to_print'
           OR NEW.issued_by_id IS NULL THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'QR identity must be created active and ready-to-print by an identified actor';
        END IF;
        IF current_asset_status = 'pending_finance' THEN
            IF NEW.version <> 1 THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'formalization creates the first QR identity';
            END IF;
        ELSIF current_asset_status IN ('in_use', 'idle') THEN
            IF NOT controlled_qr OR NEW.version <= 1 OR NOT EXISTS (
                SELECT 1 FROM assets_assetqridentity old_qr
                 WHERE old_qr.asset_id = NEW.asset_id
                   AND old_qr.company_id = NEW.company_id
                   AND old_qr.version = NEW.version - 1
                   AND old_qr.status = 'revoked'
                   AND old_qr.label_status = 'attached'
            ) THEN
                RAISE EXCEPTION USING ERRCODE = '23514',
                    MESSAGE = 'replacement QR identity requires controlled relabelling of an active or idle asset';
            END IF;
            PERFORM set_config('eam_lite.controlled_qr_identity_mutation', 'off', true);
        ELSE
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'QR identity cannot be created in the current asset state';
        END IF;
    ELSE
        IF ROW(NEW.company_id, NEW.asset_id, NEW.public_token, NEW.issued_at, NEW.version)
           IS DISTINCT FROM
           ROW(OLD.company_id, OLD.asset_id, OLD.public_token, OLD.issued_at, OLD.version) THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'QR identity and token are immutable';
        END IF;
        actor_only_clear := ROW(
                NEW.status, NEW.label_status, NEW.revoked_at,
                NEW.revoke_reason, NEW.attached_at
            ) IS NOT DISTINCT FROM ROW(
                OLD.status, OLD.label_status, OLD.revoked_at,
                OLD.revoke_reason, OLD.attached_at
            )
            AND (NEW.issued_by_id IS NOT DISTINCT FROM OLD.issued_by_id
                 OR (OLD.issued_by_id IS NOT NULL AND NEW.issued_by_id IS NULL))
            AND (NEW.revoked_by_id IS NOT DISTINCT FROM OLD.revoked_by_id
                 OR (OLD.revoked_by_id IS NOT NULL AND NEW.revoked_by_id IS NULL))
            AND (NEW.attached_by_id IS NOT DISTINCT FROM OLD.attached_by_id
                 OR (OLD.attached_by_id IS NOT NULL AND NEW.attached_by_id IS NULL));
        IF actor_only_clear THEN
            RETURN NEW;
        END IF;
        IF NOT controlled_qr OR OLD.status = 'revoked'
           OR NEW.issued_by_id IS DISTINCT FROM OLD.issued_by_id THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'QR state must be changed by the controlled service';
        END IF;
        IF OLD.status = 'active' AND NEW.status = 'active'
           AND OLD.label_status = 'ready_to_print' AND NEW.label_status = 'printed'
           AND NEW.revoked_at IS NOT DISTINCT FROM OLD.revoked_at
           AND NEW.revoked_by_id IS NOT DISTINCT FROM OLD.revoked_by_id
           AND NEW.revoke_reason IS NOT DISTINCT FROM OLD.revoke_reason
           AND NEW.attached_at IS NOT DISTINCT FROM OLD.attached_at
           AND NEW.attached_by_id IS NOT DISTINCT FROM OLD.attached_by_id THEN
            NULL;
        ELSIF OLD.status = 'active' AND NEW.status = 'active'
           AND OLD.label_status = 'printed' AND NEW.label_status = 'attached'
           AND NEW.attached_at IS NOT NULL AND NEW.attached_by_id IS NOT NULL
           AND NEW.revoked_at IS NOT DISTINCT FROM OLD.revoked_at
           AND NEW.revoked_by_id IS NOT DISTINCT FROM OLD.revoked_by_id
           AND NEW.revoke_reason IS NOT DISTINCT FROM OLD.revoke_reason THEN
            NULL;
        ELSIF OLD.status = 'active' AND NEW.status = 'revoked'
           AND OLD.label_status = 'attached' AND NEW.label_status = 'attached'
           AND NEW.revoked_at IS NOT NULL AND NEW.revoked_by_id IS NOT NULL
           AND btrim(NEW.revoke_reason) <> ''
           AND NEW.attached_at IS NOT DISTINCT FROM OLD.attached_at
           AND NEW.attached_by_id IS NOT DISTINCT FROM OLD.attached_by_id THEN
            NULL;
        ELSE
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'invalid QR state transition for Sprint 6';
        END IF;
        PERFORM set_config('eam_lite.controlled_qr_identity_mutation', 'off', true);
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_label_batch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    controlled_label boolean;
    actor_only_clear boolean;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status NOT IN ('draft', 'generated') OR NEW.created_by_id IS NULL
           OR NEW.printed_by_id IS NOT NULL OR NEW.printed_at IS NOT NULL
           OR btrim(NEW.batch_code) = '' OR btrim(NEW.template_version) = ''
           OR btrim(NEW.idempotency_key) = '' THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'invalid new label print batch';
        END IF;
        RETURN NEW;
    END IF;
    IF ROW(
        NEW.company_id, NEW.batch_code, NEW.template_version,
        NEW.include_responsible_employee, NEW.include_location,
        NEW.include_model, NEW.created_at, NEW.idempotency_key
    ) IS DISTINCT FROM ROW(
        OLD.company_id, OLD.batch_code, OLD.template_version,
        OLD.include_responsible_employee, OLD.include_location,
        OLD.include_model, OLD.created_at, OLD.idempotency_key
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label print batch identity and layout are immutable';
    END IF;
    actor_only_clear := NEW.status IS NOT DISTINCT FROM OLD.status
        AND NEW.printed_at IS NOT DISTINCT FROM OLD.printed_at
        AND (NEW.created_by_id IS NOT DISTINCT FROM OLD.created_by_id
             OR (OLD.created_by_id IS NOT NULL AND NEW.created_by_id IS NULL))
        AND (NEW.printed_by_id IS NOT DISTINCT FROM OLD.printed_by_id
             OR (OLD.printed_by_id IS NOT NULL AND NEW.printed_by_id IS NULL));
    IF actor_only_clear THEN
        RETURN NEW;
    END IF;
    controlled_label := COALESCE(
        current_setting('eam_lite.controlled_label_batch_mutation', true), ''
    ) = 'on';
    IF NOT controlled_label OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label print batch state must be changed by the controlled service';
    END IF;
    IF OLD.status = 'draft' AND NEW.status = 'generated'
       AND NEW.printed_by_id IS NULL AND NEW.printed_at IS NULL THEN
        NULL;
    ELSIF OLD.status = 'generated' AND NEW.status = 'printed'
       AND NEW.printed_by_id IS NOT NULL AND NEW.printed_at IS NOT NULL THEN
        NULL;
    ELSIF OLD.status = 'generated' AND NEW.status = 'cancelled'
       AND NEW.printed_by_id IS NULL AND NEW.printed_at IS NULL THEN
        NULL;
    ELSE
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'invalid label print batch state transition';
    END IF;
    PERFORM set_config('eam_lite.controlled_label_batch_mutation', 'off', true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_label_item()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    batch_company bigint;
    batch_status varchar;
    qr_company bigint;
    qr_status varchar;
    qr_label_status varchar;
    controlled_label boolean;
BEGIN
    SELECT company_id, status INTO batch_company, batch_status
      FROM assets_assetlabelprintbatch WHERE id = NEW.batch_id FOR SHARE;
    SELECT company_id, status, label_status
      INTO qr_company, qr_status, qr_label_status
      FROM assets_assetqridentity WHERE id = NEW.qr_identity_id FOR SHARE;
    IF batch_company IS NULL OR qr_company IS NULL OR batch_company <> qr_company THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label item batch and QR identity must be in the same company';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF batch_status <> 'generated' OR NEW.print_status <> 'generated'
           OR qr_status <> 'active'
           OR qr_label_status NOT IN ('ready_to_print', 'printed')
           OR jsonb_typeof(NEW.label_snapshot_json) <> 'object'
           OR NEW.label_snapshot_json = '{}'::jsonb
           OR NEW.label_snapshot_json ?| ARRAY[
               'public_token', 'token', 'original_cost', 'book_value',
               'accumulated_depreciation', 'impairment', 'disposal_income'
           ] THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'label items require a generated batch and a printable active QR identity';
        END IF;
        RETURN NEW;
    END IF;
    IF ROW(NEW.batch_id, NEW.qr_identity_id, NEW.page_no,
           NEW.position_no, NEW.label_snapshot_json, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.batch_id, OLD.qr_identity_id, OLD.page_no,
           OLD.position_no, OLD.label_snapshot_json, OLD.created_at) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label print item identity and position are immutable';
    END IF;
    controlled_label := COALESCE(
        current_setting('eam_lite.controlled_label_batch_mutation', true), ''
    ) = 'on';
    IF NOT controlled_label OR OLD.print_status <> 'generated'
       OR NOT (
           (NEW.print_status = 'printed' AND batch_status = 'printed')
           OR (NEW.print_status = 'cancelled' AND batch_status = 'cancelled')
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label item state must follow its controlled parent batch';
    END IF;
    PERFORM set_config('eam_lite.controlled_label_batch_mutation', 'off', true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_label_batch_commit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_batch_id uuid;
    target_status varchar;
    item_count integer;
    inconsistent_count integer;
BEGIN
    IF TG_TABLE_NAME = 'assets_assetlabelprintbatch' THEN
        target_batch_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    ELSE
        target_batch_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.batch_id ELSE NEW.batch_id END;
    END IF;
    SELECT status INTO target_status
      FROM assets_assetlabelprintbatch WHERE id = target_batch_id;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    SELECT count(*) INTO item_count FROM assets_assetlabelprintitem
     WHERE batch_id = target_batch_id;
    IF target_status = 'draft' THEN
        IF item_count <> 0 THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'draft label batch cannot contain items';
        END IF;
        RETURN NULL;
    END IF;
    IF item_count = 0 THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'generated label batch must contain at least one item';
    END IF;
    SELECT count(*) INTO inconsistent_count
      FROM assets_assetlabelprintitem
     WHERE batch_id = target_batch_id
       AND print_status <> target_status;
    IF inconsistent_count <> 0 THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label batch and item states are inconsistent';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_movement_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    controlled_movement boolean;
    asset_company bigint;
    ref_company bigint;
BEGIN
    controlled_movement := COALESCE(
        current_setting('eam_lite.controlled_asset_movement_insert', true), ''
    ) = 'on';
    IF NOT controlled_movement THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'asset movement must be created by the controlled service';
    END IF;
    IF NEW.movement_type <> 'label_activation'
       OR NEW.from_status <> 'pending_label'
       OR NEW.to_status NOT IN ('in_use', 'idle')
       OR NEW.effective_at > clock_timestamp()
       OR NEW.operated_by_id IS NULL
       OR btrim(NEW.reason) = ''
       OR btrim(NEW.idempotency_key) = '' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'invalid Sprint 6 label activation movement';
    END IF;
    SELECT company_id INTO asset_company FROM assets_asset WHERE id = NEW.asset_id FOR SHARE;
    IF asset_company IS NULL OR asset_company <> NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'movement asset must be in the same company';
    END IF;
    IF NEW.from_department_id IS NULL OR NEW.from_department_id <> NEW.to_department_id
       OR NEW.from_employee_id IS NULL OR NEW.from_employee_id <> NEW.to_employee_id
       OR NEW.from_location_id IS NULL OR NEW.from_location_id <> NEW.to_location_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label activation must preserve complete responsibility and location snapshots';
    END IF;
    SELECT company_id INTO ref_company FROM masterdata_department WHERE id = NEW.from_department_id;
    IF ref_company IS NULL OR ref_company <> NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'movement department must be in the same company';
    END IF;
    SELECT company_id INTO ref_company FROM masterdata_employee WHERE id = NEW.from_employee_id;
    IF ref_company IS NULL OR ref_company <> NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'movement employee must be in the same company';
    END IF;
    SELECT company_id INTO ref_company FROM masterdata_location WHERE id = NEW.from_location_id;
    IF ref_company IS NULL OR ref_company <> NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'movement location must be in the same company';
    END IF;
    PERFORM set_config('eam_lite.controlled_asset_movement_insert', 'off', true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_movement_commit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target assets_assetmovement%%ROWTYPE;
    current_asset assets_asset%%ROWTYPE;
    attached_qr_count integer;
BEGIN
    SELECT * INTO target FROM assets_assetmovement
     WHERE id = CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    SELECT * INTO current_asset FROM assets_asset WHERE id = target.asset_id;
    IF NOT FOUND OR current_asset.company_id <> target.company_id
       OR current_asset.asset_status <> target.to_status
       OR current_asset.department_id <> target.to_department_id
       OR current_asset.responsible_employee_id <> target.to_employee_id
       OR current_asset.location_id <> target.to_location_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label activation movement must match the committed asset state';
    END IF;
    SELECT count(*) INTO attached_qr_count FROM assets_assetqridentity
     WHERE asset_id = target.asset_id AND company_id = target.company_id
       AND status = 'active' AND label_status = 'attached';
    IF attached_qr_count <> 1 THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label activation requires exactly one attached current QR identity';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_reject_label_history_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND OLD.operated_by_id IS NOT NULL AND NEW.operated_by_id IS NULL
       AND ROW(
           NEW.id, NEW.company_id, NEW.asset_id, NEW.movement_type,
           NEW.effective_at, NEW.from_department_id, NEW.to_department_id,
           NEW.from_employee_id, NEW.to_employee_id,
           NEW.from_location_id, NEW.to_location_id,
           NEW.from_status, NEW.to_status, NEW.reason, NEW.remark,
           NEW.idempotency_key, NEW.created_at
       ) IS NOT DISTINCT FROM ROW(
           OLD.id, OLD.company_id, OLD.asset_id, OLD.movement_type,
           OLD.effective_at, OLD.from_department_id, OLD.to_department_id,
           OLD.from_employee_id, OLD.to_employee_id,
           OLD.from_location_id, OLD.to_location_id,
           OLD.from_status, OLD.to_status, OLD.reason, OLD.remark,
           OLD.idempotency_key, OLD.created_at
       ) THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION USING ERRCODE = '23514',
        MESSAGE = 'label and movement history cannot be deleted or rewritten';
END;
$$;

CREATE OR REPLACE FUNCTION assets_reject_label_history_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION USING ERRCODE = '23514',
        MESSAGE = 'label and movement history cannot be deleted or rewritten';
END;
$$;

DROP TRIGGER IF EXISTS trg_sprint6_movement_asset_commit ON assets_assetmovement;
CREATE CONSTRAINT TRIGGER trg_sprint6_movement_asset_commit
AFTER INSERT OR UPDATE OR DELETE ON assets_assetmovement
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION assets_validate_formal_asset_commit();

DROP TRIGGER IF EXISTS trg_assets_label_batch_validate ON assets_assetlabelprintbatch;
CREATE TRIGGER trg_assets_label_batch_validate
BEFORE INSERT OR UPDATE ON assets_assetlabelprintbatch
FOR EACH ROW EXECUTE FUNCTION assets_validate_label_batch();

DROP TRIGGER IF EXISTS trg_assets_label_batch_delete ON assets_assetlabelprintbatch;
CREATE TRIGGER trg_assets_label_batch_delete
BEFORE DELETE ON assets_assetlabelprintbatch
FOR EACH ROW EXECUTE FUNCTION assets_reject_label_history_delete();

DROP TRIGGER IF EXISTS trg_assets_label_item_validate ON assets_assetlabelprintitem;
CREATE TRIGGER trg_assets_label_item_validate
BEFORE INSERT OR UPDATE ON assets_assetlabelprintitem
FOR EACH ROW EXECUTE FUNCTION assets_validate_label_item();

DROP TRIGGER IF EXISTS trg_assets_label_item_delete ON assets_assetlabelprintitem;
CREATE TRIGGER trg_assets_label_item_delete
BEFORE DELETE ON assets_assetlabelprintitem
FOR EACH ROW EXECUTE FUNCTION assets_reject_label_history_delete();

DROP TRIGGER IF EXISTS trg_assets_label_batch_commit ON assets_assetlabelprintbatch;
CREATE CONSTRAINT TRIGGER trg_assets_label_batch_commit
AFTER INSERT OR UPDATE OR DELETE ON assets_assetlabelprintbatch
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION assets_validate_label_batch_commit();

DROP TRIGGER IF EXISTS trg_assets_label_item_commit ON assets_assetlabelprintitem;
CREATE CONSTRAINT TRIGGER trg_assets_label_item_commit
AFTER INSERT OR UPDATE OR DELETE ON assets_assetlabelprintitem
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION assets_validate_label_batch_commit();

DROP TRIGGER IF EXISTS trg_assets_movement_validate ON assets_assetmovement;
CREATE TRIGGER trg_assets_movement_validate
BEFORE INSERT ON assets_assetmovement
FOR EACH ROW EXECUTE FUNCTION assets_validate_movement_insert();

DROP TRIGGER IF EXISTS trg_assets_movement_change ON assets_assetmovement;
CREATE TRIGGER trg_assets_movement_change
BEFORE UPDATE OR DELETE ON assets_assetmovement
FOR EACH ROW EXECUTE FUNCTION assets_reject_label_history_change();

DROP TRIGGER IF EXISTS trg_assets_movement_commit ON assets_assetmovement;
CREATE CONSTRAINT TRIGGER trg_assets_movement_commit
AFTER INSERT OR UPDATE OR DELETE ON assets_assetmovement
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION assets_validate_movement_commit();
"""


DROP_SQL = r"""
DROP TRIGGER IF EXISTS trg_assets_movement_commit ON assets_assetmovement;
DROP TRIGGER IF EXISTS trg_assets_movement_change ON assets_assetmovement;
DROP TRIGGER IF EXISTS trg_assets_movement_validate ON assets_assetmovement;
DROP TRIGGER IF EXISTS trg_assets_label_item_commit ON assets_assetlabelprintitem;
DROP TRIGGER IF EXISTS trg_assets_label_batch_commit ON assets_assetlabelprintbatch;
DROP TRIGGER IF EXISTS trg_assets_label_item_delete ON assets_assetlabelprintitem;
DROP TRIGGER IF EXISTS trg_assets_label_item_validate ON assets_assetlabelprintitem;
DROP TRIGGER IF EXISTS trg_assets_label_batch_delete ON assets_assetlabelprintbatch;
DROP TRIGGER IF EXISTS trg_assets_label_batch_validate ON assets_assetlabelprintbatch;
DROP TRIGGER IF EXISTS trg_sprint6_movement_asset_commit ON assets_assetmovement;
DROP FUNCTION IF EXISTS assets_reject_label_history_delete();
DROP FUNCTION IF EXISTS assets_reject_label_history_change();
DROP FUNCTION IF EXISTS assets_validate_movement_commit();
DROP FUNCTION IF EXISTS assets_validate_movement_insert();
DROP FUNCTION IF EXISTS assets_validate_label_batch_commit();
DROP FUNCTION IF EXISTS assets_validate_label_item();
DROP FUNCTION IF EXISTS assets_validate_label_batch();
DROP FUNCTION IF EXISTS assets_validate_qr_identity();
DROP FUNCTION IF EXISTS assets_validate_formal_asset_commit();
DROP FUNCTION IF EXISTS assets_validate_asset_references();
"""


def install_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CREATE_SQL)


def remove_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(DROP_SQL)
        previous = import_module(
            "apps.assets.migrations.0004_sprint4_formal_asset_guards"
        )
        schema_editor.execute(previous.CREATE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_sprint5_initialization_source'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLabelPrintBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=64, verbose_name='批次编号')),
                ('template_version', models.CharField(max_length=32, verbose_name='模板版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成'), ('printed', '已打印'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='批次状态')),
                ('include_responsible_employee', models.BooleanField(default=False, verbose_name='显示责任人')),
                ('include_location', models.BooleanField(default=False, verbose_name='显示位置')),
                ('include_model', models.BooleanField(default=False, verbose_name='显示型号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='打印确认时间')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_label_print_batches', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_label_print_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_asset_label_print_batches', to=settings.AUTH_USER_MODEL, verbose_name='打印确认人')),
            ],
            options={
                'verbose_name': '资产标签打印批次',
                'verbose_name_plural': '资产标签打印批次',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetLabelPrintItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_no', models.PositiveIntegerField(verbose_name='页码')),
                ('position_no', models.PositiveIntegerField(verbose_name='页内位置')),
                ('label_snapshot_json', models.JSONField(default=dict, verbose_name='标签文字快照')),
                ('print_status', models.CharField(choices=[('generated', '已生成'), ('printed', '已打印'), ('cancelled', '已取消')], default='generated', max_length=16, verbose_name='打印状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetlabelprintbatch', verbose_name='打印批次')),
                ('qr_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_items', to='assets.assetqridentity', verbose_name='二维码身份')),
            ],
            options={
                'verbose_name': '资产标签打印明细',
                'verbose_name_plural': '资产标签打印明细',
                'ordering': ('batch_id', 'page_no', 'position_no'),
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('label_activation', '首次贴标启用')], max_length=32, verbose_name='变动类型')),
                ('effective_at', models.DateTimeField(verbose_name='生效时间')),
                ('from_status', models.CharField(max_length=32, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=32, verbose_name='新状态')),
                ('reason', models.TextField(verbose_name='原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='assets.asset', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_movements', to='masterdata.company', verbose_name='公司')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_movements_from_department', to='masterdata.department', verbose_name='原部门')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_movements_from_employee', to='masterdata.employee', verbose_name='原责任人')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_movements_from_location', to='masterdata.location', verbose_name='原位置')),
                ('operated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_asset_movements', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_movements_to_department', to='masterdata.department', verbose_name='新部门')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_movements_to_employee', to='masterdata.employee', verbose_name='新责任人')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_movements_to_location', to='masterdata.location', verbose_name='新位置')),
            ],
            options={
                'verbose_name': '资产变动历史',
                'verbose_name_plural': '资产变动历史',
                'ordering': ('asset_id', 'effective_at', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintbatch',
            constraint=models.UniqueConstraint(fields=('company', 'batch_code'), name='uq_label_batch_company_code'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintbatch',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_label_batch_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'generated', 'printed', 'cancelled'))), name='ck_label_batch_status'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('printed_at__isnull', False), ('status', 'printed')), models.Q(('printed_at__isnull', True), ('printed_by__isnull', True), ('status__in', ('draft', 'generated', 'cancelled'))), _connector='OR'), name='ck_label_batch_print_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(('batch_code', ''), _negated=True), name='ck_label_batch_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(('template_version', ''), _negated=True), name='ck_label_batch_template_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='ck_label_batch_idem_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintitem',
            constraint=models.UniqueConstraint(fields=('batch', 'qr_identity'), name='uq_label_item_batch_qr'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintitem',
            constraint=models.UniqueConstraint(fields=('batch', 'page_no', 'position_no'), name='uq_label_item_batch_position'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintitem',
            constraint=models.CheckConstraint(condition=models.Q(('page_no__gte', 1)), name='ck_label_item_page_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintitem',
            constraint=models.CheckConstraint(condition=models.Q(('position_no__gte', 1)), name='ck_label_item_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelprintitem',
            constraint=models.CheckConstraint(condition=models.Q(('print_status__in', ('generated', 'printed', 'cancelled'))), name='ck_label_item_status'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_movement_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type', 'label_activation')), fields=('asset',), name='uq_movement_asset_label_activation'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type', 'label_activation')), name='ck_movement_sprint6_type'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_department__isnull', False), ('from_employee__isnull', False), ('from_location__isnull', False), ('from_status', 'pending_label'), ('movement_type', 'label_activation'), ('to_department__isnull', False), ('to_employee__isnull', False), ('to_location__isnull', False), ('to_status__in', ('in_use', 'idle'))), name='ck_movement_label_activation_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_department', models.F('to_department'))), name='ck_movement_label_same_department'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_employee', models.F('to_employee'))), name='ck_movement_label_same_employee'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('from_location', models.F('to_location'))), name='ck_movement_label_same_location'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='ck_movement_idem_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='ck_movement_reason_nonempty'),
        ),
        migrations.RunPython(
            install_postgresql_guards,
            reverse_code=remove_postgresql_guards,
        ),
    ]
