# Generated by Django 5.2.17 on 2026-08-13 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


CREATE_SQL = r"""
CREATE OR REPLACE FUNCTION assets_guard_label_attachment_request()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    asset_company bigint;
    qr_company bigint;
    qr_asset uuid;
BEGIN
    IF TG_OP = 'UPDATE'
       AND OLD.completed_by_id IS NOT NULL AND NEW.completed_by_id IS NULL
       AND ROW(
           NEW.id, NEW.company_id, NEW.asset_id, NEW.qr_identity_id,
           NEW.idempotency_key, NEW.request_hash, NEW.target_status,
           NEW.completed_at
       ) IS NOT DISTINCT FROM ROW(
           OLD.id, OLD.company_id, OLD.asset_id, OLD.qr_identity_id,
           OLD.idempotency_key, OLD.request_hash, OLD.target_status,
           OLD.completed_at
       ) THEN
        RETURN NEW;
    ELSIF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'label attachment idempotency results are append-only';
    END IF;
    SELECT company_id INTO asset_company FROM assets_asset WHERE id = NEW.asset_id;
    SELECT company_id, asset_id INTO qr_company, qr_asset
      FROM assets_assetqridentity WHERE id = NEW.qr_identity_id;
    IF asset_company IS NULL OR asset_company <> NEW.company_id
       OR qr_company IS NULL OR qr_company <> NEW.company_id
       OR qr_asset <> NEW.asset_id
       OR btrim(NEW.idempotency_key) = ''
       OR NEW.request_hash !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'invalid label attachment idempotency result';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_assets_label_attachment_request_guard
    ON assets_assetlabelattachmentrequest;
CREATE TRIGGER trg_assets_label_attachment_request_guard
BEFORE INSERT OR UPDATE OR DELETE ON assets_assetlabelattachmentrequest
FOR EACH ROW EXECUTE FUNCTION assets_guard_label_attachment_request();
"""


DROP_SQL = r"""
DROP TRIGGER IF EXISTS trg_assets_label_attachment_request_guard
    ON assets_assetlabelattachmentrequest;
DROP FUNCTION IF EXISTS assets_guard_label_attachment_request();
"""


def install_postgresql_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CREATE_SQL)


def remove_postgresql_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(DROP_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_sprint6_qr_labels'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLabelAttachmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('target_status', models.CharField(blank=True, max_length=32)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_attachment_requests', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_label_attachment_requests', to='masterdata.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_asset_label_attachment_requests', to=settings.AUTH_USER_MODEL)),
                ('qr_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_requests', to='assets.assetqridentity')),
            ],
            options={
                'ordering': ('completed_at', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_label_attach_request_company_idem'), models.CheckConstraint(condition=models.Q(models.Q(('idempotency_key', ''), _negated=True), models.Q(('request_hash', ''), _negated=True)), name='ck_label_attach_request_values')],
            },
        ),
        migrations.RunPython(install_postgresql_guard, remove_postgresql_guard),
    ]
