# Generated by Django 5.2.17 on 2026-08-13 01:02

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


ASSET_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION assets_validate_formal_asset_commit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_asset_id uuid;
    target_asset assets_asset%%ROWTYPE;
    issued_company bigint;
    issued_display varchar;
    issued_status varchar;
    finance_id uuid;
    finance_company bigint;
    finance_treatment varchar;
    finance_cost numeric;
    finance_confirmed timestamptz;
    qr_count integer;
    movement_count integer;
    formalization_count integer;
    formalized_issued_id bigint;
    correction_chain_valid boolean := false;
BEGIN
    IF TG_TABLE_NAME = 'assets_asset' THEN
        target_asset_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    ELSIF TG_TABLE_NAME IN (
        'finance_assetfinance', 'assets_assetqridentity',
        'finance_assetdepreciationprofile', 'finance_financeformalizationrequest',
        'assets_assetmovement'
    ) THEN
        target_asset_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.asset_id ELSE NEW.asset_id END;
    ELSIF TG_TABLE_NAME IN (
        'finance_depreciationentry', 'finance_assetvalueadjustment'
    ) THEN
        target_asset_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.asset_id ELSE NEW.asset_id END;
    ELSIF TG_TABLE_NAME = 'masterdata_issuedcode' THEN
        SELECT asset.id INTO target_asset_id
          FROM assets_asset asset
         WHERE asset.current_issued_code_id = CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    ELSE
        RETURN NULL;
    END IF;
    SELECT * INTO target_asset FROM assets_asset WHERE id = target_asset_id;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    IF target_asset.asset_status IN ('draft', 'pending_finance') THEN
        IF EXISTS (
            SELECT 1 FROM assets_assetqridentity
             WHERE asset_id = target_asset.id
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'draft or pending finance asset cannot retain a QR identity outside formalization';
        END IF;
        RETURN NULL;
    END IF;
    IF target_asset.asset_status NOT IN ('pending_label', 'in_use', 'idle') THEN
        RETURN NULL;
    END IF;

    SELECT company_id, display_code, status
      INTO issued_company, issued_display, issued_status
      FROM masterdata_issuedcode WHERE id = target_asset.current_issued_code_id;
    IF issued_company IS NULL OR issued_company <> target_asset.company_id
       OR issued_display <> target_asset.asset_code OR issued_status <> 'active' THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset requires its active issued code mirror';
    END IF;

    SELECT id, company_id, accounting_treatment, original_cost, finance_confirmed_at
      INTO finance_id, finance_company, finance_treatment, finance_cost, finance_confirmed
      FROM finance_assetfinance WHERE asset_id = target_asset.id;
    IF finance_id IS NULL OR finance_company <> target_asset.company_id
       OR finance_confirmed IS NULL OR finance_treatment IS NULL OR finance_cost IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset requires confirmed complete finance';
    END IF;

    IF target_asset.asset_status = 'pending_label' THEN
        SELECT count(*) INTO qr_count FROM assets_assetqridentity
         WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
           AND status = 'active' AND label_status IN ('ready_to_print', 'printed');
        SELECT count(*) INTO movement_count FROM assets_assetmovement
         WHERE asset_id = target_asset.id AND movement_type = 'label_activation';
        IF qr_count <> 1 OR movement_count <> 0 THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'pending label asset requires one printable active QR and no activation movement';
        END IF;
    ELSE
        SELECT count(*) INTO qr_count FROM assets_assetqridentity
         WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
           AND status = 'active'
           AND label_status IN ('ready_to_print', 'printed', 'attached');
        SELECT count(*) INTO movement_count FROM assets_assetmovement
         WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
           AND movement_type = 'label_activation';
        IF qr_count <> 1 OR movement_count <> 1 THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'active or idle asset requires one active QR and one activation movement';
        END IF;
    END IF;

    IF finance_treatment = 'fixed_asset' THEN
        IF NOT EXISTS (
            SELECT 1 FROM finance_assetdepreciationprofile
             WHERE asset_id = target_asset.id AND company_id = target_asset.company_id
               AND (
                   (target_asset.asset_status = 'pending_label' AND status = 'active')
                   OR (
                       target_asset.asset_status IN ('in_use', 'idle')
                       AND status IN ('active', 'suspended', 'completed', 'stopped')
                   )
               )
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'fixed asset formalization requires one active depreciation profile';
        END IF;
    ELSE
        IF EXISTS (
            SELECT 1 FROM finance_assetdepreciationprofile
             WHERE asset_id = target_asset.id AND status IN ('active', 'suspended')
        ) OR EXISTS (
            SELECT 1 FROM finance_depreciationentry WHERE asset_id = target_asset.id
        ) OR EXISTS (
            SELECT 1 FROM finance_assetvalueadjustment WHERE asset_id = target_asset.id
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'controlled non-fixed asset cannot have depreciation or value adjustment history';
        END IF;
    END IF;

    SELECT count(*) INTO formalization_count
      FROM finance_financeformalizationrequest request
     WHERE request.asset_id = target_asset.id
       AND request.company_id = target_asset.company_id
       AND request.result_finance_id = finance_id
       AND request.status = 'completed';
    IF formalization_count <> 1 THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset requires its durable formalization idempotency result';
    END IF;
    SELECT request.result_issued_code_id INTO formalized_issued_id
      FROM finance_financeformalizationrequest request
     WHERE request.asset_id = target_asset.id
       AND request.company_id = target_asset.company_id
       AND request.result_finance_id = finance_id
       AND request.status = 'completed';
    IF formalized_issued_id IS DISTINCT FROM target_asset.current_issued_code_id THEN
        WITH RECURSIVE correction_chain(issued_code_id) AS (
            SELECT formalized_issued_id
            UNION
            SELECT history.new_issued_code_id
              FROM assets_assetcodehistory history
              JOIN correction_chain chain
                ON history.old_issued_code_id = chain.issued_code_id
             WHERE history.asset_id = target_asset.id
               AND history.company_id = target_asset.company_id
               AND history.event_type = 'corrected'
        )
        SELECT EXISTS (
            SELECT 1 FROM correction_chain
             WHERE issued_code_id = target_asset.current_issued_code_id
        ) INTO correction_chain_valid;
        IF NOT correction_chain_valid THEN
            RAISE EXCEPTION USING ERRCODE = '23514',
                MESSAGE = 'current issued code must descend from the immutable formalization result';
        END IF;
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_validate_movement()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    ref_company bigint;
    expected_from_status varchar;
    expected_to_status varchar;
BEGIN
    IF COALESCE(current_setting('eam_lite.controlled_asset_movement_insert', true), '') <> 'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset movement must be created by the controlled service';
    END IF;
    IF NEW.movement_type NOT IN (
        'assignment','assignment_return','transfer','loan','loan_return','idle','activate',
        'repair_start','repair_complete','label_activation','disposal_start','disposal_cancel',
        'disposal_complete','disposal_reversal'
    ) OR NEW.effective_at > clock_timestamp() OR NEW.operated_by_id IS NULL
       OR btrim(NEW.reason) = '' OR btrim(NEW.idempotency_key) = '' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid asset movement';
    END IF;
    SELECT company_id INTO ref_company FROM assets_asset WHERE id=NEW.asset_id FOR SHARE;
    IF ref_company IS NULL OR ref_company <> NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='movement asset must be in the same company';
    END IF;
    FOR ref_company IN
        SELECT company_id FROM masterdata_department WHERE id IN (NEW.from_department_id, NEW.to_department_id)
        UNION ALL SELECT company_id FROM masterdata_employee WHERE id IN (NEW.from_employee_id, NEW.to_employee_id)
        UNION ALL SELECT company_id FROM masterdata_location WHERE id IN (NEW.from_location_id, NEW.to_location_id)
    LOOP
        IF ref_company <> NEW.company_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='movement references must be in the same company';
        END IF;
    END LOOP;
    IF NEW.movement_type='label_activation' AND NOT (
        NEW.from_status='pending_label' AND NEW.to_status IN ('in_use','idle')
        AND NEW.from_department_id IS NOT NULL AND NEW.from_department_id=NEW.to_department_id
        AND NEW.from_employee_id IS NOT NULL AND NEW.from_employee_id=NEW.to_employee_id
        AND NEW.from_location_id IS NOT NULL AND NEW.from_location_id=NEW.to_location_id
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid label activation movement';
    END IF;
    IF NEW.movement_type='idle' AND NOT (NEW.from_status='in_use' AND NEW.to_status='idle')
       OR NEW.movement_type='activate' AND NOT (NEW.from_status='idle' AND NEW.to_status='in_use')
       OR NEW.movement_type='repair_start' AND NOT (NEW.from_status IN ('in_use','idle') AND NEW.to_status='under_repair')
       OR NEW.movement_type='repair_complete' AND NOT (NEW.from_status='under_repair' AND NEW.to_status IN ('in_use','idle'))
       OR NEW.movement_type='loan' AND NOT (NEW.from_status IN ('in_use','idle') AND NEW.to_status='loaned')
       OR NEW.movement_type='loan_return' AND NOT (NEW.from_status='loaned' AND NEW.to_status IN ('in_use','idle'))
       OR NEW.movement_type='disposal_start' AND NOT (NEW.from_status IN ('in_use','idle','under_repair') AND NEW.to_status='pending_disposal')
       OR NEW.movement_type='disposal_cancel' AND NOT (NEW.from_status='pending_disposal' AND NEW.to_status IN ('in_use','idle','under_repair'))
       OR NEW.movement_type='disposal_complete' AND NOT (NEW.from_status='pending_disposal' AND NEW.to_status IN ('disposed','sold','other_disposed'))
       OR NEW.movement_type='disposal_reversal' AND NOT (NEW.from_status IN ('disposed','sold','other_disposed') AND NEW.to_status IN ('in_use','idle','under_repair')) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='movement status transition is invalid';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_validate_movement_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE current_asset assets_asset%%ROWTYPE; latest_movement uuid;
BEGIN
    SELECT id INTO latest_movement FROM assets_assetmovement
     WHERE asset_id=NEW.asset_id ORDER BY created_at DESC,id DESC LIMIT 1;
    IF latest_movement IS DISTINCT FROM NEW.id THEN
        RETURN NULL;
    END IF;
    SELECT * INTO current_asset FROM assets_asset WHERE id=NEW.asset_id;
    IF NOT FOUND OR current_asset.company_id<>NEW.company_id
       OR current_asset.asset_status<>NEW.to_status
       OR current_asset.department_id IS DISTINCT FROM NEW.to_department_id
       OR current_asset.responsible_employee_id IS DISTINCT FROM NEW.to_employee_id
       OR current_asset.location_id IS DISTINCT FROM NEW.to_location_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='movement must match committed asset current state';
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_guard_history()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE controlled boolean;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23503', MESSAGE='lifecycle history cannot be deleted';
    END IF;
    IF TG_TABLE_NAME='assets_assetloan' THEN
        controlled := COALESCE(current_setting('eam_lite.controlled_asset_loan_mutation',true),'')='on';
        IF ((OLD.handled_by_id IS NOT NULL AND NEW.handled_by_id IS NULL)
            OR (OLD.created_by_id IS NOT NULL AND NEW.created_by_id IS NULL))
           AND (to_jsonb(NEW)-ARRAY['handled_by_id','created_by_id','updated_at'])
               =(to_jsonb(OLD)-ARRAY['handled_by_id','created_by_id','updated_at'])
           AND (NEW.handled_by_id IS NOT DISTINCT FROM OLD.handled_by_id OR NEW.handled_by_id IS NULL)
           AND (NEW.created_by_id IS NOT DISTINCT FROM OLD.created_by_id OR NEW.created_by_id IS NULL) THEN RETURN NEW; END IF;
        IF controlled THEN
        IF OLD.status='active' AND NEW.status='returned'
           AND ROW(NEW.company_id,NEW.asset_id,NEW.borrower_type,NEW.borrower_employee_id,
                   NEW.borrower_name_snapshot,NEW.borrower_name,NEW.borrower_organization,
                   NEW.loan_date,NEW.expected_return_date,NEW.previous_asset_status,NEW.reason,
                   NEW.loan_movement_id,NEW.loan_idempotency_key,NEW.created_at)
               IS NOT DISTINCT FROM
               ROW(OLD.company_id,OLD.asset_id,OLD.borrower_type,OLD.borrower_employee_id,
                   OLD.borrower_name_snapshot,OLD.borrower_name,OLD.borrower_organization,
                   OLD.loan_date,OLD.expected_return_date,OLD.previous_asset_status,OLD.reason,
                   OLD.loan_movement_id,OLD.loan_idempotency_key,OLD.created_at) THEN
            PERFORM set_config('eam_lite.controlled_asset_loan_mutation','off',true);
            RETURN NEW;
        END IF;
        END IF;
    ELSIF TG_TABLE_NAME='assets_assetdisposal' THEN
        controlled := COALESCE(current_setting('eam_lite.controlled_asset_disposal_mutation',true),'')='on';
        IF ((OLD.initiated_by_id IS NOT NULL AND NEW.initiated_by_id IS NULL)
            OR (OLD.finance_locked_by_id IS NOT NULL AND NEW.finance_locked_by_id IS NULL)
            OR (OLD.handled_by_id IS NOT NULL AND NEW.handled_by_id IS NULL)
            OR (OLD.confirmed_by_id IS NOT NULL AND NEW.confirmed_by_id IS NULL)
            OR (OLD.cancelled_by_id IS NOT NULL AND NEW.cancelled_by_id IS NULL))
           AND (to_jsonb(NEW)-ARRAY['initiated_by_id','finance_locked_by_id','handled_by_id','confirmed_by_id','cancelled_by_id','updated_at'])
               =(to_jsonb(OLD)-ARRAY['initiated_by_id','finance_locked_by_id','handled_by_id','confirmed_by_id','cancelled_by_id','updated_at'])
           AND (NEW.initiated_by_id IS NOT DISTINCT FROM OLD.initiated_by_id OR NEW.initiated_by_id IS NULL)
           AND (NEW.finance_locked_by_id IS NOT DISTINCT FROM OLD.finance_locked_by_id OR NEW.finance_locked_by_id IS NULL)
           AND (NEW.handled_by_id IS NOT DISTINCT FROM OLD.handled_by_id OR NEW.handled_by_id IS NULL)
           AND (NEW.confirmed_by_id IS NOT DISTINCT FROM OLD.confirmed_by_id OR NEW.confirmed_by_id IS NULL)
           AND (NEW.cancelled_by_id IS NOT DISTINCT FROM OLD.cancelled_by_id OR NEW.cancelled_by_id IS NULL) THEN RETURN NEW; END IF;
        IF controlled THEN
        IF OLD.status IN ('draft','finance_locked','confirmed')
           AND NEW.status IN ('draft','finance_locked','confirmed','cancelled','reversed')
           AND ROW(NEW.company_id,NEW.asset_id,NEW.disposal_type,NEW.application_date,
                   NEW.planned_disposal_date,NEW.reason,NEW.description,NEW.previous_asset_status,
                   NEW.idempotency_key,NEW.created_at)
               IS NOT DISTINCT FROM
               ROW(OLD.company_id,OLD.asset_id,OLD.disposal_type,OLD.application_date,
                   OLD.planned_disposal_date,OLD.reason,OLD.description,OLD.previous_asset_status,
                   OLD.idempotency_key,OLD.created_at) THEN
            PERFORM set_config('eam_lite.controlled_asset_disposal_mutation','off',true);
            RETURN NEW;
        END IF;
        END IF;
    ELSIF TG_TABLE_NAME='assets_assetdisposalreversal' THEN
        IF OLD.reversed_by_id IS NOT NULL AND NEW.reversed_by_id IS NULL
           AND (to_jsonb(NEW)-'reversed_by_id')=(to_jsonb(OLD)-'reversed_by_id') THEN RETURN NEW; END IF;
    END IF;
    RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='lifecycle history is immutable outside the controlled service';
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_validate_lifecycle_write()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE capability text;
BEGIN
    capability := CASE TG_TABLE_NAME
        WHEN 'assets_assetloan' THEN 'eam_lite.controlled_asset_loan_mutation'
        WHEN 'assets_assetdisposal' THEN 'eam_lite.controlled_asset_disposal_mutation'
        ELSE 'eam_lite.controlled_asset_disposal_reversal_insert'
    END;
    IF COALESCE(current_setting(capability,true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='lifecycle record must be created by the controlled service';
    END IF;
    PERFORM set_config(capability,'off',true);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_validate_loan_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    a_company bigint; a_status varchar; m_company bigint; m_asset uuid; m_type varchar;
    emp_company bigint; emp_status varchar; emp_active boolean; current_loan_status varchar;
BEGIN
    SELECT status INTO current_loan_status FROM assets_assetloan WHERE id=NEW.id;
    IF current_loan_status IS DISTINCT FROM NEW.status THEN
        RETURN NULL;
    END IF;
    SELECT company_id,asset_status INTO a_company,a_status FROM assets_asset WHERE id=NEW.asset_id;
    IF a_company IS NULL OR a_company<>NEW.company_id THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='loan asset company mismatch'; END IF;
    SELECT company_id,asset_id,movement_type INTO m_company,m_asset,m_type FROM assets_assetmovement WHERE id=NEW.loan_movement_id;
    IF m_company<>NEW.company_id OR m_asset<>NEW.asset_id OR m_type<>'loan' THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='loan movement mismatch'; END IF;
    IF NEW.borrower_type='internal_employee' THEN
        SELECT company_id,employment_status,is_active INTO emp_company,emp_status,emp_active FROM masterdata_employee WHERE id=NEW.borrower_employee_id;
        IF emp_company<>NEW.company_id OR emp_status<>'active' OR NOT emp_active THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='internal borrower must be active in same company'; END IF;
    END IF;
    IF NEW.status='active' AND a_status<>'loaned' THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='active loan requires loaned asset'; END IF;
    IF NEW.status='returned' THEN
        SELECT company_id,asset_id,movement_type INTO m_company,m_asset,m_type FROM assets_assetmovement WHERE id=NEW.return_movement_id;
        IF m_company<>NEW.company_id OR m_asset<>NEW.asset_id OR m_type<>'loan_return' OR a_status<>NEW.return_asset_status THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='return movement or asset state mismatch'; END IF;
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_validate_disposal_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a_company bigint; a_status varchar; current_disposal_status varchar;
BEGIN
    SELECT status INTO current_disposal_status FROM assets_assetdisposal WHERE id=NEW.id;
    IF current_disposal_status IS DISTINCT FROM NEW.status THEN
        RETURN NULL;
    END IF;
    SELECT company_id,asset_status INTO a_company,a_status FROM assets_asset WHERE id=NEW.asset_id;
    IF a_company IS NULL OR a_company<>NEW.company_id THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='disposal asset company mismatch'; END IF;
    IF NEW.status IN ('draft','finance_locked') AND a_status<>'pending_disposal' THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='open disposal requires pending disposal asset'; END IF;
    IF NEW.status='confirmed' AND a_status<>(CASE NEW.disposal_type WHEN 'scrap' THEN 'disposed' WHEN 'sale' THEN 'sold' ELSE 'other_disposed' END) THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='confirmed disposal terminal status mismatch'; END IF;
    IF NEW.status='cancelled' AND a_status<>NEW.previous_asset_status THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='cancelled disposal must restore asset'; END IF;
    IF NEW.status='reversed' AND a_status<>NEW.previous_asset_status THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='reversed disposal must restore asset'; END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_validate_reversal_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE d_company bigint; d_status varchar; d_asset uuid; a_status varchar;
BEGIN
    SELECT company_id,status,asset_id INTO d_company,d_status,d_asset FROM assets_assetdisposal WHERE id=NEW.asset_disposal_id;
    SELECT asset_status INTO a_status FROM assets_asset WHERE id=d_asset;
    IF d_company IS NULL OR d_company<>NEW.company_id OR d_status<>'reversed' OR a_status<>NEW.restored_asset_status THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='disposal reversal references or restored state mismatch'; END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint7_validate_attachment_link()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_company bigint; attachment_company bigint; attachment_mime varchar;
    controlled boolean; actor_cleared boolean;
BEGIN
    IF num_nonnulls(NEW.asset_id,NEW.asset_disposal_id)<>1 THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment link requires exactly one target'; END IF;
    IF TG_OP='INSERT' AND NEW.status<>'active' THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment links must be created active'; END IF;
    IF TG_OP='UPDATE' THEN
        IF ROW(NEW.company_id,NEW.asset_id,NEW.asset_disposal_id,NEW.attachment_id,NEW.role,NEW.security_class)
           IS DISTINCT FROM ROW(OLD.company_id,OLD.asset_id,OLD.asset_disposal_id,OLD.attachment_id,OLD.role,OLD.security_class) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment link identity, role and security class are immutable; void and recreate';
        END IF;
        controlled := COALESCE(current_setting('eam_lite.controlled_asset_mutation',true),'')='on';
        actor_cleared := OLD.voided_by_id IS NOT NULL AND NEW.voided_by_id IS NULL
            AND (to_jsonb(NEW)-'voided_by_id')=(to_jsonb(OLD)-'voided_by_id');
        IF ROW(NEW.status,NEW.void_reason,NEW.voided_by_id,NEW.voided_at)
           IS DISTINCT FROM ROW(OLD.status,OLD.void_reason,OLD.voided_by_id,OLD.voided_at)
           AND NOT controlled AND NOT actor_cleared THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment link protected state must be changed by the controlled service';
        END IF;
        IF controlled AND ROW(NEW.status,NEW.void_reason,NEW.voided_by_id,NEW.voided_at)
           IS DISTINCT FROM ROW(OLD.status,OLD.void_reason,OLD.voided_by_id,OLD.voided_at) THEN
            PERFORM set_config('eam_lite.controlled_asset_mutation','off',true);
        END IF;
    END IF;
    IF NEW.asset_id IS NOT NULL THEN SELECT company_id INTO target_company FROM assets_asset WHERE id=NEW.asset_id;
    ELSE SELECT company_id INTO target_company FROM assets_assetdisposal WHERE id=NEW.asset_disposal_id; END IF;
    SELECT company_id,mime_type INTO attachment_company,attachment_mime FROM masterdata_attachment WHERE id=NEW.attachment_id;
    IF target_company IS NULL OR attachment_company IS NULL OR target_company<>NEW.company_id OR attachment_company<>NEW.company_id THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment link objects must be in same company'; END IF;
    IF NEW.role IN ('cover','photo') AND attachment_mime NOT LIKE 'image/%%' THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset cover and photo roles require an image attachment'; END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_validate_asset_references()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    category_company bigint; category_active boolean;
    department_company bigint; department_active boolean;
    employee_company bigint; employee_department bigint; employee_status varchar;
    employee_active boolean; employee_department_active boolean;
    location_company bigint; location_active boolean;
    scheme_company bigint; scheme_status varchar; scheme_from date; scheme_to date;
    shanghai_today date;
    controlled_mutation boolean; actor_cleared boolean;
BEGIN
    IF TG_OP='INSERT' AND NEW.asset_status<>'draft' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='assets must be created as drafts';
    END IF;
    IF TG_OP='UPDATE' THEN
        controlled_mutation := COALESCE(current_setting('eam_lite.controlled_asset_mutation',true),'')='on';
        actor_cleared := OLD.submitted_by_id IS NOT NULL AND NEW.submitted_by_id IS NULL
            AND ROW(NEW.asset_status,NEW.record_status,NEW.asset_code,NEW.current_issued_code_id,
                    NEW.requested_coding_scheme_id,NEW.submitted_at,NEW.department_id,
                    NEW.responsible_employee_id,NEW.location_id)
                IS NOT DISTINCT FROM
                ROW(OLD.asset_status,OLD.record_status,OLD.asset_code,OLD.current_issued_code_id,
                    OLD.requested_coding_scheme_id,OLD.submitted_at,OLD.department_id,
                    OLD.responsible_employee_id,OLD.location_id);
        IF ROW(NEW.asset_status,NEW.record_status,NEW.asset_code,NEW.current_issued_code_id,
               NEW.requested_coding_scheme_id,NEW.submitted_by_id,NEW.submitted_at,
               NEW.department_id,NEW.responsible_employee_id,NEW.location_id)
           IS DISTINCT FROM
           ROW(OLD.asset_status,OLD.record_status,OLD.asset_code,OLD.current_issued_code_id,
               OLD.requested_coding_scheme_id,OLD.submitted_by_id,OLD.submitted_at,
               OLD.department_id,OLD.responsible_employee_id,OLD.location_id)
           AND NOT controlled_mutation AND NOT actor_cleared THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset protected state must be changed by controlled service';
        END IF;
        IF controlled_mutation AND ROW(NEW.asset_status,NEW.record_status,NEW.asset_code,
               NEW.current_issued_code_id,NEW.requested_coding_scheme_id,NEW.submitted_by_id,
               NEW.submitted_at,NEW.department_id,NEW.responsible_employee_id,NEW.location_id)
           IS DISTINCT FROM ROW(OLD.asset_status,OLD.record_status,OLD.asset_code,
               OLD.current_issued_code_id,OLD.requested_coding_scheme_id,OLD.submitted_by_id,
               OLD.submitted_at,OLD.department_id,OLD.responsible_employee_id,OLD.location_id) THEN
            PERFORM set_config('eam_lite.controlled_asset_mutation','off',true);
        END IF;
        IF NEW.asset_status IS DISTINCT FROM OLD.asset_status AND NOT (
            (OLD.asset_status='draft' AND NEW.asset_status='pending_finance')
            OR (OLD.asset_status='pending_finance' AND NEW.asset_status='draft')
            OR (OLD.asset_status='pending_finance' AND NEW.asset_status='pending_label')
            OR (OLD.asset_status='pending_label' AND NEW.asset_status IN ('in_use','idle'))
            OR (OLD.asset_status='in_use' AND NEW.asset_status IN ('idle','loaned','under_repair','pending_disposal'))
            OR (OLD.asset_status='idle' AND NEW.asset_status IN ('in_use','loaned','under_repair','pending_disposal'))
            OR (OLD.asset_status='loaned' AND NEW.asset_status IN ('in_use','idle'))
            OR (OLD.asset_status='under_repair' AND NEW.asset_status IN ('in_use','idle','pending_disposal'))
            OR (OLD.asset_status='pending_disposal' AND NEW.asset_status IN ('in_use','idle','under_repair','disposed','sold','other_disposed'))
            OR (OLD.asset_status IN ('disposed','sold','other_disposed') AND NEW.asset_status IN ('in_use','idle','under_repair'))
        ) THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset status transition is not approved'; END IF;
        IF NEW.record_status IS DISTINCT FROM OLD.record_status
           AND (NEW.asset_status NOT IN ('disposed','sold','other_disposed')
                OR OLD.asset_status NOT IN ('disposed','sold','other_disposed')) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='only terminal assets can be archived or restored';
        END IF;
        IF OLD.asset_status NOT IN ('draft','pending_finance')
           AND ROW(NEW.asset_code,NEW.current_issued_code_id,NEW.requested_coding_scheme_id)
               IS DISTINCT FROM ROW(OLD.asset_code,OLD.current_issued_code_id,OLD.requested_coding_scheme_id)
           AND NOT controlled_mutation THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='formal asset coding can only change through controlled correction';
        END IF;
    END IF;
    SELECT company_id,is_active INTO category_company,category_active FROM masterdata_assetcategory WHERE id=NEW.category_id FOR SHARE;
    IF category_company IS NULL OR category_company<>NEW.company_id OR NOT category_active THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset category must be active in same company'; END IF;
    IF NEW.department_id IS NOT NULL THEN
        SELECT company_id,is_active INTO department_company,department_active FROM masterdata_department WHERE id=NEW.department_id FOR SHARE;
        IF department_company<>NEW.company_id OR NOT department_active THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset department must be active in same company'; END IF;
    END IF;
    IF NEW.responsible_employee_id IS NOT NULL THEN
        SELECT e.company_id,e.department_id,e.employment_status,e.is_active,d.is_active
          INTO employee_company,employee_department,employee_status,employee_active,employee_department_active
          FROM masterdata_employee e JOIN masterdata_department d ON d.id=e.department_id
         WHERE e.id=NEW.responsible_employee_id FOR SHARE OF e,d;
        IF employee_company<>NEW.company_id OR employee_department<>NEW.department_id
           OR employee_status<>'active' OR NOT employee_active OR NOT employee_department_active THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='responsible employee must be active in asset department';
        END IF;
    END IF;
    IF NEW.location_id IS NOT NULL THEN
        SELECT company_id,is_active INTO location_company,location_active FROM masterdata_location WHERE id=NEW.location_id FOR SHARE;
        IF location_company<>NEW.company_id OR NOT location_active THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset location must be active in same company'; END IF;
    END IF;
    IF NEW.requested_coding_scheme_id IS NOT NULL THEN
        SELECT company_id,status,effective_from,effective_to
          INTO scheme_company,scheme_status,scheme_from,scheme_to
          FROM masterdata_assetcodingscheme WHERE id=NEW.requested_coding_scheme_id;
        shanghai_today := (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai')::date;
        IF scheme_company IS NULL OR scheme_company<>NEW.company_id OR scheme_status<>'active'
           OR scheme_from>shanghai_today OR (scheme_to IS NOT NULL AND scheme_to<shanghai_today) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='requested coding scheme must be current and in the same company';
        END IF;
    END IF;
    IF TG_OP='UPDATE' AND NEW.category_id IS DISTINCT FROM OLD.category_id
       AND EXISTS (
           SELECT 1 FROM assets_assetcustomvalue value
           JOIN assets_assetcustomfield field ON field.id=value.custom_field_id
           WHERE value.asset_id=NEW.id AND field.category_id<>NEW.category_id
       ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='remove or migrate incompatible custom values before changing category';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_assets_movement_validate ON assets_assetmovement;
CREATE TRIGGER trg_assets_movement_validate BEFORE INSERT ON assets_assetmovement FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_movement();
DROP TRIGGER IF EXISTS trg_assets_movement_commit ON assets_assetmovement;
CREATE CONSTRAINT TRIGGER trg_assets_movement_commit AFTER INSERT ON assets_assetmovement DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_movement_commit();
DROP TRIGGER IF EXISTS trg_assets_loan_history ON assets_assetloan;
CREATE TRIGGER trg_assets_loan_history BEFORE UPDATE OR DELETE ON assets_assetloan FOR EACH ROW EXECUTE FUNCTION assets_sprint7_guard_history();
DROP TRIGGER IF EXISTS trg_assets_loan_insert ON assets_assetloan;
CREATE TRIGGER trg_assets_loan_insert BEFORE INSERT ON assets_assetloan FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_lifecycle_write();
DROP TRIGGER IF EXISTS trg_assets_loan_commit ON assets_assetloan;
CREATE CONSTRAINT TRIGGER trg_assets_loan_commit AFTER INSERT OR UPDATE ON assets_assetloan DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_loan_commit();
DROP TRIGGER IF EXISTS trg_assets_disposal_history ON assets_assetdisposal;
CREATE TRIGGER trg_assets_disposal_history BEFORE UPDATE OR DELETE ON assets_assetdisposal FOR EACH ROW EXECUTE FUNCTION assets_sprint7_guard_history();
DROP TRIGGER IF EXISTS trg_assets_disposal_insert ON assets_assetdisposal;
CREATE TRIGGER trg_assets_disposal_insert BEFORE INSERT ON assets_assetdisposal FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_lifecycle_write();
DROP TRIGGER IF EXISTS trg_assets_disposal_commit ON assets_assetdisposal;
CREATE CONSTRAINT TRIGGER trg_assets_disposal_commit AFTER INSERT OR UPDATE ON assets_assetdisposal DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_disposal_commit();
DROP TRIGGER IF EXISTS trg_assets_reversal_history ON assets_assetdisposalreversal;
CREATE TRIGGER trg_assets_reversal_history BEFORE UPDATE OR DELETE ON assets_assetdisposalreversal FOR EACH ROW EXECUTE FUNCTION assets_sprint7_guard_history();
DROP TRIGGER IF EXISTS trg_assets_reversal_insert ON assets_assetdisposalreversal;
CREATE TRIGGER trg_assets_reversal_insert BEFORE INSERT ON assets_assetdisposalreversal FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_lifecycle_write();
DROP TRIGGER IF EXISTS trg_assets_reversal_commit ON assets_assetdisposalreversal;
CREATE CONSTRAINT TRIGGER trg_assets_reversal_commit AFTER INSERT ON assets_assetdisposalreversal DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_reversal_commit();
DROP TRIGGER IF EXISTS trg_attachment_link_validate ON assets_attachmentlink;
CREATE TRIGGER trg_attachment_link_validate BEFORE INSERT OR UPDATE ON assets_attachmentlink FOR EACH ROW EXECUTE FUNCTION assets_sprint7_validate_attachment_link();
DROP TRIGGER IF EXISTS trg_asset_references ON assets_asset;
CREATE TRIGGER trg_asset_references BEFORE INSERT OR UPDATE ON assets_asset FOR EACH ROW EXECUTE FUNCTION assets_validate_asset_references();
"""

ASSET_GUARDS_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS trg_assets_reversal_commit ON assets_assetdisposalreversal;
DROP TRIGGER IF EXISTS trg_assets_reversal_insert ON assets_assetdisposalreversal;
DROP TRIGGER IF EXISTS trg_assets_reversal_history ON assets_assetdisposalreversal;
DROP TRIGGER IF EXISTS trg_assets_disposal_commit ON assets_assetdisposal;
DROP TRIGGER IF EXISTS trg_assets_disposal_insert ON assets_assetdisposal;
DROP TRIGGER IF EXISTS trg_assets_disposal_history ON assets_assetdisposal;
DROP TRIGGER IF EXISTS trg_assets_loan_commit ON assets_assetloan;
DROP TRIGGER IF EXISTS trg_assets_loan_insert ON assets_assetloan;
DROP TRIGGER IF EXISTS trg_assets_loan_history ON assets_assetloan;
DROP TRIGGER IF EXISTS trg_assets_movement_commit ON assets_assetmovement;
DROP TRIGGER IF EXISTS trg_assets_movement_validate ON assets_assetmovement;
DROP FUNCTION IF EXISTS assets_sprint7_validate_attachment_link();
DROP FUNCTION IF EXISTS assets_sprint7_validate_reversal_commit();
DROP FUNCTION IF EXISTS assets_sprint7_validate_disposal_commit();
DROP FUNCTION IF EXISTS assets_sprint7_validate_loan_commit();
DROP FUNCTION IF EXISTS assets_sprint7_validate_lifecycle_write();
DROP FUNCTION IF EXISTS assets_sprint7_guard_history();
DROP FUNCTION IF EXISTS assets_sprint7_validate_movement_commit();
DROP FUNCTION IF EXISTS assets_sprint7_validate_movement();
"""


def install_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(ASSET_GUARDS_SQL)


def remove_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(ASSET_GUARDS_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_sprint6_label_attachment_idempotency'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disposal_type', models.CharField(choices=[('scrap', '报废'), ('sale', '出售'), ('other', '其他处置')], max_length=16, verbose_name='处置类型')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('planned_disposal_date', models.DateField(verbose_name='拟处置日期')),
                ('actual_disposal_date', models.DateField(blank=True, null=True, verbose_name='实际处置日期')),
                ('reason', models.TextField(verbose_name='处置原因')),
                ('description', models.TextField(blank=True, verbose_name='处置说明')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='接收方/去向')),
                ('disposal_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='处置收入')),
                ('original_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='原值快照')),
                ('actual_accumulated_depreciation_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='实际累计折旧快照')),
                ('impairment_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='减值快照')),
                ('book_value_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='账面净值快照')),
                ('previous_asset_status', models.CharField(max_length=32, verbose_name='处置前资产状态')),
                ('status', models.CharField(choices=[('draft', '处理中'), ('finance_locked', '财务已锁定'), ('confirmed', '已完成'), ('cancelled', '已取消'), ('reversed', '已冲销')], default='draft', max_length=16, verbose_name='处置状态')),
                ('finance_locked_at', models.DateTimeField(blank=True, null=True, verbose_name='财务锁定时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='取消原因')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='发起幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产处置',
                'verbose_name_plural': '资产处置',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetDisposalReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='冲销原因')),
                ('restored_asset_status', models.CharField(max_length=32, verbose_name='恢复资产状态')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='冲销幂等键')),
                ('reversed_at', models.DateTimeField(verbose_name='冲销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产处置冲销',
                'verbose_name_plural': '资产处置冲销',
                'ordering': ('-reversed_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_type', models.CharField(choices=[('internal_employee', '内部员工'), ('external', '外部借用方')], max_length=32, verbose_name='借用方类型')),
                ('borrower_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='内部借用人姓名快照')),
                ('borrower_name', models.CharField(blank=True, max_length=200, verbose_name='外部借用人')),
                ('borrower_organization', models.CharField(blank=True, max_length=200, verbose_name='外部借用单位')),
                ('loan_date', models.DateField(verbose_name='借出日期')),
                ('expected_return_date', models.DateField(verbose_name='预计归还日期')),
                ('previous_asset_status', models.CharField(max_length=32, verbose_name='借出前状态')),
                ('reason', models.TextField(verbose_name='借出原因')),
                ('status', models.CharField(choices=[('active', '借出中'), ('returned', '已归还')], default='active', max_length=16, verbose_name='借用状态')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('return_asset_status', models.CharField(blank=True, max_length=32, verbose_name='归还后状态')),
                ('return_remark', models.TextField(blank=True, verbose_name='归还备注')),
                ('loan_idempotency_key', models.CharField(max_length=128, verbose_name='借出幂等键')),
                ('return_idempotency_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='归还幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产借用',
                'verbose_name_plural': '资产借用',
                'ordering': ('-loan_date', '-created_at'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='assetmovement',
            name='ck_movement_sprint6_type',
        ),
        migrations.RemoveConstraint(
            model_name='assetmovement',
            name='ck_movement_label_same_department',
        ),
        migrations.RemoveConstraint(
            model_name='assetmovement',
            name='ck_movement_label_same_employee',
        ),
        migrations.RemoveConstraint(
            model_name='assetmovement',
            name='ck_movement_label_same_location',
        ),
        migrations.RemoveConstraint(
            model_name='assetmovement',
            name='ck_movement_label_activation_fields',
        ),
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_role',
        ),
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_role_security',
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_type',
            field=models.CharField(choices=[('assignment', '领用'), ('assignment_return', '领用归还'), ('transfer', '调拨/责任位置变更'), ('loan', '借出'), ('loan_return', '借出归还'), ('idle', '闲置'), ('activate', '启用'), ('repair_start', '送修'), ('repair_complete', '维修完成'), ('label_activation', '首次贴标启用'), ('disposal_start', '发起处置'), ('disposal_cancel', '取消处置'), ('disposal_complete', '完成处置'), ('disposal_reversal', '处置冲销')], max_length=32, verbose_name='变动类型'),
        ),
        migrations.AlterField(
            model_name='attachmentlink',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='attachmentlink',
            name='role',
            field=models.CharField(choices=[('cover', '封面照片'), ('photo', '资产照片'), ('invoice', '发票'), ('contract', '合同'), ('acceptance', '验收单'), ('certificate', '合格证'), ('manual', '说明书'), ('disposal', '处置证据'), ('other', '其他')], max_length=32, verbose_name='附件用途'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ('assignment', 'assignment_return', 'transfer', 'loan', 'loan_return', 'idle', 'activate', 'repair_start', 'repair_complete', 'label_activation', 'disposal_start', 'disposal_cancel', 'disposal_complete', 'disposal_reversal'))), name='ck_movement_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_department', models.F('to_department')), _negated=True), models.Q(('from_employee', models.F('to_employee')), _negated=True), models.Q(('from_location', models.F('to_location')), _negated=True), models.Q(('from_status', models.F('to_status')), _negated=True), _connector='OR'), name='ck_movement_has_change'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'label_activation'), _negated=True), models.Q(('from_department__isnull', False), ('from_employee__isnull', False), ('from_location__isnull', False), ('from_status', 'pending_label'), ('movement_type', 'label_activation'), ('to_department__isnull', False), ('to_employee__isnull', False), ('to_location__isnull', False), ('to_status__in', ('in_use', 'idle'))), _connector='OR'), name='ck_movement_label_activation_fields'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='取消人'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposals', to='masterdata.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='完成人'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='finance_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_locked_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='财务锁定人'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='处置经办人'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.AddField(
            model_name='attachmentlink',
            name='asset_disposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='assets.assetdisposal', verbose_name='资产处置'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('asset_disposal__isnull', True)), models.Q(('asset__isnull', True), ('asset_disposal__isnull', False)), _connector='OR'), name='ck_attachment_link_one_target'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('cover', 'photo', 'invoice', 'contract', 'acceptance', 'certificate', 'manual', 'disposal', 'other'))), name='ck_attachment_link_role'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ('cover', 'photo', 'certificate', 'manual')), ('security_class', 'A0')), models.Q(('role__in', ('invoice', 'contract', 'acceptance')), ('security_class', 'A1')), models.Q(('role', 'disposal'), ('security_class__in', ('A0', 'A1'))), models.Q(('role', 'other'), ('security_class__in', ('A0', 'A1'))), _connector='OR'), name='ck_attachment_link_role_security'),
        ),
        migrations.AddField(
            model_name='assetdisposalreversal',
            name='asset_disposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='assets.assetdisposal', verbose_name='原处置'),
        ),
        migrations.AddField(
            model_name='assetdisposalreversal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposal_reversals', to='masterdata.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='assetdisposalreversal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='冲销人'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='assets.asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='borrower_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_asset_loans', to='masterdata.employee', verbose_name='内部借用员工'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_loans', to='masterdata.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_loans', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_asset_loans', to=settings.AUTH_USER_MODEL, verbose_name='借出经办人'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='loan_movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_record', to='assets.assetmovement', verbose_name='借出变动'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='received_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_asset_loan_returns', to='masterdata.employee', verbose_name='归还接收人'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='return_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_loan_returns', to='masterdata.department', verbose_name='归还部门'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='return_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_loan_returns', to='masterdata.location', verbose_name='归还位置'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='return_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_return_record', to='assets.assetmovement', verbose_name='归还变动'),
        ),
        migrations.AddField(
            model_name='assetloan',
            name='return_responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_asset_loan_returns', to='masterdata.employee', verbose_name='归还后责任人'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_disposal_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'finance_locked'))), fields=('asset',), name='uq_disposal_asset_open'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('asset',), name='uq_disposal_asset_confirmed'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(('disposal_type__in', ('scrap', 'sale', 'other'))), name='ck_disposal_type'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'finance_locked', 'confirmed', 'cancelled', 'reversed'))), name='ck_disposal_status'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(('planned_disposal_date__gte', models.F('application_date'))), name='ck_disposal_planned_date'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(('actual_disposal_date__isnull', True), ('actual_disposal_date__gte', models.F('application_date')), _connector='OR'), name='ck_disposal_actual_date'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('disposal_income__isnull', True), ('disposal_income__gte', 0), _connector='OR'), models.Q(('original_cost_snapshot__isnull', True), ('original_cost_snapshot__gte', 0), _connector='OR'), models.Q(('actual_accumulated_depreciation_snapshot__isnull', True), ('actual_accumulated_depreciation_snapshot__gte', 0), _connector='OR'), models.Q(('impairment_snapshot__isnull', True), ('impairment_snapshot__gte', 0), _connector='OR'), models.Q(('book_value_snapshot__isnull', True), ('book_value_snapshot__gte', 0), _connector='OR')), name='ck_disposal_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_accumulated_depreciation_snapshot__isnull', True), ('book_value_snapshot__isnull', True), ('impairment_snapshot__isnull', True), ('original_cost_snapshot__isnull', True)), ('original_cost_snapshot', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('actual_accumulated_depreciation_snapshot'), '+', models.F('impairment_snapshot')), '+', models.F('book_value_snapshot'))), _connector='OR'), name='ck_disposal_snapshot_reconciles'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_accumulated_depreciation_snapshot__isnull', True), ('book_value_snapshot__isnull', True), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('finance_locked_at__isnull', True), ('finance_locked_by__isnull', True), ('impairment_snapshot__isnull', True), ('original_cost_snapshot__isnull', True), ('status', 'draft')), models.Q(('actual_accumulated_depreciation_snapshot__isnull', False), ('actual_disposal_date__isnull', False), ('book_value_snapshot__isnull', False), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('disposal_income__isnull', False), ('finance_locked_at__isnull', False), ('impairment_snapshot__isnull', False), ('original_cost_snapshot__isnull', False), ('status', 'finance_locked')), models.Q(('actual_accumulated_depreciation_snapshot__isnull', False), ('actual_disposal_date__isnull', False), ('book_value_snapshot__isnull', False), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('confirmed_at__isnull', False), ('disposal_income__isnull', False), ('finance_locked_at__isnull', False), ('impairment_snapshot__isnull', False), ('original_cost_snapshot__isnull', False), ('status__in', ('confirmed', 'reversed'))), models.Q(('cancelled_at__isnull', False), ('confirmed_at__isnull', True), ('confirmed_by__isnull', True), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='ck_disposal_status_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(('previous_asset_status__in', ('in_use', 'idle', 'under_repair'))), name='ck_disposal_previous_status'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_disposal_required_text'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposalreversal',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_disposal_reversal_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposalreversal',
            constraint=models.CheckConstraint(condition=models.Q(('restored_asset_status__in', ('in_use', 'idle', 'under_repair'))), name='ck_disposal_reversal_status'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposalreversal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_disposal_reversal_required_text'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('asset',), name='uq_asset_loan_active_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.UniqueConstraint(fields=('company', 'loan_idempotency_key'), name='uq_asset_loan_company_loan_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.UniqueConstraint(condition=models.Q(('return_idempotency_key__isnull', False)), fields=('company', 'return_idempotency_key'), name='uq_asset_loan_company_return_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(('borrower_type__in', ('internal_employee', 'external'))), name='ck_asset_loan_borrower_type'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'returned'))), name='ck_asset_loan_status'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('borrower_employee__isnull', False), ('borrower_name', ''), ('borrower_name_snapshot__gt', ''), ('borrower_organization', ''), ('borrower_type', 'internal_employee')), models.Q(('borrower_employee__isnull', True), ('borrower_name__gt', ''), ('borrower_name_snapshot', ''), ('borrower_type', 'external')), _connector='OR'), name='ck_asset_loan_borrower_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(('expected_return_date__gte', models.F('loan_date'))), name='ck_asset_loan_expected_date'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(('previous_asset_status__in', ('in_use', 'idle'))), name='ck_asset_loan_previous_status'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('received_by_employee__isnull', True), ('return_asset_status', ''), ('return_department__isnull', True), ('return_idempotency_key__isnull', True), ('return_location__isnull', True), ('return_movement__isnull', True), ('return_responsible_employee__isnull', True), ('returned_at__isnull', True), ('status', 'active')), models.Q(('received_by_employee__isnull', False), ('return_asset_status__in', ('in_use', 'idle')), ('return_department__isnull', False), ('return_idempotency_key__isnull', False), ('return_location__isnull', False), ('return_movement__isnull', False), ('return_responsible_employee__isnull', False), ('returned_at__isnull', False), ('status', 'returned')), _connector='OR'), name='ck_asset_loan_return_fields'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(('return_movement__isnull', True), models.Q(('loan_movement', models.F('return_movement')), _negated=True), _connector='OR'), name='ck_asset_loan_movements_different'),
        ),
        migrations.AddConstraint(
            model_name='assetloan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loan_idempotency_key', ''), _negated=True), models.Q(('reason', ''), _negated=True)), name='ck_asset_loan_required_text'),
        ),
        migrations.RunPython(
            install_postgresql_guards,
            reverse_code=remove_postgresql_guards,
        ),
    ]
