# Generated by Django 5.2.17 on 2026-08-13 05:14

import django.db.models.deletion
import importlib
from django.conf import settings
from django.db import migrations, models


ATTACHMENT_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION assets_sprint7_validate_attachment_link()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_company bigint; attachment_company bigint; attachment_mime varchar;
    controlled boolean; actor_cleared boolean;
BEGIN
    IF num_nonnulls(
        NEW.asset_id,NEW.asset_disposal_id,NEW.inventory_surplus_id,
        NEW.inventory_scan_id,NEW.inventory_resolution_id,
        NEW.maintenance_record_id,NEW.maintenance_problem_id
    )<>1 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment link requires exactly one target';
    END IF;
    IF TG_OP='INSERT' AND NEW.status<>'active' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment links must be created active';
    END IF;
    IF TG_OP='UPDATE' THEN
        IF ROW(NEW.company_id,NEW.asset_id,NEW.asset_disposal_id,NEW.inventory_surplus_id,
               NEW.inventory_scan_id,NEW.inventory_resolution_id,NEW.maintenance_record_id,
               NEW.maintenance_problem_id,NEW.attachment_id,NEW.role,NEW.security_class)
           IS DISTINCT FROM
           ROW(OLD.company_id,OLD.asset_id,OLD.asset_disposal_id,OLD.inventory_surplus_id,
               OLD.inventory_scan_id,OLD.inventory_resolution_id,OLD.maintenance_record_id,
               OLD.maintenance_problem_id,OLD.attachment_id,OLD.role,OLD.security_class) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment link identity is immutable';
        END IF;
        controlled := COALESCE(current_setting('eam_lite.controlled_asset_mutation',true),'')='on';
        actor_cleared := OLD.voided_by_id IS NOT NULL AND NEW.voided_by_id IS NULL
            AND (to_jsonb(NEW)-'voided_by_id')=(to_jsonb(OLD)-'voided_by_id');
        IF ROW(NEW.status,NEW.void_reason,NEW.voided_by_id,NEW.voided_at)
           IS DISTINCT FROM ROW(OLD.status,OLD.void_reason,OLD.voided_by_id,OLD.voided_at)
           AND NOT controlled AND NOT actor_cleared THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment state requires controlled service';
        END IF;
        IF controlled AND ROW(NEW.status,NEW.void_reason,NEW.voided_by_id,NEW.voided_at)
           IS DISTINCT FROM ROW(OLD.status,OLD.void_reason,OLD.voided_by_id,OLD.voided_at) THEN
            PERFORM set_config('eam_lite.controlled_asset_mutation','off',true);
        END IF;
    END IF;
    IF NEW.asset_id IS NOT NULL THEN SELECT company_id INTO target_company FROM assets_asset WHERE id=NEW.asset_id;
    ELSIF NEW.asset_disposal_id IS NOT NULL THEN SELECT company_id INTO target_company FROM assets_assetdisposal WHERE id=NEW.asset_disposal_id;
    ELSIF NEW.inventory_surplus_id IS NOT NULL THEN SELECT company_id INTO target_company FROM inventory_inventorysurplus WHERE id=NEW.inventory_surplus_id;
    ELSIF NEW.inventory_scan_id IS NOT NULL THEN SELECT company_id INTO target_company FROM inventory_inventoryscan WHERE id=NEW.inventory_scan_id;
    ELSIF NEW.inventory_resolution_id IS NOT NULL THEN SELECT company_id INTO target_company FROM inventory_inventoryresolution WHERE id=NEW.inventory_resolution_id;
    ELSIF NEW.maintenance_record_id IS NOT NULL THEN SELECT company_id INTO target_company FROM maintenance_maintenancerecord WHERE id=NEW.maintenance_record_id;
    ELSE SELECT company_id INTO target_company FROM maintenance_maintenanceproblem WHERE id=NEW.maintenance_problem_id;
    END IF;
    SELECT company_id,mime_type INTO attachment_company,attachment_mime
      FROM masterdata_attachment WHERE id=NEW.attachment_id;
    IF target_company IS NULL OR attachment_company IS NULL OR target_company<>NEW.company_id
       OR attachment_company<>NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='attachment objects must be in same company';
    END IF;
    IF NEW.role IN ('cover','photo','surplus_evidence') AND attachment_mime NOT LIKE 'image/%%' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='photo evidence requires image attachment';
    END IF;
    IF NEW.inventory_surplus_id IS NOT NULL AND NEW.role NOT IN ('surplus_evidence','other') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid inventory surplus attachment role';
    END IF;
    IF (NEW.inventory_scan_id IS NOT NULL OR NEW.inventory_resolution_id IS NOT NULL)
       AND NEW.role NOT IN ('inventory_evidence','other') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid inventory evidence attachment role';
    END IF;
    IF (NEW.maintenance_record_id IS NOT NULL OR NEW.maintenance_problem_id IS NOT NULL)
       AND NEW.role<>'maintenance' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid maintenance attachment role';
    END IF;
    RETURN NEW;
END;
$$;
"""


def install_postgresql_attachment_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(ATTACHMENT_GUARDS_SQL)


def restore_postgresql_attachment_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        previous = importlib.import_module(
            "apps.assets.migrations.0009_remove_attachmentlink_ck_attachment_link_one_target_and_more"
        )
        schema_editor.execute(previous.ATTACHMENT_GUARDS_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_attachmentlink_ck_attachment_link_one_target_and_more'),
        ('inventory', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_role',
        ),
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_role_security',
        ),
        migrations.AddField(
            model_name='attachmentlink',
            name='maintenance_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='maintenance.maintenanceproblem', verbose_name='保养问题'),
        ),
        migrations.AddField(
            model_name='attachmentlink',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='maintenance.maintenancerecord', verbose_name='保养记录'),
        ),
        migrations.AlterField(
            model_name='attachmentlink',
            name='role',
            field=models.CharField(choices=[('cover', '封面照片'), ('photo', '资产照片'), ('invoice', '发票'), ('contract', '合同'), ('acceptance', '验收单'), ('certificate', '合格证'), ('manual', '说明书'), ('disposal', '处置证据'), ('surplus_evidence', '盘盈证据'), ('inventory_evidence', '盘点证据'), ('maintenance', '保养附件'), ('other', '其他')], max_length=32, verbose_name='附件用途'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('asset_disposal__isnull', True), ('inventory_resolution__isnull', True), ('inventory_scan__isnull', True), ('inventory_surplus__isnull', True), ('maintenance_problem__isnull', True), ('maintenance_record__isnull', True)), models.Q(('asset__isnull', True), ('asset_disposal__isnull', False), ('inventory_resolution__isnull', True), ('inventory_scan__isnull', True), ('inventory_surplus__isnull', True), ('maintenance_problem__isnull', True), ('maintenance_record__isnull', True)), models.Q(('asset__isnull', True), ('asset_disposal__isnull', True), ('inventory_resolution__isnull', True), ('inventory_scan__isnull', True), ('inventory_surplus__isnull', False), ('maintenance_problem__isnull', True), ('maintenance_record__isnull', True)), models.Q(('asset__isnull', True), ('asset_disposal__isnull', True), ('inventory_resolution__isnull', True), ('inventory_scan__isnull', False), ('inventory_surplus__isnull', True), ('maintenance_problem__isnull', True), ('maintenance_record__isnull', True)), models.Q(('asset__isnull', True), ('asset_disposal__isnull', True), ('inventory_resolution__isnull', False), ('inventory_scan__isnull', True), ('inventory_surplus__isnull', True), ('maintenance_problem__isnull', True), ('maintenance_record__isnull', True)), models.Q(('asset__isnull', True), ('asset_disposal__isnull', True), ('inventory_resolution__isnull', True), ('inventory_scan__isnull', True), ('inventory_surplus__isnull', True), ('maintenance_problem__isnull', True), ('maintenance_record__isnull', False)), models.Q(('asset__isnull', True), ('asset_disposal__isnull', True), ('inventory_resolution__isnull', True), ('inventory_scan__isnull', True), ('inventory_surplus__isnull', True), ('maintenance_problem__isnull', False), ('maintenance_record__isnull', True)), _connector='OR'), name='ck_attachment_link_one_target'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('cover', 'photo', 'invoice', 'contract', 'acceptance', 'certificate', 'manual', 'disposal', 'surplus_evidence', 'inventory_evidence', 'maintenance', 'other'))), name='ck_attachment_link_role'),
        ),
        migrations.AddConstraint(
            model_name='attachmentlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ('cover', 'photo', 'certificate', 'manual')), ('security_class', 'A0')), models.Q(('role__in', ('invoice', 'contract', 'acceptance')), ('security_class', 'A1')), models.Q(('role', 'disposal'), ('security_class__in', ('A0', 'A1'))), models.Q(('role', 'surplus_evidence'), ('security_class', 'A0')), models.Q(('role', 'inventory_evidence'), ('security_class', 'A0')), models.Q(('role', 'maintenance'), ('security_class__in', ('A0', 'A1'))), models.Q(('role', 'other'), ('security_class__in', ('A0', 'A1'))), _connector='OR'), name='ck_attachment_link_role_security'),
        ),
        migrations.RunPython(
            install_postgresql_attachment_guards,
            reverse_code=restore_postgresql_attachment_guards,
        ),
    ]
