# Generated by Django 5.2.17 on 2026-08-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_remove_attachmentlink_ck_attachment_link_one_target_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_role',
        ),
        migrations.RemoveConstraint(
            model_name='attachmentlink',
            name='ck_attachment_link_role_security',
        ),
    ]
