# Generated by Django 5.2.17 on 2026-08-13 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


POSTGRESQL_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION assets_sprint11_guard_external_reference()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    controlled boolean;
    actor_cleared boolean;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset external references cannot be deleted';
    END IF;
    IF TG_OP = 'INSERT' THEN
        RETURN NEW;
    END IF;

    actor_cleared := OLD.created_by_id IS NOT NULL
        AND NEW.created_by_id IS NULL
        AND (to_jsonb(NEW) - 'created_by_id') = (to_jsonb(OLD) - 'created_by_id');
    IF actor_cleared THEN
        RETURN NEW;
    END IF;

    controlled := COALESCE(
        current_setting('eam_lite.controlled_external_reference_mutation', true), ''
    ) = 'on';
    IF NOT controlled THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='external reference update requires controlled service';
    END IF;
    IF ROW(
        NEW.id, NEW.company_id, NEW.asset_id, NEW.external_system, NEW.reference_type,
        NEW.created_by_id, NEW.created_at
    ) IS DISTINCT FROM ROW(
        OLD.id, OLD.company_id, OLD.asset_id, OLD.external_system, OLD.reference_type,
        OLD.created_by_id, OLD.created_at
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='external reference identity is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assets_sprint11_validate_external_reference_company()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    asset_company bigint;
BEGIN
    SELECT company_id INTO asset_company FROM assets_asset WHERE id = NEW.asset_id;
    IF asset_company IS NULL OR asset_company <> NEW.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='external reference asset must be in same company';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_assets_external_reference_guard
    ON assets_assetexternalreference;
CREATE TRIGGER trg_assets_external_reference_guard
BEFORE INSERT OR UPDATE OR DELETE ON assets_assetexternalreference
FOR EACH ROW EXECUTE FUNCTION assets_sprint11_guard_external_reference();

DROP TRIGGER IF EXISTS trg_assets_external_reference_company
    ON assets_assetexternalreference;
CREATE CONSTRAINT TRIGGER trg_assets_external_reference_company
AFTER INSERT OR UPDATE ON assets_assetexternalreference
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION assets_sprint11_validate_external_reference_company();
"""

POSTGRESQL_GUARDS_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS trg_assets_external_reference_company
    ON assets_assetexternalreference;
DROP TRIGGER IF EXISTS trg_assets_external_reference_guard
    ON assets_assetexternalreference;
DROP FUNCTION IF EXISTS assets_sprint11_validate_external_reference_company();
DROP FUNCTION IF EXISTS assets_sprint11_guard_external_reference();
"""


def install_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(POSTGRESQL_GUARDS_SQL)


def remove_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(POSTGRESQL_GUARDS_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_attachmentlink_clearance_and_more'),
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetExternalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_system', models.CharField(choices=[('TPLUS', '用友 T+')], max_length=32, verbose_name='外部系统')),
                ('reference_type', models.CharField(choices=[('asset_card_code', 'T+ 资产卡片编码')], max_length=32, verbose_name='引用类型')),
                ('reference_value', models.CharField(max_length=128, verbose_name='外部编码')),
                ('normalized_value', models.CharField(editable=False, max_length=128, verbose_name='规范化外部编码')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_references', to='assets.asset', verbose_name='资产')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_external_references', to='masterdata.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_external_references', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资产外部引用',
                'verbose_name_plural': '资产外部引用',
                'ordering': ('asset_id', 'external_system', 'reference_type'),
                'constraints': [models.UniqueConstraint(fields=('asset', 'external_system', 'reference_type'), name='uq_asset_external_ref_asset_type'), models.UniqueConstraint(fields=('company', 'external_system', 'reference_type', 'normalized_value'), name='uq_asset_external_ref_company_value'), models.CheckConstraint(condition=models.Q(('external_system', 'TPLUS')), name='ck_asset_external_ref_system'), models.CheckConstraint(condition=models.Q(('reference_type', 'asset_card_code')), name='ck_asset_external_ref_type'), models.CheckConstraint(condition=models.Q(models.Q(('reference_value', ''), _negated=True), models.Q(('normalized_value', ''), _negated=True)), name='ck_asset_external_ref_value_nonempty')],
            },
        ),
        migrations.RunPython(
            install_postgresql_guards,
            reverse_code=remove_postgresql_guards,
        ),
    ]
