# Generated by Django 5.2.17 on 2026-09-09 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
import importlib
from django.conf import settings
from django.db import migrations, models


def _function(module_name, variable, name):
    sql = getattr(importlib.import_module(module_name), variable)
    start = sql.index("CREATE OR REPLACE FUNCTION " + name + "()")
    end = sql.index("\n$$;", start) + len("\n$$;")
    return sql[start:end]


def _previous_sql():
    return {
        "references": _function(
            "apps.offboarding.migrations.0002_postgresql_clearance_guards",
            "OFFBOARDING_GUARDS_SQL", "assets_validate_asset_references",
        ),
        "physical": _function(
            "apps.assets.migrations.0002_postgresql_asset_guards",
            "CREATE_SQL", "assets_validate_asset_commit",
        ),
        "formal": _function(
            "apps.assets.migrations.0008_assetdisposal_assetdisposalreversal_assetloan_and_more",
            "ASSET_GUARDS_SQL", "assets_validate_formal_asset_commit",
        ),
        "finance": _function(
            "apps.finance.migrations.0004_postgresql_finance_guards",
            "CREATE_SQL", "finance_validate_asset_finance",
        ),
        "qr": _function(
            "apps.assets.migrations.0006_sprint6_qr_labels",
            "CREATE_SQL", "assets_validate_qr_identity",
        ),
    }


def _replace(sql, old, new):
    if sql.count(old) != 1:
        raise RuntimeError("Unexpected predecessor SQL in physical-registration migration.")
    return sql.replace(old, new, 1)


REGISTRATION_SQL = r"""
CREATE OR REPLACE FUNCTION assets_guard_registration()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a_company bigint; a_code bigint; i_company bigint;
BEGIN
    IF TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset registration is immutable';
    END IF;
    IF TG_OP='UPDATE' THEN
        IF OLD.registered_by_id IS NOT NULL AND NEW.registered_by_id IS NULL
           AND (to_jsonb(NEW)-'registered_by_id') IS NOT DISTINCT FROM
               (to_jsonb(OLD)-'registered_by_id') THEN RETURN NEW; END IF;
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset registration is immutable';
    END IF;
    IF COALESCE(current_setting('eam_lite.controlled_asset_registration',true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='registration requires the controlled service';
    END IF;
    PERFORM set_config('eam_lite.controlled_asset_registration','off',true);
    SELECT company_id,current_issued_code_id INTO a_company,a_code
      FROM assets_asset WHERE id=NEW.asset_id;
    SELECT company_id INTO i_company FROM masterdata_issuedcode WHERE id=NEW.result_issued_code_id;
    IF a_company IS DISTINCT FROM NEW.company_id OR i_company IS DISTINCT FROM NEW.company_id
       OR a_code IS DISTINCT FROM NEW.result_issued_code_id
       OR NOT EXISTS (
           SELECT 1 FROM assets_assetcodehistory
            WHERE asset_id=NEW.asset_id AND company_id=NEW.company_id
              AND event_type='issued' AND new_issued_code_id=NEW.result_issued_code_id
       ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='registration code and asset references are inconsistent';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_asset_registration_guard
BEFORE INSERT OR UPDATE OR DELETE ON assets_assetregistration
FOR EACH ROW EXECUTE FUNCTION assets_guard_registration();
CREATE CONSTRAINT TRIGGER trg_asset_registration_commit
AFTER INSERT OR UPDATE OR DELETE ON assets_assetregistration
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
EXECUTE FUNCTION assets_validate_formal_asset_commit();
"""


def _current_sql():
    previous = _previous_sql()
    references = _replace(
        previous["references"],
        "(OLD.asset_status='draft' AND NEW.asset_status='pending_finance')",
        "(OLD.asset_status='draft' AND NEW.asset_status IN ('pending_finance','pending_label'))",
    )
    references = _replace(references, "    IF TG_OP='UPDATE' THEN", """    IF TG_OP='UPDATE' THEN
        IF NEW.commissioning_date IS DISTINCT FROM OLD.commissioning_date AND EXISTS (
            SELECT 1 FROM finance_assetfinance
             WHERE asset_id=OLD.id AND finance_confirmed_at IS NOT NULL
        ) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='confirmed commissioning date is immutable';
        END IF;""")
    physical = previous["physical"]
    photo_start = physical.index("        PERFORM attachment.id")
    photo_end = physical.index("        PERFORM field.id", photo_start)
    physical = physical[:photo_start] + physical[photo_end:]
    physical = _replace(
        physical, "IF target_asset.asset_status = 'pending_finance' THEN",
        "IF target_asset.asset_status IN ('pending_finance','pending_label') THEN",
    )

    formal = _replace(previous["formal"], "'assets_assetmovement'\n", "'assets_assetmovement', 'assets_assetregistration'\n")
    formal = _replace(formal, "IF target_asset.asset_status NOT IN ('pending_label', 'in_use', 'idle') THEN",
                      "IF target_asset.asset_status NOT IN ('pending_label','in_use','idle','loaned','under_repair','pending_disposal') THEN")
    formal = _replace(formal, """    IF finance_id IS NULL OR finance_company <> target_asset.company_id
       OR finance_confirmed IS NULL OR finance_treatment IS NULL OR finance_cost IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '23514',
            MESSAGE = 'formal asset requires confirmed complete finance';
    END IF;""", """    IF finance_id IS NOT NULL AND finance_company <> target_asset.company_id THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='registered finance must belong to the asset company';
    END IF;
    IF finance_confirmed IS NOT NULL AND (finance_treatment IS NULL OR finance_cost IS NULL) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='confirmed finance must be complete';
    END IF;""")
    formal = _replace(formal, "    IF finance_treatment = 'fixed_asset' THEN", """    IF finance_confirmed IS NULL THEN
        IF EXISTS (
            SELECT 1 FROM finance_assetdepreciationprofile
             WHERE asset_id=target_asset.id AND status<>'draft'
        ) OR EXISTS (SELECT 1 FROM finance_depreciationentry WHERE asset_id=target_asset.id)
          OR EXISTS (SELECT 1 FROM finance_assetvalueadjustment WHERE asset_id=target_asset.id) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='unconfirmed finance cannot have posted depreciation or adjustments';
        END IF;
    ELSIF finance_treatment = 'fixed_asset' THEN""")
    formal = _replace(formal, "target_asset.asset_status IN ('in_use', 'idle')",
                      "target_asset.asset_status IN ('in_use','idle','loaned','under_repair','pending_disposal')")
    request_start = formal.index("    SELECT count(*) INTO formalization_count")
    request_end = formal.index("    IF formalized_issued_id IS DISTINCT", request_start)
    formal = formal[:request_start] + """    IF finance_confirmed IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM finance_financeformalizationrequest request
         WHERE request.asset_id=target_asset.id AND request.company_id=target_asset.company_id
           AND request.result_finance_id=finance_id AND request.status='completed'
           AND EXISTS (
               SELECT 1 FROM assets_assetcodehistory history
                WHERE history.asset_id=target_asset.id AND history.company_id=target_asset.company_id
                  AND history.new_issued_code_id=request.result_issued_code_id
                  AND history.event_type IN ('issued','corrected')
           )
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='confirmed finance requires its durable confirmation result';
    END IF;
    SELECT count(*),min(result_issued_code_id) INTO formalization_count,formalized_issued_id
      FROM assets_assetregistration
     WHERE asset_id=target_asset.id AND company_id=target_asset.company_id;
    IF formalization_count<>1 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='formal asset requires its durable physical registration';
    END IF;
""" + formal[request_end:]
    formal = formal.replace("immutable formalization result", "immutable physical registration result")

    finance = _replace(previous["finance"],
        "IF asset_state NOT IN ('pending_finance', 'pending_label') THEN",
        """IF asset_state='draft' OR (
            (TG_OP='INSERT' OR OLD.finance_confirmed_at IS NULL)
            AND asset_state NOT IN ('pending_finance','pending_label','in_use','idle','loaned','under_repair','pending_disposal')
        ) THEN""")
    finance = finance.replace("confirmed finance requires a formalization transaction", "finance confirmation requires an eligible asset")
    qr = _replace(previous["qr"], "IF current_asset_status = 'pending_finance' THEN",
                  "IF current_asset_status IN ('pending_finance','pending_label') THEN")
    return [references, physical, formal, finance, qr, REGISTRATION_SQL]


def backfill_registrations(apps, schema_editor):
    Registration = apps.get_model("assets", "AssetRegistration")
    Asset = apps.get_model("assets", "Asset")
    Request = apps.get_model("finance", "FinanceFormalizationRequest")
    alias = schema_editor.connection.alias
    requests = Request.objects.using(alias).filter(status="completed")
    for request in requests.iterator(chunk_size=500):
        Registration.objects.using(alias).create(
            id=request.pk, company_id=request.company_id, asset_id=request.asset_id,
            result_issued_code_id=request.result_issued_code_id,
            idempotency_key=request.idempotency_key, request_hash=request.request_hash,
            source="legacy_finance", registered_by_id=request.created_by_id,
            registered_at=request.completed_at,
        )
    if Asset.objects.using(alias).filter(current_issued_code__isnull=False).exclude(
        pk__in=Registration.objects.using(alias).values("asset_id")
    ).exists():
        raise RuntimeError("发现缺少原财务建档历史的正式资产；请核查原数据，不会补造历史。")


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for sql in _current_sql():
            schema_editor.execute(sql)


def remove_guards(apps, schema_editor):
    Registration = apps.get_model("assets", "AssetRegistration")
    if Registration.objects.using(schema_editor.connection.alias).filter(source="physical").exists():
        raise RuntimeError("已有独立实物建档历史，不能降级到财务先建档的旧结构；请保留本迁移。")
    Asset = apps.get_model("assets", "Asset")
    Link = apps.get_model("assets", "AttachmentLink")
    alias = schema_editor.connection.alias
    photographed = Link.objects.using(alias).filter(
        status="active", role__in=("cover", "photo"), security_class="A0",
        attachment__is_available=True,
        attachment__malware_scan_status__in=("policy_limited", "clean"),
        attachment__mime_type__startswith="image/",
    ).values("asset_id")
    if Asset.objects.using(alias).filter(asset_status="pending_finance").exclude(pk__in=photographed).exists():
        raise RuntimeError("存在无照片的旧流程待办，旧结构无法兼容；不能通过降级丢弃这些记录。")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER IF EXISTS trg_asset_registration_commit ON assets_assetregistration;
            DROP TRIGGER IF EXISTS trg_asset_registration_guard ON assets_assetregistration;
            DROP FUNCTION IF EXISTS assets_guard_registration();
        """)
        for sql in _previous_sql().values():
            schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_production_location_leaf_guard'),
        ('masterdata', '0012_sprint16_opening_custody_import'),
        ('finance', '0009_profile_actual_continuation'),
        ('offboarding', '0002_postgresql_clearance_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('physical', '实物建档'), ('legacy_finance', '原财务建档流程')], default='physical', max_length=24)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_registrations', to='masterdata.company')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_physical_assets', to=settings.AUTH_USER_MODEL)),
                ('result_issued_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asset_registration', to='masterdata.issuedcode')),
            ],
            options={
                'verbose_name': '实物建档记录',
                'verbose_name_plural': '实物建档记录',
                'constraints': [models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_asset_registration_company_key'), models.CheckConstraint(condition=models.Q(('source__in', ('physical', 'legacy_finance'))), name='ck_asset_registration_source'), models.CheckConstraint(condition=models.Q(('idempotency_key__gt', ''), ('request_hash__regex', '^[0-9a-f]{64}$')), name='ck_asset_registration_request')],
            },
        ),
        migrations.RunPython(backfill_registrations, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(install_guards, reverse_code=remove_guards),
    ]
