# Generated by Django 5.2.17 on 2026-09-10 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


IDENTITY_SQL = r'''
CREATE OR REPLACE FUNCTION assets_guard_identity_fields()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE parent_company bigint; parent_parent uuid;
BEGIN
    IF NEW.management_attribute NOT IN ('','FA','LV','IA','LS','OT')
       OR (NEW.coding_year IS NOT NULL AND (NEW.coding_year<1000
         OR NEW.coding_year>EXTRACT(YEAR FROM CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai'))) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid initial management attribute or coding year';
    END IF;
    IF NEW.component_of_id IS NOT NULL THEN
        SELECT company_id,component_of_id INTO parent_company,parent_parent FROM assets_asset WHERE id=NEW.component_of_id;
        IF NEW.component_of_id=NEW.id OR parent_company IS DISTINCT FROM NEW.company_id OR parent_parent IS NOT NULL THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='component parent must be a root asset in the same company';
        END IF;
    END IF;
    IF TG_OP='UPDATE' AND OLD.current_issued_code_id IS NOT NULL AND
        ROW(NEW.management_attribute,NEW.coding_year,NEW.coding_year_note,NEW.component_of_id)
        IS DISTINCT FROM ROW(OLD.management_attribute,OLD.coding_year,OLD.coding_year_note,OLD.component_of_id) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='initial management identity is immutable after registration';
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER trg_asset_identity_fields BEFORE INSERT OR UPDATE ON assets_asset
FOR EACH ROW EXECUTE FUNCTION assets_guard_identity_fields();

CREATE OR REPLACE FUNCTION assets_guard_unified_identity()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP<>'INSERT' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='unified identity history is append only';
    END IF;
    IF COALESCE(current_setting('eam_lite.controlled_asset_identity',true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='unified identity requires controlled issuance';
    END IF;
    PERFORM set_config('eam_lite.controlled_asset_identity','off',true);
    RETURN NEW;
END; $$;
CREATE TRIGGER trg_unified_identity_guard BEFORE INSERT OR UPDATE OR DELETE ON assets_assetidentity
FOR EACH ROW EXECUTE FUNCTION assets_guard_unified_identity();

CREATE OR REPLACE FUNCTION assets_validate_unified_identity()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_code bigint; identity assets_assetidentity%ROWTYPE; parent_identity assets_assetidentity%ROWTYPE;
        issued masterdata_issuedcode%ROWTYPE; asset assets_asset%ROWTYPE; expected_code text; expected_scope text;
BEGIN
    IF TG_TABLE_NAME='assets_assetidentity' THEN target_code:=NEW.issued_code_id;
    ELSIF TG_TABLE_NAME='masterdata_issuedcode' THEN target_code:=NEW.id;
    ELSE target_code:=NEW.current_issued_code_id; END IF;
    IF target_code IS NULL THEN RETURN NULL; END IF;
    SELECT * INTO issued FROM masterdata_issuedcode WHERE id=target_code;
    IF NOT FOUND THEN RETURN NULL; END IF;
    IF NOT EXISTS (SELECT 1 FROM masterdata_assetcodingsegment WHERE coding_scheme_id=issued.coding_scheme_id
        AND segment_type='management_attribute') THEN RETURN NULL; END IF;
    SELECT * INTO identity FROM assets_assetidentity WHERE issued_code_id=target_code;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='standard issued code requires its immutable identity'; END IF;
    SELECT * INTO asset FROM assets_asset WHERE id=identity.asset_id;
    IF asset.company_id IS DISTINCT FROM identity.company_id OR issued.company_id<>identity.company_id
       OR asset.management_attribute<>identity.management_attribute OR asset.coding_year IS DISTINCT FROM identity.coding_year
       OR asset.component_of_id IS DISTINCT FROM identity.parent_asset_id
       OR identity.sequence_value<>issued.sequence_value OR btrim(identity.year_note)=''
       OR identity.year_source NOT IN ('specified','acquisition_date','inclusion_year','parent')
       OR NOT EXISTS (SELECT 1 FROM assets_assetcodehistory WHERE asset_id=asset.id
           AND company_id=asset.company_id AND new_issued_code_id=issued.id AND event_type IN ('issued','corrected')) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='unified identity references or evidence are inconsistent';
    END IF;
    expected_code:=identity.management_attribute||'-'||identity.category_code||'-'||identity.coding_year::text
        ||'-'||lpad(identity.sequence_value::text,6,'0')||'-'||lpad(identity.subitem_number::text,2,'0');
    expected_scope:='{"standard":"asset_identity_v1","company_id":"'||identity.company_id::text||
        '","attribute":"'||identity.management_attribute||'","category_code":"'||identity.category_code||
        '","year":'||identity.coding_year::text;
    IF identity.parent_identity_id IS NOT NULL THEN
        SELECT * INTO parent_identity FROM assets_assetidentity WHERE id=identity.parent_identity_id;
        IF NOT FOUND OR parent_identity.company_id<>identity.company_id OR parent_identity.asset_id<>identity.parent_asset_id
           OR parent_identity.subitem_number<>0 OR
           ROW(parent_identity.management_attribute,parent_identity.category_code,parent_identity.coding_year,parent_identity.sequence_value)
           IS DISTINCT FROM ROW(identity.management_attribute,identity.category_code,identity.coding_year,identity.sequence_value) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='component must retain its parent identity prefix';
        END IF;
        expected_scope:=expected_scope||',"parent_id":"'||identity.parent_identity_id::text||'","subitem":'||identity.subitem_number::text||'}';
    ELSE
        expected_scope:=expected_scope||'}';
        IF NOT EXISTS (SELECT 1 FROM masterdata_sequencecounter WHERE company_id=identity.company_id
            AND scope_key=expected_scope AND current_value>=identity.sequence_value) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='root identity requires its persistent shared counter';
        END IF;
    END IF;
    IF issued.display_code IS DISTINCT FROM expected_code OR issued.normalized_code IS DISTINCT FROM lower(expected_code)
       OR issued.scope_key IS DISTINCT FROM expected_scope THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='unified code does not match its identity snapshot';
    END IF;
    RETURN NULL;
END; $$;
CREATE CONSTRAINT TRIGGER trg_unified_identity_commit AFTER INSERT OR UPDATE ON assets_assetidentity
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_validate_unified_identity();
CREATE CONSTRAINT TRIGGER trg_unified_asset_commit AFTER INSERT OR UPDATE ON assets_asset
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_validate_unified_identity();
CREATE CONSTRAINT TRIGGER trg_unified_code_commit AFTER INSERT OR UPDATE ON masterdata_issuedcode
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_validate_unified_identity();
'''


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(IDENTITY_SQL, params=None)


def remove_guards(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    if apps.get_model('assets', 'AssetIdentity').objects.exists() or Asset.objects.filter(
        ~models.Q(management_attribute='') | models.Q(coding_year__isnull=False)
        | ~models.Q(coding_year_note='') | models.Q(component_of__isnull=False)
        | ~models.Q(vehicle_plate='') | ~models.Q(chassis_number='') | ~models.Q(calibration_number='')
    ).exists():
        raise RuntimeError('已有统一身份或新增资产资料，不能通过降级丢弃记录。')
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('''
DROP TRIGGER IF EXISTS trg_asset_identity_fields ON assets_asset;
DROP TRIGGER IF EXISTS trg_unified_identity_guard ON assets_assetidentity;
DROP TRIGGER IF EXISTS trg_unified_identity_commit ON assets_assetidentity;
DROP TRIGGER IF EXISTS trg_unified_asset_commit ON assets_asset;
DROP TRIGGER IF EXISTS trg_unified_code_commit ON masterdata_issuedcode;
DROP FUNCTION IF EXISTS assets_guard_identity_fields();
DROP FUNCTION IF EXISTS assets_guard_unified_identity();
DROP FUNCTION IF EXISTS assets_validate_unified_identity();
''')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_physical_registration'),
        ('masterdata', '0013_unified_asset_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='calibration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='校准编号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='车架号'),
        ),
        migrations.AddField(
            model_name='asset',
            name='coding_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='取得年份（编码用）'),
        ),
        migrations.AddField(
            model_name='asset',
            name='coding_year_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='取得年份依据'),
        ),
        migrations.AddField(
            model_name='asset',
            name='component_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='assets.asset', verbose_name='所属主资产'),
        ),
        migrations.AddField(
            model_name='asset',
            name='management_attribute',
            field=models.CharField(blank=True, choices=[('FA', 'FA · 固定资产实物管理'), ('LV', 'LV · 逐件低值耐用品'), ('IA', 'IA · 无形资产'), ('LS', 'LS · 租入或受托资产'), ('OT', 'OT · 其他受控资产')], default='', help_text='用于稳定编码，财务认定不同也不改号。', max_length=2, verbose_name='首次建档管理属性'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=50, verbose_name='车牌号'),
        ),
        migrations.CreateModel(
            name='AssetIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('management_attribute', models.CharField(choices=[('FA', 'FA · 固定资产实物管理'), ('LV', 'LV · 逐件低值耐用品'), ('IA', 'IA · 无形资产'), ('LS', 'LS · 租入或受托资产'), ('OT', 'OT · 其他受控资产')], max_length=2, verbose_name='首次管理属性')),
                ('category_code', models.CharField(max_length=2, verbose_name='编码类别快照')),
                ('coding_year', models.PositiveSmallIntegerField(verbose_name='取得年份')),
                ('year_source', models.CharField(max_length=24, verbose_name='年份来源')),
                ('year_note', models.CharField(max_length=500, verbose_name='年份依据')),
                ('sequence_value', models.PositiveIntegerField(verbose_name='主资产流水')),
                ('subitem_number', models.PositiveSmallIntegerField(default=0, verbose_name='子项号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_history', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.company')),
                ('issued_code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identity', to='masterdata.issuedcode')),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_identities', to='assets.asset')),
                ('parent_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_identities', to='assets.assetidentity')),
            ],
            options={
                'verbose_name': '统一资产编码身份',
                'constraints': [models.UniqueConstraint(fields=('company', 'management_attribute', 'category_code', 'coding_year', 'sequence_value', 'subitem_number'), name='uq_asset_standard_identity'), models.UniqueConstraint(condition=models.Q(('parent_identity__isnull', False)), fields=('parent_identity', 'subitem_number'), name='uq_asset_parent_subitem'), models.CheckConstraint(condition=models.Q(('management_attribute__in', ['FA', 'LV', 'IA', 'LS', 'OT'])), name='ck_asset_identity_attribute'), models.CheckConstraint(condition=models.Q(('category_code__regex', '^(0[1-9]|[1-9][0-9])$')), name='ck_asset_identity_category'), models.CheckConstraint(condition=models.Q(('coding_year__gte', 1000), ('coding_year__lte', 9999)), name='ck_asset_identity_year'), models.CheckConstraint(condition=models.Q(('sequence_value__gte', 1), ('sequence_value__lte', 999999)), name='ck_asset_identity_sequence'), models.CheckConstraint(condition=models.Q(models.Q(('parent_asset__isnull', True), ('parent_identity__isnull', True), ('subitem_number', 0)), models.Q(('parent_asset__isnull', False), ('parent_identity__isnull', False), ('subitem_number__gte', 1), ('subitem_number__lte', 99)), _connector='OR'), name='ck_asset_identity_subitem'), models.CheckConstraint(condition=models.Q(('parent_asset', models.F('asset')), _negated=True), name='ck_asset_identity_not_self')],
            },
        ),
        migrations.RunPython(install_guards, reverse_code=remove_guards),
    ]
