# Generated by Django 5.2.17 on 2026-09-10 06:49

from django.conf import settings
from django.db import migrations, models
from importlib import import_module


def previous_qr_sql():
    return import_module('apps.assets.migrations.0015_physical_registration')._current_sql()[4].replace('%%', '%')


def current_qr_sql():
    source = previous_qr_sql()
    old = "AND OLD.label_status = 'printed' AND NEW.label_status = 'attached'"
    new = """AND (OLD.label_status='printed' OR (OLD.label_status='ready_to_print' AND EXISTS (
               SELECT 1 FROM assets_assetlabelattachmentrequest request
               JOIN assets_asset asset ON asset.id=request.asset_id
                WHERE request.qr_identity_id=NEW.id AND request.asset_id=NEW.asset_id
                  AND btrim(request.identification_evidence)<>''
                  AND (request.identification_method='alternative'
                    OR (request.identification_method='electronic' AND asset.management_attribute='IA'))
           ))) AND NEW.label_status='attached'"""
    if source.count(old) != 1:
        raise RuntimeError('Unexpected predecessor QR transition guard')
    source = source.replace(old, new, 1)
    # An explicit code correction is distinct from a financial classification
    # change. Its immutable history also supports correcting an unprinted QR.
    correction = """EXISTS (
        SELECT 1 FROM assets_assetqridentity prior_qr
        JOIN assets_asset asset ON asset.id=prior_qr.asset_id
        JOIN assets_assetcodehistory history ON history.asset_id=asset.id
         WHERE prior_qr.asset_id=NEW.asset_id AND prior_qr.company_id=NEW.company_id
           AND prior_qr.version=NEW.version-1 AND prior_qr.status='revoked'
           AND history.event_type='corrected' AND history.old_issued_code_id=asset.current_issued_code_id
           AND history.operated_by_id=NEW.issued_by_id
           AND prior_qr.revoke_reason='正式编号更正：'||history.reason
    )"""
    old = "IF current_asset_status IN ('pending_finance','pending_label') THEN"
    new = """IF controlled_qr AND NEW.version>1
           AND current_asset_status IN ('pending_label','in_use','idle','loaned','under_repair','pending_disposal')
           AND """ + correction + """ THEN
            PERFORM set_config('eam_lite.controlled_qr_identity_mutation','off',true);
        ELSIF current_asset_status IN ('pending_finance','pending_label') THEN"""
    if source.count(old) != 1:
        raise RuntimeError('Unexpected predecessor initial QR branch')
    source = source.replace(old, new, 1)
    old = "ELSIF OLD.status = 'active' AND NEW.status = 'revoked'"
    new = """ELSIF OLD.status='active' AND NEW.status='revoked'
           AND OLD.label_status IN ('ready_to_print','printed') AND NEW.label_status=OLD.label_status
           AND NEW.revoked_at IS NOT NULL AND NEW.revoked_by_id IS NOT NULL
           AND NEW.attached_at IS NOT DISTINCT FROM OLD.attached_at
           AND NEW.attached_by_id IS NOT DISTINCT FROM OLD.attached_by_id
           AND EXISTS (
               SELECT 1 FROM assets_assetcodehistory history JOIN assets_asset asset ON asset.id=history.asset_id
                WHERE asset.id=NEW.asset_id AND history.event_type='corrected'
                  AND history.old_issued_code_id=asset.current_issued_code_id
                  AND history.operated_by_id=NEW.revoked_by_id
                  AND NEW.revoke_reason='正式编号更正：'||history.reason
           ) THEN NULL;
        """ + old
    if source.count(old) != 1:
        raise RuntimeError('Unexpected predecessor QR revocation branch')
    return source.replace(old, new, 1)


EVIDENCE_SQL = r'''
CREATE OR REPLACE FUNCTION assets_guard_identification_evidence()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP='UPDATE' AND ROW(NEW.identification_method,NEW.identification_evidence)
       IS DISTINCT FROM ROW(OLD.identification_method,OLD.identification_evidence) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='identification method and evidence are immutable';
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER trg_identification_evidence_guard BEFORE UPDATE ON assets_assetlabelattachmentrequest
FOR EACH ROW EXECUTE FUNCTION assets_guard_identification_evidence();

CREATE OR REPLACE FUNCTION assets_validate_identification_evidence()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE label_state varchar; attribute varchar;
BEGIN
    IF TG_OP='UPDATE' OR NEW.identification_method='physical' THEN RETURN NULL; END IF;
    SELECT qr.label_status,asset.management_attribute INTO label_state,attribute
      FROM assets_assetqridentity qr JOIN assets_asset asset ON asset.id=qr.asset_id
     WHERE qr.id=NEW.qr_identity_id AND asset.id=NEW.asset_id AND asset.company_id=NEW.company_id;
    IF label_state IS DISTINCT FROM 'attached' OR btrim(NEW.identification_evidence)=''
       OR NEW.completed_by_id IS NULL OR NEW.target_status NOT IN ('in_use','idle','')
       OR (NEW.identification_method='electronic' AND attribute IS DISTINCT FROM 'IA') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='nonphysical identification needs completed matching evidence';
    END IF;
    RETURN NULL;
END; $$;
CREATE CONSTRAINT TRIGGER trg_identification_evidence_commit AFTER INSERT OR UPDATE ON assets_assetlabelattachmentrequest
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_validate_identification_evidence();
'''


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(current_qr_sql(), params=None)
        schema_editor.execute(EVIDENCE_SQL, params=None)


def remove_guards(apps, schema_editor):
    if apps.get_model('assets', 'AssetLabelAttachmentRequest').objects.exclude(identification_method='physical').exists():
        raise RuntimeError('已有电子台账或替代标识确认，不能降级丢弃证据。')
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('''
DROP TRIGGER IF EXISTS trg_identification_evidence_guard ON assets_assetlabelattachmentrequest;
DROP TRIGGER IF EXISTS trg_identification_evidence_commit ON assets_assetlabelattachmentrequest;
DROP FUNCTION IF EXISTS assets_guard_identification_evidence();
DROP FUNCTION IF EXISTS assets_validate_identification_evidence();
''')
        schema_editor.execute(previous_qr_sql(), params=None)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_unified_asset_identity'),
        ('masterdata', '0013_unified_asset_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlabelattachmentrequest',
            name='identification_evidence',
            field=models.CharField(blank=True, max_length=1000, verbose_name='标识确认依据'),
        ),
        migrations.AddField(
            model_name='assetlabelattachmentrequest',
            name='identification_method',
            field=models.CharField(choices=[('physical', '实物贴标'), ('electronic', '电子台账'), ('alternative', '替代标识')], default='physical', max_length=16, verbose_name='标识确认方式'),
        ),
        migrations.AddConstraint(
            model_name='assetlabelattachmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identification_evidence', ''), ('identification_method', 'physical')), models.Q(('identification_method__in', ('electronic', 'alternative')), models.Q(('identification_evidence', ''), _negated=True)), _connector='OR'), name='ck_label_identification_evidence'),
        ),
        migrations.RunPython(install_guards, reverse_code=remove_guards),
    ]
