# Generated by Django 5.2.17 on 2026-09-10 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


TRACE_SQL = r'''
CREATE OR REPLACE FUNCTION assets_guard_trace_record()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE source_company bigint; target_company bigint; source_code bigint; target_code bigint;
        prior_asset uuid; prior_version integer; entry jsonb; quantity_value numeric;
BEGIN
    IF TG_OP='UPDATE' AND OLD.recorded_by_id IS NOT NULL AND NEW.recorded_by_id IS NULL
       AND (to_jsonb(NEW)-'recorded_by_id')=(to_jsonb(OLD)-'recorded_by_id') THEN RETURN NEW; END IF;
    IF TG_OP<>'INSERT' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset provenance and composition history is append only';
    END IF;
    IF COALESCE(current_setting('eam_lite.controlled_asset_trace',true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset trace requires a controlled service';
    END IF;
    PERFORM set_config('eam_lite.controlled_asset_trace','off',true);
    PERFORM 1 FROM masterdata_company WHERE id=NEW.company_id FOR UPDATE;
    IF btrim(NEW.idempotency_key)='' OR btrim(NEW.reason)='' OR NEW.request_hash !~ '^[0-9a-f]{64}$'
       OR NEW.recorded_by_id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset trace requires attributable evidence';
    END IF;
    IF TG_TABLE_NAME='assets_assetoriginlink' THEN
        SELECT company_id,current_issued_code_id INTO source_company,source_code FROM assets_asset WHERE id=NEW.source_asset_id;
        SELECT company_id,current_issued_code_id INTO target_company,target_code FROM assets_asset WHERE id=NEW.target_asset_id;
        IF source_company IS DISTINCT FROM NEW.company_id OR target_company IS DISTINCT FROM NEW.company_id
           OR source_code IS NULL OR target_code IS NULL OR source_code<>NEW.source_issued_code_id OR target_code<>NEW.target_issued_code_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='origin must snapshot registered assets in the same company';
        END IF;
        IF EXISTS (WITH RECURSIVE reach(id) AS (
            SELECT NEW.target_asset_id UNION
            SELECT edge.target_asset_id FROM assets_assetoriginlink edge JOIN reach ON edge.source_asset_id=reach.id
              WHERE edge.company_id=NEW.company_id
        ) SELECT 1 FROM reach WHERE id=NEW.source_asset_id) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='asset origin graph cannot contain a cycle';
        END IF;
    ELSE
        SELECT company_id,current_issued_code_id INTO target_company,target_code FROM assets_asset WHERE id=NEW.asset_id;
        IF target_company IS DISTINCT FROM NEW.company_id OR target_code IS NULL THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='composition requires a registered asset in its company';
        END IF;
        IF NEW.previous_revision_id IS NULL THEN
            IF NEW.revision<>1 OR EXISTS (SELECT 1 FROM assets_assetcompositionrevision WHERE asset_id=NEW.asset_id) THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='composition must start a single continuous chain';
            END IF;
        ELSE
            SELECT asset_id,revision INTO prior_asset,prior_version FROM assets_assetcompositionrevision WHERE id=NEW.previous_revision_id;
            IF prior_asset IS DISTINCT FROM NEW.asset_id OR NEW.revision<>prior_version+1 THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='composition revision must follow the same asset';
            END IF;
        END IF;
        IF jsonb_typeof(NEW.members) IS DISTINCT FROM 'array' OR jsonb_array_length(NEW.members) NOT BETWEEN 1 AND 500 THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='composition requires a bounded member list';
        END IF;
        FOR entry IN SELECT value FROM jsonb_array_elements(NEW.members) LOOP
            IF jsonb_typeof(entry) IS DISTINCT FROM 'object' OR NOT entry ?& ARRAY['name','quantity','unit','note']
               OR (SELECT count(*) FROM jsonb_object_keys(entry))<>4
               OR jsonb_typeof(entry->'name')<>'string' OR jsonb_typeof(entry->'unit')<>'string'
               OR jsonb_typeof(entry->'note')<>'string' OR jsonb_typeof(entry->'quantity')<>'string'
               OR length(btrim(entry->>'name')) NOT BETWEEN 1 AND 200
               OR length(btrim(entry->>'unit')) NOT BETWEEN 1 AND 32 OR length(entry->>'note')>500
               OR (entry->>'quantity') !~ '^[0-9]{1,14}[.][0-9]{4}$' THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid composition member';
            END IF;
            quantity_value:=(entry->>'quantity')::numeric;
            IF NOT (quantity_value>0 AND quantity_value<100000000000000) THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid composition member quantity';
            END IF;
        END LOOP;
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER trg_asset_origin_history BEFORE INSERT OR UPDATE OR DELETE ON assets_assetoriginlink
FOR EACH ROW EXECUTE FUNCTION assets_guard_trace_record();
CREATE TRIGGER trg_asset_composition_history BEFORE INSERT OR UPDATE OR DELETE ON assets_assetcompositionrevision
FOR EACH ROW EXECUTE FUNCTION assets_guard_trace_record();
'''


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(TRACE_SQL, params=None)


def remove_guards(apps, schema_editor):
    if any(apps.get_model('assets', name).objects.exists() for name in ('AssetOriginLink','AssetCompositionRevision')):
        raise RuntimeError('已有来源或组合历史，不能通过降级丢弃记录。')
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('''
DROP TRIGGER IF EXISTS trg_asset_origin_history ON assets_assetoriginlink;
DROP TRIGGER IF EXISTS trg_asset_composition_history ON assets_assetcompositionrevision;
DROP FUNCTION IF EXISTS assets_guard_trace_record();
''')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_identification_without_physical_label'),
        ('masterdata', '0013_unified_asset_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCompositionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=1000, verbose_name='依据或说明')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.PositiveIntegerField(verbose_name='清单版本')),
                ('members', models.JSONField(verbose_name='组合成员清单')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composition_revisions', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.company')),
                ('previous_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revision', to='assets.assetcompositionrevision')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资产组合清单历史',
                'ordering': ('-revision',),
                'constraints': [models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_composition_company_idem'), models.UniqueConstraint(fields=('asset', 'revision'), name='uq_asset_composition_revision'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='ck_composition_revision'), models.CheckConstraint(condition=models.Q(('id', models.F('previous_revision')), _negated=True), name='ck_composition_not_self')],
            },
        ),
        migrations.CreateModel(
            name='AssetOriginLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=1000, verbose_name='依据或说明')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('relation_type', models.CharField(choices=[('split', '拆分来源'), ('merge', '合并来源')], max_length=16, verbose_name='来源关系')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_outgoing', to='assets.asset')),
                ('source_issued_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_sources', to='masterdata.issuedcode')),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_incoming', to='assets.asset')),
                ('target_issued_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_targets', to='masterdata.issuedcode')),
            ],
            options={
                'verbose_name': '资产来源记录',
                'constraints': [models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_origin_company_idem'), models.UniqueConstraint(fields=('source_asset', 'target_asset', 'relation_type'), name='uq_asset_origin_edge'), models.CheckConstraint(condition=models.Q(('source_asset', models.F('target_asset')), _negated=True), name='ck_origin_not_self'), models.CheckConstraint(condition=models.Q(('relation_type__in', ('split', 'merge'))), name='ck_origin_type')],
            },
        ),
        migrations.RunPython(install_guards, reverse_code=remove_guards),
    ]
