# Generated by Django 5.2.17 on 2026-09-10 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from importlib import import_module


def predecessor_functions():
    helpers = import_module('apps.assets.migrations.0015_physical_registration')
    references = helpers._current_sql()[0].replace('%%', '%')
    movement = helpers._function('apps.assets.migrations.0008_assetdisposal_assetdisposalreversal_assetloan_and_more',
                                 'ASSET_GUARDS_SQL', 'assets_sprint7_validate_movement').replace('%%', '%')
    return references, movement


def current_functions():
    references, movement = predecessor_functions()
    marker = "OR (OLD.asset_status='pending_label' AND NEW.asset_status IN ('in_use','idle'))"
    addition = marker + """
            OR (OLD.asset_status IN ('pending_label','in_use','idle','under_repair') AND NEW.asset_status='other_disposed'
                AND EXISTS (SELECT 1 FROM assets_assetcustodyreturn returned
                    WHERE returned.asset_id=NEW.id AND returned.company_id=NEW.company_id AND returned.movement_id IS NOT NULL))"""
    if references.count(marker) != 1:
        raise RuntimeError('Unexpected asset state guard predecessor')
    references = references.replace(marker, addition, 1)
    marker = "'disposal_complete','disposal_reversal'"
    if movement.count(marker) != 1:
        raise RuntimeError('Unexpected movement guard predecessor')
    movement = movement.replace(marker, marker + ",'custody_return'", 1)
    marker = '    RETURN NEW;\nEND;\n$$;'
    addition = """    IF NEW.movement_type='custody_return' AND NOT (
        NEW.from_status IN ('pending_label','in_use','idle','under_repair') AND NEW.to_status='other_disposed'
        AND ROW(NEW.from_department_id,NEW.from_employee_id,NEW.from_location_id)
            IS NOT DISTINCT FROM ROW(NEW.to_department_id,NEW.to_employee_id,NEW.to_location_id)
    ) THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid custody return movement'; END IF;
""" + marker
    if movement.count(marker) != 1:
        raise RuntimeError('Unexpected movement return statement')
    return references, movement.replace(marker, addition, 1)


RETURN_SQL = r'''
CREATE OR REPLACE FUNCTION assets_guard_custody_return()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE asset assets_asset%ROWTYPE; movement assets_assetmovement%ROWTYPE; prior_company bigint; prior_asset uuid;
BEGIN
    IF TG_OP='UPDATE' AND OLD.recorded_by_id IS NOT NULL AND NEW.recorded_by_id IS NULL
       AND (to_jsonb(NEW)-'recorded_by_id')=(to_jsonb(OLD)-'recorded_by_id') THEN RETURN NEW; END IF;
    IF TG_OP<>'INSERT' THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='custody return is immutable history'; END IF;
    IF COALESCE(current_setting('eam_lite.controlled_asset_custody_return',true),'')<>'on' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='custody return needs controlled service';
    END IF;
    PERFORM set_config('eam_lite.controlled_asset_custody_return','off',true);
    SELECT * INTO asset FROM assets_asset WHERE id=NEW.asset_id;
    IF NOT FOUND OR asset.company_id<>NEW.company_id OR asset.management_attribute<>'LS'
       OR asset.current_issued_code_id IS DISTINCT FROM NEW.issued_code_id OR asset.record_status<>'active'
       OR btrim(NEW.counterparty)='' OR btrim(NEW.contract_reference)='' OR btrim(NEW.acceptance_evidence)=''
       OR btrim(NEW.reason)='' OR btrim(NEW.idempotency_key)='' OR NEW.request_hash !~ '^[0-9a-f]{64}$'
       OR NEW.recorded_by_id IS NULL OR NEW.returned_on>(CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Shanghai')::date
       OR (asset.acquisition_date IS NOT NULL AND NEW.returned_on<asset.acquisition_date)
       OR NOT EXISTS (SELECT 1 FROM assets_assetregistration WHERE asset_id=asset.id AND company_id=asset.company_id)
       OR (SELECT count(*) FROM assets_assetqridentity WHERE asset_id=asset.id AND status='active')<>1 THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid custody return identity or evidence';
    END IF;
    IF EXISTS (SELECT 1 FROM assets_asset child WHERE child.component_of_id=asset.id
        AND child.record_status='active' AND child.asset_status NOT IN ('disposed','sold','other_disposed')) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='independent components must be handled before parent return';
    END IF;
    IF NEW.composition_revision_id IS NOT NULL THEN
        SELECT company_id,asset_id INTO prior_company,prior_asset FROM assets_assetcompositionrevision WHERE id=NEW.composition_revision_id;
        IF prior_company IS DISTINCT FROM NEW.company_id OR prior_asset IS DISTINCT FROM NEW.asset_id THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='custody return composition does not belong to asset';
        END IF;
    END IF;
    IF NEW.movement_id IS NULL THEN
        IF asset.asset_status<>'other_disposed' OR NOT EXISTS (SELECT 1 FROM assets_assetdisposal WHERE asset_id=asset.id AND status='confirmed') THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='return evidence without new movement requires completed disposal';
        END IF;
    ELSE
        SELECT * INTO movement FROM assets_assetmovement WHERE id=NEW.movement_id;
        IF NOT FOUND OR movement.company_id<>NEW.company_id OR movement.asset_id<>NEW.asset_id
           OR movement.movement_type<>'custody_return' OR movement.from_status<>asset.asset_status
           OR EXISTS (SELECT 1 FROM finance_assetfinance WHERE asset_id=asset.id AND finance_confirmed_at IS NOT NULL AND accounting_treatment='fixed_asset')
           OR EXISTS (SELECT 1 FROM finance_assetdepreciationprofile WHERE asset_id=asset.id AND status IN ('active','suspended'))
           OR EXISTS (SELECT 1 FROM finance_depreciationentry WHERE asset_id=asset.id)
           OR EXISTS (SELECT 1 FROM finance_assetvalueadjustment WHERE asset_id=asset.id) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='custody return cannot silently change confirmed accounting';
        END IF;
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER trg_custody_return_guard BEFORE INSERT OR UPDATE OR DELETE ON assets_assetcustodyreturn
FOR EACH ROW EXECUTE FUNCTION assets_guard_custody_return();

CREATE OR REPLACE FUNCTION assets_validate_custody_return_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_asset uuid;
BEGIN
    IF TG_TABLE_NAME='assets_assetmovement' THEN
        IF NEW.movement_type<>'custody_return' THEN RETURN NULL; END IF;
        IF NOT EXISTS (SELECT 1 FROM assets_assetcustodyreturn WHERE movement_id=NEW.id AND asset_id=NEW.asset_id) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='custody return movement needs its durable result';
        END IF;
        target_asset:=NEW.asset_id;
    ELSE
        IF TG_OP='UPDATE' THEN RETURN NULL; END IF;
        target_asset:=NEW.asset_id;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM assets_asset WHERE id=target_asset AND asset_status='other_disposed') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='custody return must close physical management';
    END IF;
    RETURN NULL;
END; $$;
CREATE CONSTRAINT TRIGGER trg_custody_return_commit AFTER INSERT OR UPDATE ON assets_assetcustodyreturn
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_validate_custody_return_commit();
CREATE CONSTRAINT TRIGGER trg_custody_return_movement_commit AFTER INSERT ON assets_assetmovement
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION assets_validate_custody_return_commit();
'''


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        for sql in (*current_functions(), RETURN_SQL):
            schema_editor.execute(sql, params=None)


def remove_guards(apps, schema_editor):
    if apps.get_model('assets', 'AssetCustodyReturn').objects.exists() or apps.get_model('assets', 'AssetMovement').objects.filter(movement_type='custody_return').exists():
        raise RuntimeError('已有租入受托归还记录，不能通过降级丢弃历史。')
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('''
DROP TRIGGER IF EXISTS trg_custody_return_guard ON assets_assetcustodyreturn;
DROP TRIGGER IF EXISTS trg_custody_return_commit ON assets_assetcustodyreturn;
DROP TRIGGER IF EXISTS trg_custody_return_movement_commit ON assets_assetmovement;
DROP FUNCTION IF EXISTS assets_guard_custody_return();
DROP FUNCTION IF EXISTS assets_validate_custody_return_commit();
''')
        for sql in predecessor_functions():
            schema_editor.execute(sql, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_asset_origin_and_composition'),
        ('masterdata', '0013_unified_asset_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCustodyReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=1000, verbose_name='依据或说明')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('returned_on', models.DateField(verbose_name='实际归还日期')),
                ('counterparty', models.CharField(max_length=200, verbose_name='接收单位或接收人')),
                ('contract_reference', models.CharField(max_length=200, verbose_name='合同或受托依据')),
                ('acceptance_evidence', models.CharField(max_length=1000, verbose_name='归还验收依据')),
            ],
            options={
                'verbose_name': '租入受托资产归还记录',
            },
        ),
        migrations.RemoveConstraint(
            model_name='assetmovement',
            name='ck_movement_type_valid',
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_type',
            field=models.CharField(choices=[('assignment', '领用'), ('assignment_return', '领用归还'), ('transfer', '调拨/责任位置变更'), ('loan', '借出'), ('loan_return', '借出归还'), ('idle', '闲置'), ('activate', '启用'), ('repair_start', '送修'), ('repair_complete', '维修完成'), ('label_activation', '首次贴标启用'), ('disposal_start', '发起处置'), ('disposal_cancel', '取消处置'), ('disposal_complete', '完成处置'), ('disposal_reversal', '处置冲销'), ('custody_return', '租入或受托归还')], max_length=32, verbose_name='变动类型'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ('assignment', 'assignment_return', 'transfer', 'loan', 'loan_return', 'idle', 'activate', 'repair_start', 'repair_complete', 'label_activation', 'disposal_start', 'disposal_cancel', 'disposal_complete', 'disposal_reversal', 'custody_return'))), name='ck_movement_type_valid'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturn',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custody_return_record', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturn',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.company'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturn',
            name='composition_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assetcompositionrevision'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturn',
            name='issued_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.issuedcode'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturn',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assetmovement'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturn',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assetcustodyreturn',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_custody_return_company_idem'),
        ),
        migrations.RunPython(install_guards, reverse_code=remove_guards),
    ]
