# Generated by Django 5.2.17 on 2026-09-17 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_leased_custody_return'),
        ('masterdata', '0015_remove_asset_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCustodyReturnReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=1000, verbose_name='依据或说明')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '租入受托归还撤销记录',
            },
        ),
        migrations.CreateModel(
            name='AssetOriginReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=1000, verbose_name='依据或说明')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '来源登记撤销记录',
            },
        ),
        migrations.RemoveConstraint(
            model_name='assetmovement',
            name='ck_movement_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='assetoriginlink',
            name='uq_asset_origin_edge',
        ),
        migrations.AddField(
            model_name='assetcustodyreturn',
            name='maintenance_plan_states',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assetcustodyreturn',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_returns', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_type',
            field=models.CharField(choices=[('assignment', '领用'), ('assignment_return', '领用归还'), ('transfer', '调拨/责任位置变更'), ('loan', '借出'), ('loan_return', '借出归还'), ('idle', '闲置'), ('activate', '启用'), ('repair_start', '送修'), ('repair_complete', '维修完成'), ('label_activation', '首次贴标启用'), ('disposal_start', '发起处置'), ('disposal_cancel', '取消处置'), ('disposal_complete', '完成处置'), ('disposal_reversal', '处置冲销'), ('custody_return', '租入或受托归还'), ('custody_return_reversal', '撤销租入受托归还')], max_length=32, verbose_name='变动类型'),
        ),
        migrations.AddConstraint(
            model_name='assetmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ('assignment', 'assignment_return', 'transfer', 'loan', 'loan_return', 'idle', 'activate', 'repair_start', 'repair_complete', 'label_activation', 'disposal_start', 'disposal_cancel', 'disposal_complete', 'disposal_reversal', 'custody_return', 'custody_return_reversal'))), name='ck_movement_type_valid'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturnreversal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.company'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturnreversal',
            name='custody_return',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='assets.assetcustodyreturn'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturnreversal',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_return_reversal', to='assets.assetmovement'),
        ),
        migrations.AddField(
            model_name='assetcustodyreturnreversal',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetoriginreversal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.company'),
        ),
        migrations.AddField(
            model_name='assetoriginreversal',
            name='origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='assets.assetoriginlink'),
        ),
        migrations.AddField(
            model_name='assetoriginreversal',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assetcustodyreturnreversal',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_return_reversal_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetoriginreversal',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_origin_reversal_idem'),
        ),
    ]
