# Generated by Django 5.2.17 on 2026-08-24 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_set_id', models.CharField(max_length=64, verbose_name='备份集编号')),
                ('kind', models.CharField(choices=[('automatic', '自动日备份'), ('manual', '管理员手动备份')], max_length=16, verbose_name='类型')),
                ('status', models.CharField(choices=[('pending', '生成中'), ('completed', '已完成'), ('failed', '失败'), ('expired', '已过期')], default='pending', max_length=16, verbose_name='状态')),
                ('request_hash', models.CharField(max_length=64, verbose_name='请求摘要')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('storage_key', models.CharField(blank=True, max_length=255, verbose_name='受保护存储键')),
                ('package_sha256', models.CharField(blank=True, max_length=64, verbose_name='备份包摘要')),
                ('package_size', models.BigIntegerField(blank=True, null=True, verbose_name='备份包字节数')),
                ('manifest_json', models.JSONField(blank=True, default=dict, verbose_name='清单快照')),
                ('data_snapshot_at', models.DateTimeField(blank=True, null=True, verbose_name='数据快照时间')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='保留到期时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='实际过期时间')),
                ('error_summary', models.TextField(blank=True, verbose_name='失败摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_sets', to='masterdata.company', verbose_name='公司')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_backup_sets', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BackupDownloadGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('issued', '已签发'), ('started', '下载中'), ('completed', '已完成'), ('failed', '失败')], default='issued', max_length=16, verbose_name='状态')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('issued_at', models.DateTimeField(verbose_name='签发时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始下载时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_download_grants', to='masterdata.company', verbose_name='公司')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_download_grants', to=settings.AUTH_USER_MODEL, verbose_name='下载用户')),
                ('backup_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_grants', to='operations.backupset', verbose_name='备份集')),
            ],
            options={
                'ordering': ('-issued_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='backupset',
            constraint=models.UniqueConstraint(fields=('company', 'backup_set_id'), name='uq_backup_company_set'),
        ),
        migrations.AddConstraint(
            model_name='backupset',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_backup_company_idem'),
        ),
        migrations.AddConstraint(
            model_name='backupset',
            constraint=models.CheckConstraint(condition=models.Q(('package_size__isnull', True), ('package_size__gte', 0), _connector='OR'), name='ck_backup_package_size'),
        ),
        migrations.AddConstraint(
            model_name='backupdownloadgrant',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_backup_grant_company_idem'),
        ),
    ]
