# Generated by Django 5.2.17 on 2026-08-11 07:13

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Sprint 1 建立 Company 后，以跟踪迁移添加
# company -> Company(on_delete=PROTECT, null=True)。Sprint 0 不创建文本占位列。
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='动作')),
                ('object_type', models.CharField(max_length=100, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='对象标识')),
                ('old_data_json', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='变更前数据')),
                ('new_data_json', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='变更后数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='关联标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['correlation_id'], name='audit_audit_correla_69684b_idx')],
            },
        ),
    ]
