# Generated by Django 5.2.17 on 2026-08-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_postgresql_audit_actor_set_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=("company", "created_at"),
                name="audit_co_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=("company", "user", "created_at"),
                name="audit_co_user_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=("company", "object_type", "object_id", "created_at"),
                name="audit_co_object_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=("company", "action", "created_at"),
                name="audit_co_action_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=("company", "correlation_id", "created_at"),
                name="audit_co_corr_at_idx",
            ),
        ),
    ]
