# Generated by Django 5.2.17 on 2026-09-24 08:13

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_actor_set_null_integrity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationUndo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_json', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='undo', to='audit.auditlog')),
                ('reversal_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='undone_operations', to='audit.auditlog')),
            ],
        ),
    ]
