# Generated by Django 5.2.17 on 2026-08-13 11:39

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


POSTGRESQL_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION reports_sprint11_guard_export_log()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    controlled boolean;
    actor_cleared boolean;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export logs cannot be deleted';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'pending' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export logs must be created pending';
        END IF;
        IF NEW.output_attachment_id IS NOT NULL OR NEW.output_sha256 <> ''
           OR NEW.totals_schema_version <> '' OR NEW.row_count IS NOT NULL
           OR NEW.data_snapshot_at IS NOT NULL OR NEW.completed_at IS NOT NULL
           OR NEW.error_summary <> '' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='pending export log cannot contain publication fields';
        END IF;
        RETURN NEW;
    END IF;
    actor_cleared := OLD.requested_by_id IS NOT NULL
        AND NEW.requested_by_id IS NULL
        AND (to_jsonb(NEW) - 'requested_by_id') = (to_jsonb(OLD) - 'requested_by_id');
    IF actor_cleared THEN
        RETURN NEW;
    END IF;
    IF OLD.status IN ('completed', 'failed', 'expired') THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='published export logs are immutable';
    END IF;
    IF OLD.status <> 'pending' OR NEW.status = 'pending' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid export log transition';
    END IF;
    controlled := COALESCE(
        current_setting('eam_lite.controlled_export_log_mutation', true), ''
    ) = 'on';
    IF NOT controlled THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export publication requires controlled service';
    END IF;
    IF ROW(
        NEW.id, NEW.company_id, NEW.export_type, NEW.filters_json, NEW.request_hash,
        NEW.idempotency_key, NEW.requested_by_id, NEW.requested_at
    ) IS DISTINCT FROM ROW(
        OLD.id, OLD.company_id, OLD.export_type, OLD.filters_json, OLD.request_hash,
        OLD.idempotency_key, OLD.requested_by_id, OLD.requested_at
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export request identity is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION reports_sprint11_guard_export_total()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    parent_status varchar;
    parent_type varchar;
    old_parent_status varchar;
BEGIN
    IF TG_OP = 'DELETE' THEN
        SELECT status INTO parent_status
          FROM reports_exportlog WHERE id = OLD.export_log_id;
        IF parent_status IS NULL OR parent_status <> 'pending' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='published export totals are immutable';
        END IF;
        RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' THEN
        SELECT status INTO old_parent_status
          FROM reports_exportlog WHERE id = OLD.export_log_id;
        IF old_parent_status IS NULL OR old_parent_status <> 'pending' THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='published export totals are immutable';
        END IF;
    END IF;
    SELECT status, export_type INTO parent_status, parent_type
      FROM reports_exportlog WHERE id = NEW.export_log_id;
    IF parent_status IS NULL OR parent_status <> 'pending' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export totals require a pending parent';
    END IF;
    IF parent_type <> 'tplus_reconciliation'
       OR NEW.metric_key NOT IN (
           'original_cost', 'opening_accumulated_depreciation',
           'automatic_depreciation', 'manual_depreciation', 'adjustment_net',
           'reversal_net', 'ending_accumulated_depreciation', 'impairment',
           'ending_book_value', 'disposal_income'
       ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='unknown export total metric';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION reports_sprint11_validate_export_commit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    target_id uuid;
    log_row record;
    actual_keys text[];
    expected_keys text[];
    attachment_company bigint;
    attachment_sha varchar;
BEGIN
    IF TG_TABLE_NAME = 'reports_exportlog' THEN
        target_id := NEW.id;
    ELSIF TG_OP = 'DELETE' THEN
        target_id := OLD.export_log_id;
    ELSE
        target_id := NEW.export_log_id;
    END IF;
    SELECT * INTO log_row FROM reports_exportlog WHERE id = target_id;
    IF NOT FOUND THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;

    IF log_row.output_attachment_id IS NOT NULL THEN
        SELECT company_id, sha256 INTO attachment_company, attachment_sha
          FROM masterdata_attachment WHERE id = log_row.output_attachment_id;
        IF attachment_company IS NULL OR attachment_company <> log_row.company_id
           OR attachment_sha IS DISTINCT FROM log_row.output_sha256 THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export attachment company or digest mismatch';
        END IF;
    END IF;

    IF EXISTS (
        SELECT 1 FROM reports_exportlogtotal t
         WHERE t.export_log_id = log_row.id AND t.company_id <> log_row.company_id
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export totals must be in same company';
    END IF;

    IF log_row.status = 'completed' THEN
        IF log_row.export_type = 'tplus_reconciliation' THEN
            IF log_row.totals_schema_version <> 'tplus_v1' THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid T+ totals schema version';
            END IF;
            expected_keys := ARRAY[
                'adjustment_net', 'automatic_depreciation', 'disposal_income',
                'ending_accumulated_depreciation', 'ending_book_value', 'impairment',
                'manual_depreciation', 'opening_accumulated_depreciation',
                'original_cost', 'reversal_net'
            ];
        ELSE
            IF log_row.totals_schema_version <> 'report_v1' THEN
                RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='invalid report totals schema version';
            END IF;
            expected_keys := ARRAY[]::text[];
        END IF;
        SELECT COALESCE(array_agg(metric_key ORDER BY metric_key), ARRAY[]::text[])
          INTO actual_keys
          FROM reports_exportlogtotal WHERE export_log_id = log_row.id;
        IF actual_keys IS DISTINCT FROM expected_keys THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='export totals schema is incomplete or contains unknown keys';
        END IF;
    ELSIF log_row.status IN ('failed', 'expired') AND EXISTS (
        SELECT 1 FROM reports_exportlogtotal WHERE export_log_id = log_row.id
    ) THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='non-completed export cannot retain totals';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_reports_export_log_guard ON reports_exportlog;
CREATE TRIGGER trg_reports_export_log_guard
BEFORE INSERT OR UPDATE OR DELETE ON reports_exportlog
FOR EACH ROW EXECUTE FUNCTION reports_sprint11_guard_export_log();

DROP TRIGGER IF EXISTS trg_reports_export_total_guard ON reports_exportlogtotal;
CREATE TRIGGER trg_reports_export_total_guard
BEFORE INSERT OR UPDATE OR DELETE ON reports_exportlogtotal
FOR EACH ROW EXECUTE FUNCTION reports_sprint11_guard_export_total();

DROP TRIGGER IF EXISTS trg_reports_export_log_commit ON reports_exportlog;
CREATE CONSTRAINT TRIGGER trg_reports_export_log_commit
AFTER INSERT OR UPDATE ON reports_exportlog
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION reports_sprint11_validate_export_commit();

DROP TRIGGER IF EXISTS trg_reports_export_total_commit ON reports_exportlogtotal;
CREATE CONSTRAINT TRIGGER trg_reports_export_total_commit
AFTER INSERT OR UPDATE OR DELETE ON reports_exportlogtotal
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION reports_sprint11_validate_export_commit();
"""

POSTGRESQL_GUARDS_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS trg_reports_export_total_commit ON reports_exportlogtotal;
DROP TRIGGER IF EXISTS trg_reports_export_log_commit ON reports_exportlog;
DROP TRIGGER IF EXISTS trg_reports_export_total_guard ON reports_exportlogtotal;
DROP TRIGGER IF EXISTS trg_reports_export_log_guard ON reports_exportlog;
DROP FUNCTION IF EXISTS reports_sprint11_validate_export_commit();
DROP FUNCTION IF EXISTS reports_sprint11_guard_export_total();
DROP FUNCTION IF EXISTS reports_sprint11_guard_export_log();
"""


def install_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(POSTGRESQL_GUARDS_SQL)


def remove_postgresql_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(POSTGRESQL_GUARDS_REVERSE_SQL)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0009_sprint5_asset_initialization_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('asset_ledger', '公司资产总账'), ('fixed_asset_detail', '固定资产明细'), ('depreciation_schedule', '折旧计划'), ('depreciation_detail', '折旧明细'), ('monthly_depreciation', '月度折旧'), ('department_assets', '部门资产'), ('employee_assets', '人员资产'), ('equipment_list', '设备清单'), ('mold_tool_inspection_list', '模具工具检具清单'), ('inventory_results', '盘点结果'), ('inventory_differences', '盘点差异'), ('maintenance_plans', '保养计划'), ('maintenance_due', '到期保养'), ('maintenance_records', '保养记录'), ('offboarding_unresolved', '离职资产未清'), ('disposal_list', '处置清单'), ('tplus_reconciliation', 'T+ 人工对账')], max_length=48, verbose_name='导出类型')),
                ('filters_json', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='筛选条件')),
                ('data_snapshot_at', models.DateTimeField(blank=True, null=True, verbose_name='数据截止时间')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='行数')),
                ('output_sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='摘要必须是 64 位小写十六进制字符串。', regex='^[0-9a-f]{64}$')], verbose_name='输出 SHA-256')),
                ('totals_schema_version', models.CharField(blank=True, max_length=32, verbose_name='合计 Schema 版本')),
                ('request_hash', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='摘要必须是 64 位小写十六进制字符串。', regex='^[0-9a-f]{64}$')], verbose_name='请求摘要')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.CharField(choices=[('pending', '生成中'), ('completed', '已完成'), ('failed', '失败'), ('expired', '已过期')], default='pending', max_length=16, verbose_name='状态')),
                ('error_summary', models.TextField(blank=True, verbose_name='错误摘要')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_logs', to='masterdata.company', verbose_name='公司')),
                ('output_attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_log', to='masterdata.attachment', verbose_name='输出附件')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_export_logs', to=settings.AUTH_USER_MODEL, verbose_name='导出人')),
            ],
            options={
                'verbose_name': '导出记录',
                'verbose_name_plural': '导出记录',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ExportLogTotal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=64, verbose_name='合计指标')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='币种')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_log_totals', to='masterdata.company', verbose_name='公司')),
                ('export_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='reports.exportlog', verbose_name='导出记录')),
            ],
            options={
                'verbose_name': '导出金额合计',
                'verbose_name_plural': '导出金额合计',
                'ordering': ('export_log_id', 'metric_key'),
            },
        ),
        migrations.AddConstraint(
            model_name='exportlog',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='uq_export_log_company_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='exportlog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'completed', 'failed', 'expired'))), name='ck_export_log_status'),
        ),
        migrations.AddConstraint(
            model_name='exportlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pending'), _negated=True), models.Q(('completed_at__isnull', True), ('data_snapshot_at__isnull', True), ('error_summary', ''), ('output_attachment__isnull', True), ('output_sha256', ''), ('row_count__isnull', True), ('totals_schema_version', '')), _connector='OR'), name='ck_export_log_pending_fields'),
        ),
        migrations.AddConstraint(
            model_name='exportlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), models.Q(('completed_at__isnull', False), ('data_snapshot_at__isnull', False), ('output_attachment__isnull', False), ('row_count__isnull', False), models.Q(('output_sha256', ''), _negated=True), models.Q(('totals_schema_version', ''), _negated=True), ('error_summary', '')), _connector='OR'), name='ck_export_log_completed_fields'),
        ),
        migrations.AddConstraint(
            model_name='exportlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), models.Q(('completed_at__isnull', True), ('output_attachment__isnull', True), ('output_sha256', ''), models.Q(('error_summary', ''), _negated=True)), _connector='OR'), name='ck_export_log_failed_fields'),
        ),
        migrations.AddConstraint(
            model_name='exportlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request_hash', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='ck_export_log_request_fields'),
        ),
        migrations.AddConstraint(
            model_name='exportlogtotal',
            constraint=models.UniqueConstraint(fields=('export_log', 'metric_key'), name='uq_export_log_total_metric'),
        ),
        migrations.AddConstraint(
            model_name='exportlogtotal',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'CNY')), name='ck_export_log_total_currency'),
        ),
        migrations.AddConstraint(
            model_name='exportlogtotal',
            constraint=models.CheckConstraint(condition=models.Q(('metric_key', ''), _negated=True), name='ck_export_log_total_metric_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='exportlogtotal',
            constraint=models.CheckConstraint(condition=models.Q(('metric_key__in', ('original_cost', 'opening_accumulated_depreciation', 'automatic_depreciation', 'manual_depreciation', 'adjustment_net', 'reversal_net', 'ending_accumulated_depreciation', 'impairment', 'ending_book_value', 'disposal_income'))), name='ck_export_log_total_metric_key'),
        ),
        migrations.RunPython(
            install_postgresql_guards,
            reverse_code=remove_postgresql_guards,
        ),
    ]
