# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reports", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="exportlog",
            name="export_type",
            field=models.CharField(
                verbose_name="导出类型",
                max_length=48,
                choices=[
                    ("asset_ledger", "公司资产总账"),
                    ("fixed_asset_detail", "固定资产明细"),
                    ("depreciation_schedule", "折旧计划"),
                    ("depreciation_detail", "折旧明细"),
                    ("monthly_depreciation", "月度折旧"),
                    ("department_assets", "部门资产"),
                    ("employee_assets", "人员资产"),
                    ("equipment_list", "设备清单"),
                    ("mold_tool_inspection_list", "模具工具检具清单"),
                    ("inventory_results", "盘点结果"),
                    ("inventory_differences", "盘点差异"),
                    ("maintenance_plans", "保养计划"),
                    ("maintenance_due", "到期保养"),
                    ("maintenance_records", "保养记录"),
                    ("offboarding_unresolved", "离职资产未清"),
                    ("disposal_list", "处置清单"),
                    ("supply_stock_balance", "当前库存余额表"),
                    ("supply_low_stock", "低库存预警表"),
                    ("supply_stock_movement", "库存收发存表"),
                    ("supply_stock_ledger", "库存流水明细表"),
                    ("supply_issue_detail", "领用明细表"),
                    ("supply_department_issue", "部门领用汇总表"),
                    ("supply_employee_issue", "员工领用汇总表"),
                    ("supply_custody_balance", "耐用品保管余额表"),
                    ("supply_custody_movement", "保管动作明细表"),
                    ("supply_count_difference", "盘点差异处理表"),
                    ("controlled_non_fixed_assets", "逐件受控非固定资产清单"),
                    ("supply_management_amount", "综合管理金额表"),
                    ("tplus_reconciliation", "T+ 人工对账"),
                ],
            ),
        )
    ]
