# Generated by Django 5.2.17 on 2026-09-28 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_remove_importbatch_ck_import_batch_status_fields_and_more'),
        ('reports', '0002_sprint18_supply_report_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_key', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=80, verbose_name='常用查询名称')),
                ('query', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('company', 'user', 'report_key', 'name'), name='uq_report_preset_owner_name')],
            },
        ),
    ]
